### ISSUE TITLE
Wrap or propagate exceptions instead of suppress and throw new one

### ISSUE THREAD

**Issue by AUlasen** [jdi-testing/jdi-light#1060]
Replace such logic:
```
catch (Exception ex) {
    throw new Exception("Some msg");
}
```
with such:
```
catch (Exception ex) {
    throw new Exception("Some msg", ex);
}
```
I suppose, it is better to add additional method to com.epam.jdi.light.common.Exceptions class:
```
public class Exceptions {
 ...

    public static RuntimeException exception(Throwable ex, String msg, Object... args) {
        String message = args.length == 0 ? msg : format(msg, args);
        return new RuntimeException(LINE_BREAK + message, ex);
    }

...
}
```
And use it this in case we want to propagate exception this way:
```
catch (Exception ex) {
    throw Exceptions.exception(ex, "Some msg");
}
```

Also, sometimes it is better to propagate Exceptions, because wrong type of exception will lead wrong type of test status in Allure reports. For example, methods from class `com.epam.jdi.light.actions.ActionProcessor` are used in assertion. They catch exception of type `AssertionError `and throw `RuntimeException`. Allure interpret tests with `RuntimeException` as broken instead of failed.

It will improve maintainability of code, because we won't lose stack trace with broken code.

**Comment by AlexeyGirin** [comment]
Demo has been done.
