### ISSUE TITLE
Add strict check of parameters in test.properties - FOR DECOMPOSE

### ISSUE THREAD

**Issue by AUlasen** [jdi-testing/jdi-light#1061]
Add strict check of parameters reading from test.properties and throw an exception if some of parameters are wrong. It will make JDI more user friendly.

1. Design code skeleton for parameter validation to enable per each parameter future development.
2. Define default directory for storing tests
3. Provide an example of test validation for one parameter - timeout.wait.element

**Comment by AlexeyGirin** [comment]
Closed since decomposed

**Comment by AlexeyGirin** [comment]
Demo has been done.
