### ISSUE TITLE
Identify extra elements added to BootStrap by Roman

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1077]
Identify extra elements added to BootStrap by Roman
Please provide a list of them

**Comment by AlexandraKozhevnikova** [comment]
<img width="499" alt="2019-10-17_15h52_46" src="https://user-images.githubusercontent.com/48656154/67011118-a3f76a80-f0f7-11e9-96c5-a15c113a94ec.png">

**Comment by AlexandraKozhevnikova** [comment]
- Каких классов нет в jdi-light-bootstrap, но эти элементы есть на getbootstrap.com

1. Forms
2. Input group
3. Jumbotron
4. Navs
5. Scrollspy
6. Toast

**Comment by AlexandraKozhevnikova** [comment]
- Какие классы есть в jdi-light-bootstrap, но эти элементы отсутствуют на getbootstrap.com

1. BaseImage
2. Checkbox
3. ColorSpinner
4. Image
5. Link
6. MultipleInputs
7. RadioButton
8. Text
9. TextArea
10. TextField
11. VectorImage
12. ButtonWithSpinner
13. DropdownExpand
14. RadioButtons

**Comment by DorohedoroRu** [comment]
[MultipleInputs](https://getbootstrap.com/docs/4.3/components/input-group/#multiple-inputs) вполне себе есть

**Comment by AlexandraKozhevnikova** [comment]
Итоги 06.11:

**Comment by AlexeyGirin** [comment]
Создать комиссию.
Порешать все пункты - создать все таски.

**Comment by AlexandraKozhevnikova** [comment]
Итоги 07.11 :
1) Рефакторить будем только то,что уходит наружу пользователям, то есть jdi-light-bootstrap. Тесты для внутреннего использования, по возможности, оставить без изменений.

2) Media object и Сard сделать пустыми классами наследуемые от Секции.

**Comment by AlexandraKozhevnikova** [comment]
Итоги 08.11: 
Обсудили dropdown
Решено реализовать:
BootstrapDropdown  DropdownMenu (Aндрей)
DropdownForm (Елена)

  | BootstrapDropdown | DropdownMenu |   | DropdownForm
-- | -- | -- | -- | --
в каких   репозиториях,  хранить | jdi-light-bootstrap | jdi-light-bootstrap |   | jdi-light-bootstrap-test
в каких  пакетах хранить | composite | composite |   | composite
от каких классов наследовать | Section | BootstrapDropdown |   | BootstrapDropdown
какие интерфейсы имплементить | hasAssert<BootstrapDropdownAssetr> | no |   | no
какие методы реализовать | получить  текст (буквы на плашке)        открыть выпадашку     закрыть выпадашку     проверить что выпадашка открыта     проверить что выпадашка скрыта      проверить цвет     получить цвет | оставшиеся   методы          методы связанные со списком доступных опций (getList()…) |   | no
какие поля реализовать | ?   collapseExpand | item list |   |  
что должно присутствовать в доке по этому элементу | composite     пример с формой | composite     пример со списком |   | composite

**Comment by AlexandraKozhevnikova** [comment]
Итоги 11.11

- Поля должны быть у джава классов, которые экстендят Секцию, у остальных классов, полей быть не должно.
 - У каждого класса должен быть набор ассертов под методы.

**Comment by AlexandraKozhevnikova** [comment]
Итоги 13.11 обсуждали Navs. Необходимо принять политическое решение по реализации. Мария и Андрей расскажут о своих взглядах о реализации.

**Comment by evasileva-epam** [comment]
26.11 Участники: @troe88, @splekhanov, @evasileva-epam.
**Toasts:**
Модуль в котором хранить класс элемента | jdi-light-bootstrap |  
Пакет в котором хранить класс элемента | composite |  
Классы, которые нужно унаследовать классу элемента | Section | Question to discuss on stand up
Интерфейсы, которые нужно имплементить классу элемента | Itoast |  
Методы класса | close(), getTitle(), getMessage() |  
Поля класса | - |  
Раздел документации, где нужно описать элемент | Bootstrap Composite elements |  
Комментарии по содержанию документации | - |  
Комментарии по содержанию документации | - |  
Методы, которые добавить в доку | - |

**Comment by AlexeyGirin** [comment]
Demo has been done.
