### ISSUE TITLE
Create hasAttribute(attributeName) assertion method

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1078]
Create hasAttribute(attributeName) assertion method

Bootstrap related task ( #15 )

**Comment by troe88** [comment]
Demo has been done.

**Comment by troe88** [comment]
1. Implement unit tests

**Comment by AlexeyGirin** [comment]
Contact w/@Delnote for details

**Comment by AlexeyGirin** [comment]
Contact w/ @mf-code for approach definition

**Comment by AlexeyGirin** [comment]
1. Назначить митинг с @RomanIovlev и @mf-code (на 15 минут) для решения проблемы открытия браузера
2. Закончить покрытие тестами

**Comment by AlexeyGirin** [comment]
Demo has been done.
