### ISSUE TITLE
Refactor method getDriver(String driverName) from class WebDriverFactory

### ISSUE THREAD

**Issue by AUlasen** [jdi-testing/jdi-light#1084]
Refactor method
`public static WebDriver getDriver(String driverName)`
from class 
`com.epam.jdi.light.driver.WebDriverFactory`
to reduce it complexity and resolve codacy [issue](https://app.codacy.com/manual/jdi-testing/jdi-light/issues?bid=14601379&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbIldhcm5pbmciXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls1NTQ4XX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=)

**Comment by AlexeyGirin** [comment]
Please make Codacy to ignore this issue

**Comment by AlexeyGirin** [comment]
Demo has been done.
