### ISSUE TITLE
Fix frames

### ISSUE THREAD

**Issue by AUlasen** [jdi-testing/jdi-light#1104]
There is 3 tests with frame in JDI packages:
```
io.github.epam.tests.recommended.WindowsAndFramesTests::frameTest
io.github.epam.tests.epam.WindowsAndFramesTests::frameTest.WindowsAndFramesTests::frameTest
io.github.epam.html.tests.site.WindowsAndFramesTests::frameTest.WindowsAndFramesTests::frameTest
```

2 of them use frames? declared as `public class HomePageFrame {`, the third use frame declared as `public class HomePageFrame extends Section {`.

Case  `public class HomePageFrame {` doesn't work correctly, because of error while defining SearchContext. Tests are false positive, because frame contains the same page as is outside the frame.

Case `public class HomePageFrame extends Section {` work well with elements inside the frame, but throw an exception, when you try to call methods, which were inherited from Section and use Sectionas UI-element.

It is needed to fix frames behavior and corresponding tests.

**Comment by troe88** [comment]
Demo has been done.
