### ISSUE TITLE
Create a simple example for parallel tests execution: TestNG

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#1156]
As a JDI user, I wish to have examples that can help me to realize how JDI works in a parallel mode with TestNG runner.

Use jdi-templates project;
JDI should be included as a library;

Task started by Beata Chugunova. Preliminary version is at https://github.com/BeataChu/JDI-parallel-template (please do not hesitate to contact her). Anyway tests execution in a multi-thread mode is unstable for now.

**Comment by romaha08** [comment]
Demo has been done
