### ISSUE TITLE
Add non-static site initialisation example

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#1169]

**Comment by vladb00mer** [comment]
waiting for review in branch https://github.com/jdi-testing/jdi-light/tree/1169-Add-non-static-site-initialisation-example

**Comment by vladb00mer** [comment]
passed test case is here: jdi-light/jdi-light-examples/src/test/java/io/github/epam/tests/nonstatic/NonStaticSiteTests.java

**Comment by AlexeyGirin** [comment]
Code is ok.
Waiting for Documentation

**Comment by vladb00mer** [comment]
Documentation updated here: https://jdi-docs.github.io/jdi-light/?java#non-static-site-initialization

**Comment by AlexeyGirin** [comment]
Waiting documentation re-design and pr merge

**Comment by vladb00mer** [comment]
documentation updated, waiting for PR approve and merge

**Comment by AlexeyGirin** [comment]
Demo has been done.

**Comment by troe88** [comment]
Demo has been done.
