### ISSUE TITLE
Fix documentation for every element which uses checkbox

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#1176]

**Comment by VeronikaRevjakina** [comment]
1) Checkbox default fix table +fix located class+ fix test on the right+ link on test examples
2)Checkbox default inline fix located class+fix table+ fix "Button group"+ fix link + fix test on the right
3)Radio button and checkbox without labels fix located class+ fix table?+ fix "Button group"+ fix test on the right
4)Checkbox custom fix located class+ fix link+ fix test on the right
5)Custom disabled  fix located class+fix table+ fix "Button group"+ fix test on the right
6)Switches custom fix located class+fix table+ fix "Button group"+ fix test on the right
