### ISSUE TITLE
Fix timers for absent elements

### ISSUE THREAD

**Issue by RomE-HK** [jdi-testing/jdi-light#1197]
Could be checked in these branch
https://github.com/jdi-testing/jdi-light/tree/timers_of_missing_elements

Here is the test for it
ButtonTests.java:167
See
project jdi-light
\jdi-light\src\main\java\com\epam\jdi\light\elements\common\UIElement.java
you need to review the implementation of the displayed() method or add a special method to check for the missing element

line 627:    protected boolean displayed() {
line 629:            if (getWebElement().isDisplayed())
line 633:            return result.size() == 1 && result.get(0).isDisplayed();

**Comment by RomE-HK** [comment]
Could be checked in these branch
https://github.com/jdi-testing/jdi-light/tree/timers_of_missing_elements

**Comment by RomE-HK** [comment]
"C:\Program Files\Java\jdk1.8.0_231\bin\java.exe" -ea -javaagent:C:\Users\Roman_Bordiugov\.m2\repository/org/aspectj/aspectjweaver/1.9.1/aspectjweaver-1.9.1.jar -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3\lib\idea_rt.jar=56746:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3\plugins\testng\lib\testng-plugin.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_231\jre\lib\rt.jar;C:\Users\Roman_Bordiugov\IdeaProjects\jdi-light\jdi-light-html-tests\target\test-classes;C:\Users\Roman_Bordiugov\IdeaProjects\jdi-light\jdi-light-html-tests\target\classes;C:\Users\Roman_Bordiugov\IdeaProjects\jdi-light\jdi-light-html\target\classes;C:\Users\Roman_Bordiugov\IdeaProjects\jdi-light\jdi-light\target\classes;C:\Users\Roman_Bordiugov\.m2\repository\com\epam\jdi\tools\jdi-light-saber\2.0.60\jdi-light-saber-2.0.60.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\code\gson\gson\2.8.5\gson-2.8.5.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.8\jackson-databind-2.9.8.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.8\jackson-core-2.9.8.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\logging\log4j\log4j-api\2.11.1\log4j-api-2.11.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\logging\log4j\log4j-core\2.11.1\log4j-core-2.11.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\logging\log4j\log4j-slf4j-impl\2.11.1\log4j-slf4j-impl-2.11.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\logging\log4j\log4j-1.2-api\2.11.1\log4j-1.2-api-2.11.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-java\4.0.0-alpha-3\selenium-java-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-api\4.0.0-alpha-3\selenium-api-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\4.0.0-alpha-3\selenium-chrome-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\guava\guava\27.1-jre\guava-27.1-jre.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\checkerframework\checker-qual\2.5.2\checker-qual-2.5.2.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\errorprone\error_prone_annotations\2.2.0\error_prone_annotations-2.2.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.17\animal-sniffer-annotations-1.17.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-chromium-driver\4.0.0-alpha-3\selenium-chromium-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-devtools\4.0.0-alpha-3\selenium-devtools-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-http\4.0.0-alpha-3\selenium-http-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-json\4.0.0-alpha-3\selenium-json-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\4.0.0-alpha-3\selenium-edge-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-edgehtml-driver\4.0.0-alpha-3\selenium-edgehtml-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\4.0.0-alpha-3\selenium-firefox-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-firefox-xpi-driver\4.0.0-alpha-3\selenium-firefox-xpi-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\4.0.0-alpha-3\selenium-ie-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\4.0.0-alpha-3\selenium-opera-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\4.0.0-alpha-3\selenium-remote-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\squareup\okhttp3\okhttp\4.0.1\okhttp-4.0.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\squareup\okio\okio\2.2.2\okio-2.2.2.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.3.40\kotlin-stdlib-1.3.40.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.3.40\kotlin-stdlib-common-1.3.40.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\opentracing\opentracing-api\0.33.0\opentracing-api-0.33.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\net\bytebuddy\byte-buddy\1.9.12\byte-buddy-1.9.12.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\4.0.0-alpha-3\selenium-safari-driver-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\seleniumhq\selenium\selenium-support\4.0.0-alpha-3\selenium-support-4.0.0-alpha-3.jar;C:\Users\Roman_Bordiugov\.m2\repository\net\lingala\zip4j\zip4j\2.2.4\zip4j-2.2.4.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\github\bonigarcia\webdrivermanager\3.7.1\webdrivermanager-3.7.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar;C:\Users\Roman_Bordiugov\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Roman_Bordiugov\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\rauschig\jarchivelib\1.0.0\jarchivelib-1.0.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\commons\commons-compress\1.18\commons-compress-1.18.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\jsoup\jsoup\1.11.3\jsoup-1.11.3.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\aspectj\aspectjrt\1.9.1\aspectjrt-1.9.1.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\hamcrest\hamcrest\2.2\hamcrest-2.2.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\commons\commons-lang3\3.9\commons-lang3-3.9.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure-testng\2.7.0\allure-testng-2.7.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure-descriptions-javadoc\2.7.0\allure-descriptions-javadoc-2.7.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure-java-commons\2.7.0\allure-java-commons-2.7.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure2-model-api\1.0.0\allure2-model-api-1.0.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure2-model-pojo\1.0.0\allure2-model-pojo-1.0.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\apache\tika\tika-core\1.14\tika-core-1.14.jar;C:\Users\Roman_Bordiugov\.m2\repository\io\qameta\allure\allure2-model-jackson\1.0.0\allure2-model-jackson-1.0.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.7.0\jackson-module-jaxb-annotations-2.7.0.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\jooq\joor-java-8\0.9.9\joor-java-8-0.9.9.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\Roman_Bordiugov\.m2\repository\org\testng\testng\7.0.0-beta1\testng-7.0.0-beta1.jar;C:\Users\Roman_Bordiugov\.m2\repository\com\beust\jcommander\1.72\jcommander-1.72.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3\plugins\testng\lib\jcommander-1.27.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket56745 @w@C:\Users\Roman_Bordiugov\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\Roman_Bordiugov\AppData\Local\Temp\idea_testng.tmp



[ STEP 41:59.096] : Open 'Home Page'(url=https://jdi-testing.github.io/jdi-light/index.html) (Home Page)
[ INFO 42:01.215] : Using chromedriver 78.0.3904.70 (since Google Chrome 78 is installed in your machine)
[ INFO 42:01.256] : Exporting webdriver.chrome.driver as C:\Users\Roman_Bordiugov\.m2\repository\webdriver\chromedriver\win32\78.0.3904.70\chromedriver.exe
[ INFO 42:01.258] : Download driver: 'CHROME X32' successfully
Starting ChromeDriver 78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}) on port 47502
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1573227726.545][WARNING]: Timed out connecting to Chrome, retrying...
Nov 08, 2019 6:42:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[ INFO 42:08.681] : Page: Home Page
[ INFO 42:08.682] : Set timeout 30 seconds
[ INFO 42:09.777] : Run Tests


[ STEP 42:09.849] : ShouldBeLoggedIn
[ STEP 42:09.881] : Check that 'User Name' is hidden (User Name)
[ STEP 42:09.982] : >>> true
[ STEP 42:09.983] : Login
[ STEP 42:09.984] : Check that 'Login Form' is hidden (Login Form)
[ STEP 42:10.061] : >>> true
[ STEP 42:10.073] : Click on 'User Icon' (User Icon)
[ STEP 42:10.482] : Submit 'Login Form' with User(name:Roman; password:Jdi1234) (Login Form)
[ STEP 42:11.037] : 'Html5 Page'(url=https://jdi-testing.github.io/jdi-light/html5.html) should be opened (Html5 Page)
[ INFO 42:11.041] : Page: Html5 Page
[ INFO 42:11.042] : Set timeout 30 seconds
[ INFO 42:11.054] : Check that page url(https://jdi-testing.github.io/jdi-light/index.html) contains '/html5.html'
[ INFO 42:11.576] : Check that page url(https://jdi-testing.github.io/jdi-light/html5.html) contains '/html5.html'


[ STEP 42:11.773] : Check that 'Missing Button' is displayed (Missing Button)
[ STEP 42:31.868] : >>> false
[ STEP 42:31.869] : Assert that 'Missing Button' disappeared (Missing Button)
[ STEP 42:51.983] : >>> HtmlElementsPage.missingButton (css='#missing-button')




===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

**Comment by RomE-HK** [comment]
I'll run this test at home few more times, 'cause yesterday at home PC it didn't crash
Maybe some dependencies are different

**Comment by RomE-HK** [comment]
After `mvn clean compile` the bug are reproducing

**Comment by AlexeyGirin** [comment]
Issues could be reproduced if you run test from jar file.
If it run from Idea - works correct

**Comment by AlexeyGirin** [comment]
Please implement solution suggested by @RomanIovlev

**Comment by romaha08** [comment]
Task is closed as it's already in bootstrap branch and will be merged in master by R.Iovlev
