### ISSUE TITLE
Can not load Boolean property from browser capabilities property file

### ISSUE THREAD

**Issue by robotizeitall** [jdi-testing/jdi-light#1206]
When I am trying to initialise RemoteWebDriver using property file I have next error message:

 `Drivers: chrome:com.epam.jdi.light.driver.WebDriverFactory$$Lambda$100/1157624710@281b2dfd; Run: Exception:  
Failed to setup remote chrome driver. Exception: json: cannot unmarshal string into Go struct field Caps.enableVNC of type bool (WARNING: The server did not provide any stacktrace information)
`

Example of my test.properties file:

`driver=chrome
chrome.capabilities.path=chromecapabilities.properties
domain=https://domain.com:8880/`

Example of my chromecapabilities.properties file:
`browserName=chrome
version=77.0
enableVNC=true`

As I investigated the problem is in DriverData class. 

`public static Map<String,String> CAPABILITIES_FOR_CHROME = new HashMap<>();`
stores only String values, but for correct 'enableVNC' capability initialisation it is necessary to initialise it as boolean value.

**Comment by RomanIovlev** [comment]
Fixed in 1.1.14
