### ISSUE TITLE
Create a single page in "Elements packs > Bootstrap Form Example"

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#1217]
In the context of #15 decomposition

This particular page should consist of two forms:

- Simple
   - TextInput
   - TextArea
   - Button x2 (submit and cancel)
- Complicated
   - Checkbox
   - Dropdown
   - Radiobutton
   - Button x2 (submit and cancel)

You can include whatever bootstrap element you want if needed.

**Comment by troe88** [comment]
This particular page should consist of two forms:

- Simple
   - TextInput
   - TextArea
   - Button x2 (submit and cancel)
- Complicated
   - Checkbox
   - Dropdown
   - Radiobutton
   - Button x2 (submit and cancel)

You can include whatever bootstrap element you want if needed.

**Comment by AlexeyGirin** [comment]
Demo has been done.
