### ISSUE TITLE
Fix RadioButtons control in BootStrap

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1250]
Bootstrap related task (#15 )

1. Replace RadioButton with RadioButtons (rename or replace) - merge RadioButton into RadioButtons (make it thru WebList and Labels)
2. Updrade WebList if needed
3. Fix action methods

**Comment by AlexeyGirin** [comment]
Please describe your expectation from this issue

**Comment by VeronikaRevjakina** [comment]
1. Use div locator on radioButton instead of input
2. Override methods @JDIAction("Check that '{name}' is selected")
    public boolean isSelected() {
        return input.isSelected();
    }

    @JDIAction("Check that '{name}' is enabled")
    public boolean isEnabled() {
        return input.isEnabled();
    } in such way +  @JDIAction("Click at '{name}'")
    public void click() {
            label().click();
    }

    public Label label() {
        return input.label();
    }.
3. Improve all tests which use RadioButton
4. Remove RadioButtons class & Fix its usage in 1 test InputGroupInputWithRadio

**Comment by AlexeyGirin** [comment]
Demo has been done.
