### ISSUE TITLE
Fix info level Codacy found issues: Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1261]
List of issues: https://app.codacy.com/manual/jdi-testing/jdi-light/issues?bid=14601379&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbIkluZm8iXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls1MjczXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=

1. Learn the problem
2. Get confirmation from @mf-code or @RomanIovlev that we have to fix them such cases
3. Fix them if confirmed or suppress otherwise (ask @hellokitties - she know-how)

**Comment by AlexeyGirin** [comment]
238

**Comment by vladb00mer** [comment]
PR created

**Comment by AlexeyGirin** [comment]
Demo has ben done.
