### ISSUE TITLE
Create dedicated test page for Appium integration

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1268]
In the context of #1240 decomposition

Create a dedicated test page for Appium integration - just use the copy of regular (HTML5) one for the first time

**Comment by RomE-HK** [comment]
Done. PR created

**Comment by AlexeyGirin** [comment]
Demop has been done.

**Comment by RomE-HK** [comment]
https://jdi-testing.github.io/jdi-light/mobile-html5.html
