### ISSUE TITLE
Fix JList and WebList . The  JList and WebList  do not work correctly with web elements that have the same text

### ISSUE THREAD

**Issue by dancingolav** [jdi-testing/jdi-light#1272]
The issue related to task **Implement tests that clarified JList issue #1228.** 
JList does not collect UIElements correctly since it converts the list of elements found
to MapArray using as a key the elements text. As a result forEach loop will not process elements with the same text.

**Comment by dancingolav** [comment]
JList does not collect UIElements correctly since it converts the list of elements found
to MapArray using as a key the elements text. As a result forEach loop will not process elements with the same text.

**Comment by RomanIovlev** [comment]
Already implemented
