### ISSUE TITLE
Create Contact Form Test on Pure Selenium

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#128]
For our tutorial, we need to create test scenario for [Contact Form - fillContactFormTest()](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-examples/src/test/java/io/github/epam/tests/recommended/FormsTests.java)
on pure Selenium
This should be a separate project without JDI Dependencies with minimum action to do the same scenario.<br/>
Scenario:<br/>
- Open Home page (https://jdi-testing.github.io/jdi-light/index.html )<br/>
- Login with Default user (Roman/Jdi1234)<br/>
- Open Contact Page from menu<br/>
- Fill all 11 different elements in this Complex form by some values (see values in jdi test by link above)<br/>
- And validate that form filled correctly<br/>

You need to create:
1) Page Object for Login
2) Page Object for Contact Page
3) Test Scenario

**Comment by vladb00mer** [comment]
this task is implemented here: https://github.com/vladb00mer/PureSelenium.git

**Comment by AlexeyGirin** [comment]
Please close the issue once it is not necessary any more

**Comment by vladb00mer** [comment]
code was updated to work under windows, ok

**Comment by RomanIovlev** [comment]
Please add in the project:
1. Make fillContactForm method more Generic. That means it depends on data input
2. Develop one more test in the same test class that fills only text fields in the Contact form
* Move common parts of both tests like PO init and log in separately
3. Add Form data validation in both tests in order to check that data you input is in form fields and other elements

**Comment by AlexeyGirin** [comment]
Waiting p.3 to complete

**Comment by vladb00mer** [comment]
implemented and tested - ok

**Comment by AlexeyGirin** [comment]
@RomanIovlev to review

**Comment by RomanIovlev** [comment]
Vlad,

1. Please add gitignore from jdi project in your project
2. Please correct textFieldsTest(): fill and validate ONLY TextFields: 
Name, LastName, Position, Number, Seria

**Comment by AlexeyGirin** [comment]
Demo has been done.
