### ISSUE TITLE
Refactor  bootstrap  element - Card

### ISSUE THREAD

**Issue by AlexandraKozhevnikova** [jdi-testing/jdi-light#1287]
Линки на эпики #15  и на #1077 

В рамках данного эпика работаем только с модулем _jdi-light-bootstrap._  
Модуль jdi-light-bootstrap-test оставляем без изменений по возможности.

**Что нужно сделать/проверить что сделано:**
- в каких репозиториях хранить:  jdi-light-bootstrap (В этом модуле должен быть только один класс Card. Других классов Card (дублей или подтипов быть не должно)
- к какой группе относится элемент: composite 
- от каких классов наследовать и какие интерфейсы имплементить: наследовать от Section
- какие методы и поля реализовать: пустой класс
- что должно присутствовать в доке по этому элементу: В документации описание должно быть в разделе composite 

**Ссылки:**
https://getbootstrap.com/docs/4.3/components/card/
https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap

**Comment by troe88** [comment]
Demo has been done.
