### ISSUE TITLE
Refactor bootstrap element - Media-object

### ISSUE THREAD

**Issue by AlexandraKozhevnikova** [jdi-testing/jdi-light#1288]
Линки на эпики #15 и на #1077

В рамках данного эпика работаем только с модулем _jdi-light-bootstrap._
Модуль jdi-light-bootstrap-test оставляем без изменений по возможности.

**Что нужно сделать/проверить что сделано:**

- в каких репозиториях хранить: jdi-light-bootstrap  (В этом модуле должен быть только один класс Media-object. Других классов Media-object (дублей или подтипов быть не должно)

 - к какой группе относится элемент: пакет composite 
от каких классов наследовать и какие интерфейсы имплементить: наследовать от Section
 - какие методы и поля реализовать: пустой класс
 - что должно присутствовать в доке по этому элементу: Фраза в документации «Media object is represented by Section class in Java:» неверна. Media object is represented by MediaObject class. MediaObject class is inherited from Section class. И соответственно нужна ссылка в документации на MediaObject class.
В документации описание должно быть в разделе composite 

**Ссылки:**
Сайт getbootstrap https://getbootstrap.com/docs/4.3/components/media-object/
Сайт JDI https://jdi-testing.github.io/jdi-light/bootstrap.html#media-object
Дока JDI -  https://jdi-docs.github.io/jdi-light/#media-object
Тесты на GitHub - https://github.com/jdi-testing/jdi-light/blob/bootstrap/jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/composite/section/mediaObject/MediaObjectTests.java

**Comment by vladb00mer** [comment]
- в каких репозиториях хранить: jdi-light-bootstrap (В этом модуле должен быть только один класс Media-object. Других классов Media-object (дублей или подтипов быть не должно): **пустой класс MediaObject присутствует в единственном экземпляре в пакете com.epam.jdi.light.ui.bootstrap.elements.complex**

**Comment by vladb00mer** [comment]
- к какой группе относится элемент: пакет composite
от каких классов наследовать и какие интерфейсы имплементить - наследовать от Section: класс наследуется от Section, перенесен из пакета com.epam.jdi.light.ui.bootstrap.elements.complex  в пакет com.epam.jdi.light.ui.bootstrap.elements.composite с изменением всех вызовов класса

**Comment by vladb00mer** [comment]
- какие методы и поля реализовать: пустой класс: **уже реализован**

**Comment by vladb00mer** [comment]
- PR ждет CR в ветке bootstrap-vmurashov

**Comment by vladb00mer** [comment]
- что должно присутствовать в доке по этому элементу: Фраза в документации «Media object is represented by Section class in Java:» неверна. Media object is represented by MediaObject class. MediaObject class is inherited from Section class. И соответственно нужна ссылка в документации на MediaObject class.
В документации описание должно быть в разделе composite: **https://jdi-docs.github.io/jdi-light/#media-object**

**Comment by AlexeyGirin** [comment]
Demo has been done.
