### ISSUE TITLE
Add dependency in jdi-light-bootstrap to  jdi-light-html-elements 

### ISSUE THREAD

**Issue by AlexandraKozhevnikova** [jdi-testing/jdi-light#1289]
In the context of #15  #1077 

1. В jdi-light-bootstrap сделать депенденси от jdi-light-html и использовать их реализацию
2. Вычистить появившиеся дубли в jdi-light-bootstrap и jdi-light-bootstrap-test
3. Документация. Перепроверить ссылки на дубли, все ссылки должны вести на html-элементы

**Comment by AlexeyGirin** [comment]
1. Waiting for PR
2. Waiting for list of duplicate elements for creating redicated task for their eliminations
3. Documentation demo

**Comment by AlexeyGirin** [comment]
Closed.
