### ISSUE TITLE
Add Java Docs for jdi-light-html JDIAction

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#13]
Add Java docs for methods in [jdi-light-html interfaces](https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html) marked with @JDIAction annotation

**Comment by owl-se** [comment]
On it

**Comment by AlexeyGirin** [comment]
Demo has been done.
