### ISSUE TITLE
Add tests and documentation for Section composite element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#130]
Write documentation on all methods for
Section - This means to add different types of elements on section and validate that they are not null after Section init (via Site) and use Section (parent) locator as context
public WebElement
WebElement
public static WebElement
public TextField
TextField
public static TextField
extend PageObject from some BaseClass that extends Section (public class Header extends BasePage; public class BasePage extends Section); place some elements on Base Page and validate that these elements are not null
    Create Section for IFrame with @frame annotation (use this page https://jdi-testing.github.io/jdi-light/index.html) and validate that elements in IFrame are intractable
    Validate that Base action also work for section (like isDisplayed and all is() validations)
    Add tests for PageObjects that not extend Section and placed on some WebPage

Tests should be located at dedicated directory on the same level as complex and common

**Comment by PetelimovaNadezhda** [comment]
https://github.com/jdi-testing/jdi-light/pull/147
