### ISSUE TITLE
Add Review policy to Documentation portal

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1305]
Add Review principals doc to Documentation portal

Code review policy could be obtained here: https://epam-my.sharepoint.com/:t:/r/personal/dmitrii_fentcik_epam_com/Documents/JDI_meeting_materials/review_guide.md?csf=1&e=fjHuzh

**Comment by vladb00mer** [comment]
done

**Comment by AlexeyGirin** [comment]
Demo has been done.
