### ISSUE TITLE
Refactor bootstrap element - Progress

### ISSUE THREAD

**Issue by AlexandraKozhevnikova** [jdi-testing/jdi-light#1309]
Линки на эпики #15 и на #1077

В рамках данного эпика работаем только с модулем jdi-light-bootstrap.
Модуль jdi-light-bootstrap-test оставляем без изменений по возможности.

Элементы для реализации | Progress | MultiplebarsProgress
-- | -- | --
в каких репозиториях,  хранить | bootstrap | bootstrap
в каких  пакетах хранить | common | complex
от каких классов наследовать | UIBaseElement\<ProgressAssert\> | JList\<Progress\>
какие   интерфейсы имплементить |интерфейсы не нужны | интерфейсы не нужны
какие методы реализовать | getAriaValue () - переименовать   метод в getValue()     метод getText() для получения "25%"     переименовать ассерты на методы в ProgressAssert | методы для листа (размеры,   количество, лейблы)
какие поля   реализовать | Без   полей | Без полей
дока хранится в разделе | common | complex
что должно  быть в доке |  Добавить ссылку на элемент MultiplebarsProgress, который будет храниться в другом разделе документации, чтобы была связь этих элементов , картинок сделать несколько (на все виды прогресса , а таблицу с методами сделать одну, так как она ко всем програссам будет относиться |  Добавить ссылку на Progress 

После создания всех изменений в jdi-light-bootstrap, необходимо в jdi-light-bootstrap-test удалить дублирующие сущности, и пофиксить проблемы связанные с удалением дублей.
Проверить правильное расположение тестов по пакетам.

Cсылки:
Сайт getbootstrap - https://getbootstrap.com/docs/4.3/components/progress/
Сайт JDI  -  https://jdi-testing.github.io/jdi-light/bootstrap.html
Дока JDI -   https://jdi-docs.github.io/jdi-light/#progress
Тесты на GitHub -  https://github.com/jdi-testing/jdi-light/blob/bootstrap/jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/common/progress/ProgressBaseTests.java

**Comment by AlexeyGirin** [comment]
Demo has been done.
