### ISSUE TITLE
Add tests and documentation for Form composite element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#131]
Write documentation on all methods for
Form
    Validate all form actions
    Validate changing FILL_ACTION and GET_ACTION methods
    Validate filters functionality
    Add test for form with overridden fillAction() and getAction()

Tests should be located at dedicated directory on the same level as complex and common

**Comment by ksenia-vyushkova** [comment]
https://github.com/jdi-testing/jdi-light/pull/147 - awaiting review, awaiting #132 to be added
https://github.com/jdi-docs/jdi-light/pull/102 - awaiting review, need info on what to do with C#

**Comment by AlexeyGirin** [comment]
Demo has been done.
