### ISSUE TITLE
Add tests and documentation for WebPage composite element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#132]
Write documentation on all methods for WebPage

Add @url and @title validation tests with all combinations of these annotations params (including cases where some annotations missed)
Add tests on all Page actions
Add the same tests for WebPage as for Section
Add tests for PageObjects that not extend WebPage and placed on some Site

Tests should be located at dedicated directory on the same level as complex and simple

**Comment by AlexeyGirin** [comment]
Ссылочка на документацию
https://jdi-docs.github.io/jdi-light/?java

Ссылка на репозиторий 
https://github.com/jdi-testing/jdi-light 
 
Туториал 
https://jdi-docs.github.io/jdi-light/?java#tutorial 
 
Ссылка на репозиторий документации (автоматически протягивается на сайт по коммиту)
https://github.com/jdi-docs/jdi-light/blob/master/source/includes/_documentation.md

**Comment by vladb00mer** [comment]
- "Write documentation on all methods for WebPage": ready, but with lot of questions
repo is here(without PR): https://github.com/jdi-docs/jdi-light/blob/Task132WebPageDocs/source/includes/_documentation.md

**Comment by vladb00mer** [comment]
"Tests should be located at dedicated directory on the same level as complex and common" - can't find any test cases/classes in jdi-light repo(

**Comment by vladb00mer** [comment]
Waiting for the test samples in directory "/Users/b00mer/IdeaProjects/jdi-light/jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements"

**Comment by vladb00mer** [comment]
Самая важная часть тут инициализация - проверить что все инициализируется правильно во всех комбинациях (отдельная задача по методам WebPage и Form не буду ее касаться)
По инициализации. чтобы покрыть все комбинации и ускорить прохождение тестов, лучше создать отдельный псевдо Сайт с псведо "не реальными" элементами
Для этого сайта создать Пейджобджекты всех возможных вариантов с различными элементами и проверить что после запуска initElements - все элементы "инициализировались"
Это значит, что они 
1) как минимум не null, 
2) у них есть правильный локатор, 
3) есть правильный parent
4) У них правильное name

Виды PageObjects которые надо проверить: 
1) SomeSite.cs
@UI("") public static SomeSection …; -> SomeSection extends Section
public static SomeSection …;
@UI("") public static ExtendedSection …; -> ExtendedSection extends SomeSection extends Section
public static ExtendedSection …;
@UI("") public static SomeObject …;-> public class SomeObject {…}
public static SomeObject …;
@UI("") public static ExtendedObject …; -> ExtendedSection extends SomeObject {…}
public static ExtendedObject …;
@Url(...) @Title(...) public static SomePage …;
@Url(...) public static SomePage …;
@Title(...) public static SomePage …;
public static SomePage …;

**Comment by vladb00mer** [comment]
"Add @url and @title validation tests with all combinations of these annotations params (including cases where some annotations missed)": done but with some questions, pushed to branch "https://github.com/jdi-testing/jdi-light/tree/composite_elements_tests_(issues_130_131_132)"

**Comment by vladb00mer** [comment]
"Add tests on all Page actions" - all tests are passed, pushed into branch "https://github.com/jdi-testing/jdi-light/tree/composite_elements_tests_(issues_130_131_132)"

**Comment by AlexeyGirin** [comment]
Скопипастить с секшана

**Comment by AlexeyGirin** [comment]
@RomanIovlev please contact w/ @vladb00mer regarding this task

**Comment by AlexeyGirin** [comment]
@RomanIovlev, please update the documentation

**Comment by AlexeyGirin** [comment]
Demo has been done.
