### ISSUE TITLE
Research and remove obsolette Form tests

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1326]
Contact w/@RomE-HK

**Comment by VeronikaRevjakina** [comment]
Removed:
+ all tests with obsolette Forms 
+classes for its declarations (e.g.jdi-light-bootstrap-tests\src\main\java\io\github\com\sections\form\FormBrowserDefaults.java and so on)
+ mentions on BootstrapPage
whole (34 files)

Left 2 unused classes:
entities:(\jdi-light-bootstrap-tests\src\main\java\io\github\com\entities\)
FormSignUp.java
FormUsers.java

**Comment by AlexeyGirin** [comment]
No demo possible
