### ISSUE TITLE
Create documentation for DataTable (Java)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#133]
Use other elements description as an example

**Comment by igordien** [comment]
Following methods aren't used in tests; new tests with these methods should be created:

- allLines() 
- data(java.lang.Enum rowName)
- data(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- data(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- data(com.epam.jdi.light.elements.complex.table.TableMatcher... matchers)
- datas(com.epam.jdi.light.elements.complex.table.TableMatcher... matchers)
- filterData(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- filterDatas(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- filterLines(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- filterLines(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- line(java.lang.Enum rowName)
- line(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- line(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- line(com.epam.jdi.light.elements.complex.table.TableMatcher... matchers)
- lines(com.epam.jdi.light.elements.complex.table.TableMatcher... matchers)
- shouldBe()
- waitFor()

**Comment by AlexeyGirin** [comment]
1. Add kind of legend for Return Types
2. Add "old" (FindBy) declaration

**Comment by igordien** [comment]
Documentation has been correspondingly updated

**Comment by AlexeyGirin** [comment]
Demo has been done.
