### ISSUE TITLE
Update documentation for Table (Java and C#)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#134]
Java:
Create all code examples
Add the link to Java tests

C#
Add initialization code examples

**Comment by AlexeyGirin** [comment]
Waiting for fixing found issues in documentation

**Comment by igordien** [comment]
Following methods aren't used in tests; new tests with these methods should be created:

- column(java.lang.Enum colName) 
- columns() 
- filterRows(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- filterRows(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- isEmpty() 
- isNotEmpty() 
- row(java.lang.Enum rowName)
- row(org.hamcrest.Matcher<java.lang.String> matcher, com.epam.jdi.light.elements.complex.table.Column column)
- row(com.epam.jdi.tools.pairs.Pair<org.hamcrest.Matcher<java.lang.String>, com.epam.jdi.light.elements.complex.table.Column>... matchers)
- shouldBe() 
- waitFor()

**Comment by AlexeyGirin** [comment]
Add FindBy declaration

**Comment by igordien** [comment]
Declaration has been added

**Comment by AlexeyGirin** [comment]
Demo has been done.
