### ISSUE TITLE
Add strict check of parameters in test.properties: screens.folder browser.kill element.search.strategy

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1340]
In the context of #1061 decomposition

Add strict check of parameters reading from test.properties and throw an exception if some of parameters are wrong. It will make JDI more user friendly.
Parameters: 
1. screens.folder
2. browser.kill
3. element.search.strategy

For given parameters you have to:
1. Add boundary (if applicable) and other possible validations
2. Cover these checks with tests (including negative)  - BOOTSTRAP branch!
3. Describe each parameter in documentation (including the definition of valid value range)

**Comment by troe88** [comment]
Demo has been done.
