### ISSUE TITLE
Replace screenshots of HTML code with native HTML blocks for Bootstrap elements

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1349]
Replace screenshots of HTML code with native HTML blocks for Bootstrap elements

Usually, these pictures follow after "Here is an example with provided Bootstrap v4.3 code:" string in the documentation.
Use the same markup language as in any HTML5 element (see https://jdi-docs.github.io/jdi-light/#checkbox as an example)

**Comment by troe88** [comment]
Demo has been done.
