### ISSUE TITLE
Fix Travis Build

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#139]
Unfortunately, Travis doesn't work with Java Windows
We should run tests on Linux or OSx
1. You can manage this in .travis.yml in project's root https://github.com/jdi-testing/jdi-light
Add "os: osx" in this file [See details](https://docs.travis-ci.com/user/reference/osx/)
Or just run Travis without this option (in this case will be used Linux)
2. Observe build log and try to identify the issue. https://travis-ci.com/jdi-testing/jdi-light

>> Now on Linux build fails because can't run WebDriver.
>> Maybe the problem appears because Travis can't download the driver successfully or some other reasons.
>> Reasons in logs are not clear, maybe it will be good to add more logs in driver init and run in order to get the problem
* Be sure that all tests pass on your computer with "mvn clean install" command

**Comment by vladb00mer** [comment]
all tests success:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JDI Light 1.0.57 ................................... SUCCESS [ 17.526 s]
[INFO] JDI Web Tests 1.0-SNAPSHOT ......................... SUCCESS [05:02 min]
[INFO] JDI Light Html Elements 1.0.57 ..................... SUCCESS [  4.337 s]
[INFO] JDI Html Tests 1.0.57 .............................. SUCCESS [05:41 min]
[INFO] JDI Performance 1.0 ................................ SUCCESS [ 15.125 s]
[INFO] JDI UI 2.0 1.0.19 .................................. SUCCESS [  0.031 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:21 min
[INFO] Finished at: 2019-05-13T16:05:47+03:00
[INFO] ------------------------------------------------------------------------

**Comment by vladb00mer** [comment]
file ".travis.yml" is modified:

os: osx
language: java
script:
  - mvn clean verify -Ddriver=chrome
after_failure:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report

**Comment by vladb00mer** [comment]
same test result with new parameter "os: osx":

[INFO] Building JDI UI 2.0 1.0.19                                         [6/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jdi-2 ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jdi-2 ---
[INFO] Installing /Users/b00mer/IdeaProjects/jdi-light/pom.xml to /Users/b00mer/.m2/repository/com/epam/jdi/jdi-2/1.0.19/jdi-2-1.0.19.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JDI Light 1.0.57 ................................... SUCCESS [ 14.854 s]
[INFO] JDI Web Tests 1.0-SNAPSHOT ......................... SUCCESS [04:54 min]
[INFO] JDI Light Html Elements 1.0.57 ..................... SUCCESS [  4.580 s]
[INFO] JDI Html Tests 1.0.57 .............................. SUCCESS [05:44 min]
[INFO] JDI Performance 1.0 ................................ SUCCESS [ 10.685 s]
[INFO] JDI UI 2.0 1.0.19 .................................. SUCCESS [  0.034 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:08 min
[INFO] Finished at: 2019-05-13T16:40:44+03:00
[INFO] ------------------------------------------------------------------------

**Comment by AlexeyGirin** [comment]
Надо рабираться с кодом
Понять - почему он падает когда наш код запускает трэвис (добавить инвестигацию в проект что бы было понятно почему так)

**Comment by vladb00mer** [comment]
я нашел пару старых статей с подобной проблемой, но не нашел какую версию юзает Travis сейчас: https://stackoverflow.com/questions/40747770/travis-ci-build-failed-for-a-java-maven-project и http://qaru.site/questions/12841117/travis-ci-build-failed-for-a-java-maven-project

**Comment by vladb00mer** [comment]
вроде нашел описание поддерживаемых версий: 
https://docs.travis-ci.com/user/reference/precise/

тут, в частности, сказано:
JDK #
Oracle JDK 7 (oraclejdk7)
OpenJDK 7 (openjdk7)
OpenJDK 6 (openjdk6)
Oracle JDK 8 (oraclejdk8)
OracleJDK 7 is the default because we have a much more recent patch level compared to OpenJDK 7 from the Ubuntu repositories. Sun/Oracle JDK 6 is not provided because it reached End of Life in fall 2012.

The $JAVA_HOME will be set correctly when you choose the jdk value for the JVM image.

**Comment by AlexeyGirin** [comment]
Demo has been done.
