### ISSUE TITLE
Review all tests for the element and methods for that element in code and documentation: Carousel

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1398]
In the context of #15 
Decomposition of #1336

Review all tests for the element and methods for that element in code and documentation.
Element name: Carousel

1. Check if the given element has all methods in the documentation described - add missing methods (not ALL possible methods but methods that make sense for given element - i.e. applicable for it)
2. Add missing methods into documentation
3. Check if all methods covered with tests
4. Add missing tests to get all element methods covered

**Comment by ElenaPoduzova** [comment]
getText() 
currentSlide() is used in interval() method
nextControl() is covered by fadeNextTest()
next() is covered by fadeNextTest()
prevControl() is covered by fadePrevTest()
prev() is covered by fadePrevTest()
indicators()  is used in select() method
select(int index) is covered by selectTest()
get(int index) is covered by selectTest()
interval() is covered by intervalTest()
is() is covered by getSlidesTextTest()

**Comment by AlexeyGirin** [comment]
Waiting for Test section re-position

**Comment by AlexeyGirin** [comment]
Demo has been done.
