### ISSUE TITLE
Add Java Docs for jdi-light-html core other

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#14]
Add Java docs for all methods in [jdi-light-html](https://github.com/jdi-testing/jdi-light/issues/13)
Should be done after [Add Java Docs for jdi-light-html JDIAction](https://github.com/jdi-testing/jdi-light/issues/13)

**Comment by owl-se** [comment]
On it

**Comment by owl-se** [comment]
For this issue I've created branch "jdi-light-html-docs"

**Comment by PetelimovaNadezhda** [comment]
Current version in "jdi-light-html-docs"
