### ISSUE TITLE
Review all tests for the element and methods for that element in code and documentation: Popovers 

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1405]
In the context of #15 
Decomposition of #1336

Review all tests for the element and methods for that element in code and documentation.
Element name: Popovers

1. Check if the given element has all methods in the documentation described - add missing methods (not ALL possible methods but methods that make sense for given element - i.e. applicable for it)
2. Add missing methods into documentation
3. Check if all methods covered with tests
4. Add missing tests to get all element methods covered

**Comment by DaniilPavlov1** [comment]
1. Popover tab in **common elements** was deleted;
2. Refactor notes from right side of code to up;

**Comment by AlexeyGirin** [comment]
Demo has been done.
