### ISSUE TITLE
Documentation proofreading: JDI asserts in code snippets

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1420]
Everywhere
-----------
***JDI*** asserts in code snippets instead of other (separated to #1495)
Code snippets on one level with ***HTML*** code
Order of documentation parts for each element
Links to *Represented* - У нас там у сложных элементов есть ссылки на то, от чего они наследуются и из чего состоят. Так вот эти ссылки есть не везде

Ask @RomE-HK for details

**Comment by NataliaTikhomirova** [comment]
the first point separated to #1495

**Comment by AlexeyGirin** [comment]
Demo has ben done.
