### ISSUE TITLE
Documentation proofreading: HTML5 - MultiDropDown element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1434]
`MultiDropDown`
-----------
- rework or delete whole section
- right now ***JDI*** for ***Java*** doesn't have `MultiDropDown` class at all
- and `MultiSelect` (from example) class either
- 3 tables in *Methods*

Ask @RomE-HK for details

**Comment by troe88** [comment]
Demo has been done.
