### ISSUE TITLE
Documentation proofreading: HTML5 - DataList element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1435]
`DataList`
-----------
- split element's description and example from annotation's description and example
- 3 tables in *Methods*

Ask @RomE-HK for details

**Comment by hellokitties** [comment]
Also 
1.  There is  annotation @JDataList in the documentation, but it doesn't present in the code project
2.  We see methods DataListOptions  class,  not DataList as expected
3.  DataList class locates in package com.epam.jdi.light.elements.complex , not in com.epam.jdi.light.ui.html.complex.DataList. But DataListOptions  class located com.epam.jdi.light.ui.html.elements.complex. 
4.  In example code we also can see DataList element,  but in the actual test case is  used DataListOptions  class

**Comment by AlexeyGirin** [comment]
Decided to close
