### ISSUE TITLE
Investigate BaseImage and VectorImage classes

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#1446]
Investigate for what BaseImage and VectorImage classes were created in bootstrap.
Note that there's class Image connected to these classes.
*After investigation resolve https://github.com/jdi-testing/jdi-light/issues/1077 for these 2 parameters.

**Comment by romaha08** [comment]
BaseImage and VectorImage classes removed
ImageTests added
Documentation for Image added

**Comment by romaha08** [comment]
Demo has been done
