### ISSUE TITLE
Add bootstrap element - Toast

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#1448]
Линки на эпики #15 и на #1077

Сделать абстрактный(!) класс Toast.

|Column1 | - |
-- | -- |
Модуль в котором хранить класс элемента | jdi-light-bootstrap |
Пакет в котором хранить класс элемента | composite |
Классы, которые нужно унаследовать классу элемента | Section | 
Интерфейсы, которые нужно имплементить классу элемента | - |
Методы класса | close(), getTitle(), getMessage() |
Поля класса | - |
Раздел документации, где нужно описать элемент | Bootstrap Composite elements |
Комментарии по содержанию документации | - |
Методы, которые добавить в доку | см. "Методы класса" |

Проапдейтить документацию.

Ссылки:
https://getbootstrap.com/docs/4.3/components/toasts/

**Comment by AlexeyGirin** [comment]
1. Покрыть элемент тестами как это уже сделано в документации (используя новый абстрактный класс)
2. Обновить документацию - вписать новые пример
3. Старое описание тоаста (из пакета тестов) - вычистить

**Comment by NataliaTikhomirova** [comment]
реализовано, кроме тестов связанных с багом #1574

**Comment by troe88** [comment]
Demo has been done.
