### ISSUE TITLE
Research logging process in JDI

### ISSUE THREAD

**Issue by ElenaPoduzova** [jdi-testing/jdi-light#1451]
Check logging test steps to console and Allure report.

**Comment by ElenaPoduzova** [comment]
Методы логгирования находятся в классе JDILogger.
Отдельно прописаны методы для каждого уровня логов: step, trace, debug, info, error. В зависимости от настройки log.level в test.properties происходит обработка в ActionHelper в BEFORE_STEP_ACTION и AFTER_STEP_ACTION.

В случае, если log.level = STEP, то метод error не будет вызван.
Если выставить log.level = ERROR, то корректно отработавшие тесты будут записаны в лог как error.

Для проектов с тестами (например jdi-light-bootstrap-tests) дополнительно существует TestNGListener, в котором происходит обработка результатов выполнения теста и вызывает JDILogger.

Нужно убедиться, что в данный момент это корректное поведение логгирования.

**Comment by ElenaPoduzova** [comment]
Обработка степа происходит в public Object jdiAround(ProceedingJoinPoint jp)
там же вызываются методы ActionHelper: BEFORE_JDI_ACTION, AFTER_JDI_ACTION и ACTION_FAILED.
В ACTION_FAILED логгирование отсутсвует. Поэтому в отчете нет упавших степов.

**Comment by ElenaPoduzova** [comment]
В JDILogger подряд вызываются  getLifecycle().startStep(uuid, step) и getLifecycle().stopStep(uuid). Из-за этого время шага всегда 0. Нужно разнести вызовы на на начало и завершение шага.

**Comment by troe88** [comment]
Demo has been done.
