### ISSUE TITLE
Review JDI Settings and Driver Settings

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1456]
Review existed "JDI Settings" and "Driver Settings"
Make the following changes:
1. Move JDI Setting section followed after Driver Settings one
2. Put all settings content in JDI Settings into a table (in the same manner as it is done for Driver Settings)
3. Move all settings that didn't extend by JDI from JDI Settings to Driver Settings and vice versa (i.e. JDI Settings should contain only JDI settings or web driver settings that have changed behavior by JDI)

**Comment by troe88** [comment]
Demo has been done
