### ISSUE TITLE
Improve path parameters by making them cross-platform

### ISSUE THREAD

**Issue by splekhanov** [jdi-testing/jdi-light#1475]
**Description:**
In current solution using Unix file paths is not allowed. Framework changes them to Win style in some cases.

For example, JDI doesn't make changes to the specified paths for 'drivers.folder', whereas 'screens.folder' will be changed to Win style forcibly: "/screens/folder" -> "C:\Users\UserName\jdi-light\screens\folder"

**Objective:**
Need to develop an approach to process incoming paths _in the same style throughout the project_ and make them cross-platform.

Consider creation of PathUtils method and it's implementation in the required code areas
```
public static String getCrossPlatformPath(String path) {
    path.replaceAll("[\\\\|/]", Matcher.quoteReplacement(File.separator);
}
```
**Example:**
```
String screensFilePath = getFileName(mergePath(
    getPath(), name + nowTime(dateFormat)));
new File(screensFilePath).getParentFile().mkdirs();
```
turns to
```
String screensFilePath = PathUtils.getCrossPlatformPath(getFileName(mergePath(
    getPath(), name + nowTime(dateFormat))));
new File(screensFilePath).getParentFile().mkdirs();
```
Or use more elegant solution if any crops up

Parameters to investigate:
- drivers.folder
- chrome.capabilities.path
- ff.capabilities.path
- ie.capabilities.path
- screens.folder

**Tests:**
It would be nice to write a couple of tests for each case to make sure the solution works as expected.

**Comment by splekhanov** [comment]
After the investigation it turned out that JDI already processes paths as cross-platform using mergePath() method. There is no additional Utils needed.

Within current task it is only needed to apply mergePath() method to capabilities path.

@vsevolod-adrianov FYI

**Comment by troe88** [comment]
Demo has been done.
