### ISSUE TITLE
Describe and add tests for UI Element in documentation

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#1485]
What tests should be added:
1) Tests for all methods in UIElement class. Will be finished in #1723.
2) Tests for different initializations of UIElement:
* with @UI locator - xpath      e.g. @UI(//*[@id='user-icon']) static UIElement userIcon;
* with @UI locator - css          e.g. @UI([id=user-icon]) static UIElement userIcon;
* with template @UI locator   e.g. @UI(//*[@ui='label']//*[contains(text(),'%s')]) static UIElement userIcon;
* with smart locator                 e.g. static UIElement userIcon;
* under some context - element on some section that also has locator
3) UIElement asserts all methods in IsAssert class
4) Element not found cases
* element is invisible
* element is not in dom (wrong locator)
* can't find using smart locator
5) Different annotations for UIElement
see list of available annotations for UIElement and expected element setup in JDI_ANNOTATIONS
in InitActions class. Will be done in #1722 

Task for documentation: #1721

**Comment by romaha08** [comment]
Demo has been done
