### ISSUE TITLE
[Travis] - Ронять сборку если allure-results не удалось найти для деплоя

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1486]
Decomposition of #1306 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/43035365/70134000-3f3ca300-1698-11ea-91cf-3dc74cf9da13.png">

если тут не найдется ни один url (например не нашелся нужный нам коммит и тд) , (и таким образом никаких файлов не скачается и allure-results не будет для деплоя на нетлифай)
то нужно ронять сборку (echo "some error message"; sleep 3; exit 1; )  (поместить это в какой нить метод exitWithError "${1}")

**Comment by mf-code** [comment]
так же стоит добавить проверку и вот в этом месте если не будет найдено самих папок allure-results
<img width="723" alt="image" src="https://user-images.githubusercontent.com/43035365/70134234-b83bfa80-1698-11ea-95e3-301eacf8f15e.png">

**Comment by troe88** [comment]
Demo has been done.
