### ISSUE TITLE
[Travis] - сократить количество выхлопа в мавен

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1488]
Decomposition of #1306 

Так как по большей части информация которая нам нужна располагается в самом низу лога тревиса, то часто приходится прокручивать очень много логов мавена вниз
Поэтому в настройках travis.yml стоит добавить опции которые позволят сократить этот лог
Из того что в обычной жизни может быть нам не нужно я вижу следующее:
1 опция -ntp (доступна с версии 3.6.1 , а на тревисе сейчас 3.6.0 - так что ждем либо если есть у тревиса опция задаем ему что нам нужна не меньше чем 3.6.1). данную опцию не стоит использовать для stage == compile
2 выставить более высокий уровень логирования, например warn.  если кому то понадобится отладка по логам тревиса - он легко сможет выставить уровень на подходящий для себя в своей же ветке (не требуется каких дополнительных изменения на стороне CI софта, что в сравнении с дженкинсом удобно)

возможно предложить какие нибудь свои варианты или поискать как у тревиса можно сворачивать операции из секции stage/script

релевантный код выглядит как то так:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/43035365/70135314-e3274e00-169a-11ea-8377-1acae547ac0d.png">
(изменения необходимы для всех stage==test)

**Comment by vladb00mer** [comment]
В документации есть параметр, отвечающий за максимальный размер лога: 

Setting Maximum Log Length #
The Worker comes configured with defaultMaxLogLength = 4500000 which is 4.5MB. The setting is measured in bytes, so to get 40MB you need 40000000.

export TRAVIS_WORKER_MAX_LOG_LENGTH=40000000

**Comment by vladb00mer** [comment]
Установка уровней протоколирования достаточно гибкая: 
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org: INFO
    com.filenet.wcm.*: ERROR
    de.mycompany.*: DEBUG

**Comment by vladb00mer** [comment]
Размеры файлов лога при включении разных режимов протоколирования:
INFO - 18.3 mb
ERROR - 14.9 mb
DEBUG - 13.8 mb

файли логов в приаттаченном архиве:
[Архив.zip](https://github.com/jdi-testing/jdi-light/files/3945043/default.zip)

**Comment by vladb00mer** [comment]
Уровень протоколирования установлен WARNING
Ожидается обновление до Maven 3.6.1

**Comment by hellokitties** [comment]
set option -ntm in travis.yml
attach log example with option -ntm and without for stage test
[test_ntp_option.zip](https://github.com/jdi-testing/jdi-light/files/4085447/test_ntp_option.zip)

**Comment by pnatashap** [comment]
Опция -ntp включена при переходе на Github Actions

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
