### ISSUE TITLE
[Travis] [Minor] - начальные состояния нужны не для всех стейджей в тревисе

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1489]
Decomposition of #1306 

Что это значит: смотрим на скриншот
<img width="592" alt="image" src="https://user-images.githubusercontent.com/43035365/70135482-35686f00-169b-11ea-9bd8-e7276f70b775.png">
Не всегда нужен jq, только для stage==reports и stage==test

Посмотреть нет ли красивого способа устанавливать такие софты как jq (в нашем случае пока только jq) касательно конкретных стейджей например (по моему что то такое было в секции доки про мультиджобы)

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
