### ISSUE TITLE
[Travis] - поиск альтернатив используемым сервисам

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1492]
Decomposition of #1306 

[ЗАДАЧА ВЕРОЯТНО МОНИТОРИНГОВАЯ, поэтому если не удалось найти сейчас то возможно удастся найти потом, поэтому не закрывайте ее лучше а отписывайте и возвращайте]

С целью повышения стабильности нашей инфраструктуры, стоит подобрать альтернативные сервисы для тех что мы используем сейчас, и в случае обнаружения проблем с исходными автоматически сразу обращаться к его альтернативе (в скриптах)

Какие сервисы нуждаются в подборе с целью страховки:
1. netlify (тем более он медленно открывает отчеты, если альтернатива будет быстрее то стоит их будет поменять местами)
2. transfer.sh (фактически уже славливали когда сервис не отрабатывал)

код где transfer задействован:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/43035365/70136981-0e5f6c80-169e-11ea-964b-b105e9e355fd.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/43035365/70137028-2800b400-169e-11ea-9ca1-66edc6d97552.png">
(со временем может измениться, но суть в целом остается)

код где нетлифай:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/43035365/70137084-4070ce80-169e-11ea-9dcf-047f2850b886.png">

**Comment by AkioFaris** [comment]
An alternative to transfer.sh is covered by #1982

**Comment by mf-code** [comment]
нашли file.io  и уже подключили к проекту. теперь по переменной можно переключаться между трансфер сш и файл ио. файл ио позволяет скачать файл только один раз, но работает быстро и стабильно
