### ISSUE TITLE
[Travis] - нужен сервис allure reports for open source

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1493]
[ЗАДАЧА ВЕРОЯТНО МОНИТОРИНГОВАЯ, поэтому если не удалось найти сейчас то возможно удастся найти потом, поэтому не закрывайте ее лучше а отписывайте и возвращайте]

Проблематика:
1 мы сейчас используем костыль из связки tranfer+netlify и это накладывает свои трудности по настройке сообщения между ними и прочему
2 сделано так потому что не удалось найти какой нибудь доступный бесплатно для open source сервиса который готов был бы принимать от наших сборок аллюр результаты и предоставлять соответственно на их базе аллюр репорт

Что нужно:
1. периодически обозревать среду на обнаружение сервиса описанного выше в пункте 2
(или может быть появятся идеи как улучшить хотя бы то что у нас используется)

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
