### ISSUE TITLE
Add bootstrap element - Navs

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#1498]
Линки на эпики #15 и на #1077

В рамках данного эпика работаем только с модулем jdi-light-bootstrap.
Модуль jdi-light-bootstrap-test оставляем без изменений по возможности.

Что нужно сделать/проверить что сделано:

Column1 | - |
-- | -- |
Модуль   в котором хранить класс элемента | jdi-light-bootstrap |
Пакет в котором хранить класс элемента | complex |
Классы,   которые нужно унаследовать классу элемента | UIListBase<NavsAssert> |
Интерфейсы, которые нужно имплементить классу   элемента | без интерфейсов |
Методы   класса | - |
Поля класса |  - |
Раздел   документации, где нужно описать элемент | Bootstrap Complex elements |
Комментарии по содержанию документации |  - |
Комментарии   по содержанию документации |  - |
Примечание | удалить (или перенести в   jdi-light-bootstrap-test) все другие классы    элемента из jdi-light-bootstrap , кроме указанных в таблице |

Проапдейтить документацию.

Ссылки:
https://getbootstrap.com/docs/4.3/components/navs/
https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap

**Comment by AlexeyGirin** [comment]
Demo has been done.
