### ISSUE TITLE
Add strict check of parameters in test.properties: screenshot.strategy

### ISSUE THREAD

**Issue by splekhanov** [jdi-testing/jdi-light#1504]
In the context of #1061 decomposition

Add strict check of parameters reading from test.properties and throw an exception if some of parameters are wrong. It will make JDI more user friendly.
Parameters:
- screenshot.strategy

For given parameter you have to:

Add boundary (if applicable) and other possible validations
Cover these checks with tests (including negative) - BOOTSTRAP branch!
Describe each parameter in documentation (including the definition of valid value range)

**Comment by splekhanov** [comment]
Implemented in #1342

**Comment by AlexeyGirin** [comment]
Demo has been done.
