### ISSUE TITLE
Logs are duplicated in target\.logs\jdiEvents.log

### ISSUE THREAD

**Issue by ElenaPoduzova** [jdi-testing/jdi-light#1507]
In logs file all steps are written two times.
Example:
11:32:54 [main] STEP  JDI - Open 'Home Page'(url=https://jdi-testing.github.io/jdi-light/index.html)
11:32:54 [main] STEP  JDI - Open 'Home Page'(url=https://jdi-testing.github.io/jdi-light/index.html)
11:32:56 [main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 78.0.3904.105 (since Google Chrome 78 is installed in your machine)
11:32:56 [main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Elena_Poduzova\.m2\repository\webdriver\chromedriver\win32\78.0.3904.105\chromedriver.exe
11:33:04 [main] STEP  JDI - Run Tests
11:33:04 [main] STEP  JDI - Run Tests
11:33:04 [main] STEP  JDI - 'Home Page'(url=https://jdi-testing.github.io/jdi-light/index.html) should be opened
11:33:04 [main] STEP  JDI - 'Home Page'(url=https://jdi-testing.github.io/jdi-light/index.html) should be opened
11:33:04 [main] STEP  JDI - Check that page url(https://jdi-testing.github.io/jdi-light/index.html) contains '/index.html'
11:33:04 [main] STEP  JDI - Check that page url(https://jdi-testing.github.io/jdi-light/index.html) contains '/index.html'

**Comment by AlexeyGirin** [comment]
Demo has been done.
