### ISSUE TITLE
Wrong text in logging element.

### ISSUE THREAD

**Issue by ElenaPoduzova** [jdi-testing/jdi-light#1508]
Example in log: >>> HomePage.jdiText (css='.main-txt') 
In place of element selector should be element's text.

logger called in ActionHelper AFTER_STEP_ACTION

**Comment by Inov92** [comment]
IsAssert object returns default object value insted of prepared text message in AFTER_STEP_ACTION function

**Comment by troe88** [comment]
Demo has been done.
