### ISSUE TITLE
Implement ghost page

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#151]
Add new page in https://github.com/jdi-testing/jdi-light/tree/gh-pages
(gh-pages branch) called ghost-html-page.html
The page is a copy of https://jdi-testing.github.io/jdi-light/html5.html but all elements have "invisible" class
Change js script below to remove "invisible" class from all elements that already have this class

**Comment by PetelimovaNadezhda** [comment]
https://github.com/jdi-testing/jdi-light/pull/152
