### ISSUE TITLE
Make test example that shows how to use all elements in JDI Light - HTML5 - FileInput

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1516]
Decomposition of #1509 
At the moment we have tests that making sure that JDI Light elements implemented correctly and their methods work correctly.
For that purpose, we use external validation asserts and don't use JDI native asserts. Moreover, all test examples in the documentation use tests for JDI Light testing but not JDI Light test examples. That blowup people's minds and have to be corrected.

HTML5 Element for re-work: FileInput
1. Create test examples that use native JDI Light asserts (better to place it into dedicated test suit) and demonstrate how to use every available method
2. Update documentation - remove "old" tests examples (usually they contain assertEquals) and replace them with new ones

**Comment by troe88** [comment]
Demo has been done.
