### ISSUE TITLE
Make test example that shows how to use all elements in JDI Light - HTML5 - ComboBox

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1534]
Decomposition of #1509 
At the moment we have tests that making sure that JDI Light elements implemented correctly and their methods work correctly.
For that purpose, we use external validation asserts and don't use JDI native asserts. Moreover, all test examples in the documentation use tests for JDI Light testing but not JDI Light test examples. That blowup people's minds and have to be corrected.

HTML5 Element for re-work: ComboBox
1. Create test examples that use native JDI Light asserts (better to place it into dedicated test suit) and demonstrate how to use every available method
2. Update documentation - remove "old" tests examples (usually they contain assertEquals) and replace them with new ones

**Comment by Inov92** [comment]
This issue is blocked by #1594 
It is possible to update documentation after refactoring only.

**Comment by romaha08** [comment]
Task is closed as it's already in bootstrap branch and will be merged in master by R.Iovlev

**Comment by romaha08** [comment]
Task is closed as it's already in bootstrap branch and will be merged to master and fixed if necessary by R.Iovlev
