### ISSUE TITLE
[Travis] - Phantom Travis

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1546]
looks like we have two travis accounts in our github repo, we should to remove one (I think we should to remove org-travis , but we need to research it before)

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/43035365/70471408-268c1d00-1ade-11ea-8ed2-2fee0e7b7550.png">

**Comment by ElenaPoduzova** [comment]
extra account is travis-org, because in 2018 private repositories migrated to travis-com.
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by ElenaPoduzova** [comment]
Need to disable docs and jdi-light reps at https://travis-ci.org/organizations/jdi-testing/repositories

**Comment by ElenaPoduzova** [comment]
![image](https://user-images.githubusercontent.com/50828549/70692043-957a9900-1ccb-11ea-9969-2cf40c2ed141.png)

**Comment by troe88** [comment]
We have to realize that who is in charge of travis.

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
