### ISSUE TITLE
Merge  bootstrap in master

### ISSUE THREAD

**Issue by splekhanov** [jdi-testing/jdi-light#1551]
Perform rebase master in bootstrap branch and resolve conflicts

**Comment by splekhanov** [comment]
Merging in three steps:
1. Merge Travis CI integration part in order to run tests when build in master #1569 
2. Merge only bootstrap tests module + everything it needs to work properly. Move this to the new branch manually and create PR to master.
3. Move everything else. Can be separated to more tasks.

**Comment by RomanIovlev** [comment]
Merge done
https://github.com/jdi-testing/jdi-light/pull/1773
https://github.com/jdi-testing/jdi-light/pull/1774
