### ISSUE TITLE
[Travis] - Divide each test project in allure reports for better usability

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1562]
As we can see different projects looks inside allure reports like the same suite:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/43035365/70617532-da49f580-1c21-11ea-8d9d-54305af2dc38.png">

We need provide the different valuable names for each project to see it in the one allure report as different suites to understand how much tests were failed for each project.
list of projects is:
jdi-light-bdd-no-po-tests/
jdi-light-bdd-tests/
jdi-light-bdd/
jdi-light-bootstrap-tests/
jdi-light-bootstrap/
jdi-light-examples/
jdi-light-html-tests/
jdi-light-html/
jdi-light/
jdi-performance/

**Comment by ElenaPoduzova** [comment]
Done for 
jdi-light-examples/
jdi-light-html-tests/
jdi-performance/
jdi-applitools-tests/

**Comment by romaha08** [comment]
Need to review and finish if necessary after merge bootstrap to master

**Comment by RomE-HK** [comment]
Added right config after Bootstrap merge for module
jdi-light-bootstrap-tests/

Modules without any tests, so there is no need to create test suite for them:
jdi-light-bdd/
jdi-light-bootstrap/
jdi-light-html/
jdi-light/

Maybe later it would be necessary to add TestNG config for modules:
jdi-light-bdd-no-po-tests/
jdi-light-bdd-tests/
But now it would be redundant

**Comment by mf-code** [comment]
done
