### ISSUE TITLE
[Travis] - Fix an error: jdi-performance results will be losts

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#1563]
jdi performance project has name that different from another project names:
**jdi-performance**
although another project names looks like: **jdi-light-**somesuffix (for example jdi-light-html-tests)

in bash script for travis we use such code:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/43035365/70617961-c6eb5a00-1c22-11ea-9673-eb1b919ad945.png">
that means jdi performance project results will be missed in allure report because it's out of name pattern matching

so we have two ways:
1 rename jdi performance to the **jdi-light-**somesuffix pattern **(NEED APPROVING AT ALEXEY GIRIN)**
2 or fix bash script and use another pattern inside that script (_reports.sh_ file)

**Comment by pnatashap** [comment]
Already fixed 
`for report in $(ls -d1 jdi*/target/ ./*/jdi*/target/)`

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
