### ISSUE TITLE
Implement html.code.logging

### ISSUE THREAD

**Issue by splekhanov** [jdi-testing/jdi-light#1571]
**html.code.logging** parameter defines a strategy for writting html-code of the web element last processed before test failure to log. If it set to "on fail" value, then web element's html-code will be logged (and added to Allure report as well) when test fails, if possible.

Options: _on fail, off_

Need to implement html page attachment to Allure reports. It can be combined with screenshot attachment methods. 

Consider something like:
```
String pageSource = getHtml();
try {
    BufferedWriter writer = new BufferedWriter(new FileWriter("sourcePage.html"));
    writer.write(pageSource);
    writer.close();
} catch (IOException ex) {
    throw exception(ex, ex.getMessage());
}
```
And then attach it to Allure if html.code.logging = on fail

**Comment by troe88** [comment]
Demo has been done.
