### ISSUE TITLE
IBaseElement waitSec method doesn't wait 

### ISSUE THREAD

**Issue by NataliaTikhomirova** [jdi-testing/jdi-light#1574]
при использовании метода base().waitSec(1) метод не отрабатывает, ожидания не происходит
необходимо отладить или переписать метод
и проверить на работоспособность все задействованные тесты 

package com.epam.jdi.light.elements.base;
public IBaseElement waitSec(int sec) {
        timeout = sec;
        return this;
    }

**Comment by RomanIovlev** [comment]
as designed

**Comment by clockworkbanana** [comment]
waitSec() method actually just sets the timeout value and does not perform any wait action.
One could use waitFor() method if wait is needed.
E.g.:
> myButton.waitFor(5).text("test")
