### ISSUE TITLE
Update JDI documentation: smart locators.

### ISSUE THREAD

**Issue by marsoloGit** [jdi-testing/jdi-light#1592]
1. Change text from:
"If you have your developers following some standard way of marking UI elements
 or you have an agreement to add special attributes, you can even avoid writing locators for elements,
 thus making your page objects much more compact."
To this:
"If you have your developers following some standard way of marking UI elements
 or you have an agreement to add special attributes, you can even avoid writing locators for elements,
 thus making your page objects much more compact.
 E.g. let's say we have an agreement on naming elements and their ids in the following way:
 an element that represents buttonSubmit should have id=btn-submit, an element for userName has an id=user-name,
 and so on. 
In this case we can save time on addind UI annotation for each element (e.g. UI("#user-name") Text userName)
 and write just Text userName and allow JDI frameworks to transform the variable name from "username" to "user-name" and find an element with such id.

2. A new section should be added: How to define a smart locator.

A smart locator can be set in JDI framework via a config file named "test.properties".
There are two properties that we need: smart.locators and smart.locators.toName.

smart.locators property is a string representing locators separated by ";" (e.g. "#%s;name=%s") 
that are going to be used for searching for an element. 

smart.locators.toName property  should contain one of the following values:
 kebab-case | camelCase | snake_case | PascalCase | UPPER_SNAKE_CASE that says to JDI how to create a locator form a given variable name.

E.g.:
smart.locators = "#%s"
smart.locators.toName = UPPER_SNAKE_CASE 

public class UserCard extends Form<User> {
    TextField name;
    TextField lastName;
    TextField passportCode
    TextField passportNumber;  
    Button submitButton; 

Then JDI will be using the following locators for the elements:
name -->#NAME"
lastName --> #LAST_NAME
passportCode --> #PASSPORT_CODE, etc

3. test.properties files is processed by WebSetting.java class:

WebSettings.SMART_SEARCH - function invoked if your element has
 no locator or just setting a list of used locators.

WebSettings.SMART_SEARCH_LOCATORS - list of locators which can be used to try to find element.

WebSettings.SMART_SEARCH_NAME - function that creates locator name
 from field name (this value will be passed as a %s parameter to SMART_SEARCH_LOCATORS).

**Comment by troe88** [comment]
Demo has been done.
