### ISSUE TITLE
IsCombobox, Combobox, DataListOptions, DataList and tests. Possible refactoring

### ISSUE THREAD

**Issue by marsoloGit** [jdi-testing/jdi-light#1594]
I. Currently JDI contains in jdi-light module:
 	interface IsCombobox extends IsDropdown, IsInput
	 class Combobox extends UIListBase<UISelectAssert> implements IsCombobox
	 class DataList<T extends IListBase, D> extends ListBase<T, DataListAssert<T,D>>

in jdi-light-html module:
	class DataListOptions extends UIListBase<UISelectAssert> implements IsCombobox 

II. There are the following tests in JDI :
 IsComboboxTests.java 
 DataListTests.java
(TODO: check if there are more tests in other modules)
 
test methods within IsComboboxTests work with the element of type IsCombobox
test methods within DataListTests work with the element of type DataListOptions 

III. Questions:
1. How do methods in IsComboboxTests class work with an element of type IsCombobox if its type is an interface?
ANSWER: 
JDI has a mapping mechanism which tells to the tests
 (that are using elements of type IsCombobox) which implementation to use.

By default Combobox is used, which is described in initActions.INTERFACES
    public static MapArray<Class<?>, Class<?>> INTERFACES = map(
…
        $(IsCombobox.class, Combobox.class),
 
This default mapping can be changed by writing the following:
 
INTERFACES.update(IsCombobox.class, DataListOptions.class);

This line of code is currently added to the setUp() method of the TestsInit interface
 which is implemented by many test classes

2. Why is the name of DataListOptions  so wierd?
ANSWER: 
 It was created to work with html5 element that uses html tag
<datalist/> and has sub tags <option/>

3. Why do we need both classes Combobox and DataListOptions? They seem to do the same job,
 why not to have just one?
ANSWER: 
The idea was to show that we can work with different frameworks where comboboxes can be implemented differently.
E.g. in html5 there is no element with tag combobox,
 they have just the one named datalist(with or without options).
 It can be defined by just one locator.

In other framworks there can be an element named combobox
 and it can be properly defined only by using 3 locators,
 the same way it is done for Dropdown element with  JDropdown annotation.
The way of working with such element differs from the way of working with datalist

IV. Issues:
 - Multiple classes with similar names make JDI framework look 
complicated and becomes difficult to understand
 - Documentation for html elements that discribe DataList and Combobox elements 
provides absolutely the same information which can confuse a user
 - classes are located in different modules, DataListOptions doesn't even extend DataList,
 no clear dependency of one class on another. 
 - Name DataListOptions is confusing, it is better if it is called at least like ComboboxHtml
 - Combobox class is not fully implemented, in case if we decide to use it instead of DataListOptions then the tests will fail as we don't even have a proper combobox
 element on the JDI test page. It doesn't look good when a default implementation doesn't work.
- the code for mapping IsCombobox interface with its implementations differ for master and bootstrap branches.
We need THE ONE FROM MASTER, the one from bootstrap is too old.
 
V. What was decided regarding the above:
	- move related classes(not tests) to jdi-light module
	- change classes names and probably refactor the code so that it is written the same way as it is done for Dropdown class:
https://github.com/jdi-testing/jdi-light/tree/master/jdi-light/src/main/java/com/epam/jdi/light/elements/complex/dropdown
 so that to have classes: Combobox, ComboboxSelect(which is now DataListOptions)
 and ComboboxExpand in the folder named "combobox"
	- for elements of type ComboboxExpand to use JDropdown annotation
	- implement methods for ComboboxExpand and create tests for this class (see how it is done for DropDownExpand) 
	- rewrite documentation so that it refects the above changes

**Comment by romaha08** [comment]
As R.Ivovlev said - not needed task.
