### ISSUE TITLE
Implement Vue elements

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#16]
Implement [Vue typical elements](https://vuetifyjs.com/en/components/forms) like [html elements](https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html)

**Comment by AlexeyGirin** [comment]
Create list of elements for implementation

**Comment by ksenia-vyushkova** [comment]
Component available (https://vuetifyjs.com/en/components/api-explorer):

Alerts
Autocompletes
Avatars
Badges
BottomNavigation
BottomSheets
Breadcrumbs
ButtonGroups
Buttons
Calendars
Cards
Carousels
Categories
Chips
Combobox
DataIterator
DataTables
DatePickers
Dialogs
Dividers
ExpansionPanels
FloatingActionButtons
Footer
Forms
Hover
Icons
Images
Inputs
ItemGroups
Jumbotrons
Lists
Menus
NavigationDrawers
OverflowBtns
Paginations
Parallax
Progress
Ratings
SelectionControls
Selects
Sheets
Sliders
Snackbars
Sparklines
Steppers
Subheaders
Tabs
TextFields
Textarea
TimePickers
Timelines
Toolbars
Tooltips
Treeview
Windows

**Comment by ksenia-vyushkova** [comment]
Suggested to implement:
Buttons
DataTables
Icons
Images
Combobox
Forms
Lists
Menus
SelectionControls
Selects
TextFields
Textarea

**Comment by AlexeyGirin** [comment]
Done.
