### ISSUE TITLE
Made methods setText and input for TextField correct work with character "\"

### ISSUE THREAD

**Issue by hellokitties** [jdi-testing/jdi-light#1607]
When we use methods input(String value) or setText(String value) for TextField element - this methods don't  enter character "\\" in field.

If we preliminarily transform value in such way - value.replace("\\\\","\\\\\\\\") - this methods will process value corretly.

So, need to fix methods input(String value) and setText(String value) for correct work with character "\\"

**Comment by splekhanov** [comment]
Demo has been done
