### ISSUE TITLE
В классе BaseTable при проверке количества колонок сравниваются строки вместо колонок.

### ISSUE THREAD

**Issue by Drenjy** [jdi-testing/jdi-light#1620]
Кажется здесь затисалась ошибка. Сверяется количество колонок с количеством строк.
 
`  private void validateColumnIndex(int colNum) {
        if (colNum < 1) {
            throw Exceptions.exception("Columns numeration starts from 1 (but requested index is %s)", new Object[]{colNum});
        } else if (colNum > (Integer)this.count.get()) {
            throw Exceptions.exception("Table has %s columns (but requested index is %s)", new Object[]{this.size.get(), colNum});
        }
    }`

**Comment by romaha08** [comment]
Task is closed as it's already in bootstrap branch and will be merged to master and fixed if necessary by R.Iovlev
