### ISSUE TITLE
[JDI] - Working with Java 11, 12, 13

### ISSUE THREAD

**Issue by alekseygalkin** [jdi-testing/jdi-light#1655]

**Comment by romaha08** [comment]
We need to check that all tests in JDI-Light are working with Java next versions:
- Java 11
- Java 12
- Java 13

**Comment by DmitrievAlexander** [comment]
The only problem I found is incompatibility of allure maven library 2.9 with JDK9 and higher due to missing javax/xml/bind library in JDK, this issue can be solve by using latest available allure maven version(2.10.0)

**Comment by DmitrievAlexander** [comment]
#631

**Comment by romaha08** [comment]
Demo has been done
