### ISSUE TITLE
Integrate with Applitools

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#166]
https://applitools.com/tutorials/selenium-java.html#quick-start-%F0%9F%9A%80
Add JDI Light package with Aplitools functionality on each action
Add property to switch on and off Applitools eyes

**Comment by AlexeyGirin** [comment]
Not actual any more, @RomanIovlev did it in its own way

**Comment by AlexeyGirin** [comment]
Roman did it in its own way

**Comment by RomanIovlev** [comment]
Already implemented in https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-eyes
