### ISSUE TITLE
Create dummy test for Android device an run it  on emulator locally

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1662]
Create dummy test for Android device an run it  on emulator locally

1. Provide ability to  run tests on at least one of Android emulators via appium
2. Provide the ability to switch back to selenium and run jdi-light examples (test) via selenium

**Comment by Nikolai812** [comment]
Pull Request #1706 (by Zaur) implements the necessary functionality which was expected by the task

**Comment by Nikolai812** [comment]
Pull request merged, closing the task
