### ISSUE TITLE
List mobile-specific actions needed to be covered by tests

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1668]
1. List mobile-specific actions needed to be covered by tests
2. Create dedicated issue for each and link it to that issue

**Comment by MazurK239** [comment]
The complete list of the mobile driver features can be found in the attached document
[Mobile driver features.docx](https://github.com/jdi-testing/jdi-light/files/4312211/Mobile.driver.features.docx)
