### ISSUE TITLE
Check and fix tests in "jdi-light-examples" module

### ISSUE THREAD

**Issue by romaha08** [jdi-testing/jdi-light#1674]

**Comment by sergeisolarev** [comment]
Failed tests:
1) io.github.epam.tests.google.WaitDataListTests#sizeGreaterTest
2) io.github.epam.tests.google.WaitDataListTests#sizeTest
3) io.github.epam.tests.google.WaitJListTests#sizeNotEmptyTest
4) io.github.epam.tests.google.WaitJListTests#sizeTest
5) io.github.epam.tests.google.ElementsGoogleTests#validateEntities2Tests
6) io.github.epam.tests.google.ElementsGoogleTests#validateFilterTests
7) io.github.epam.tests.google.SearchTests#printResultListTest
8) io.github.epam.tests.google.SearchTests#printResultWaitTest

**Comment by sergeisolarev** [comment]
The following tests have problem with "is" function (pause before refresh is required)
1) io.github.epam.tests.google.WaitDataListTests#sizeGreaterTest
2) io.github.epam.tests.google.WaitDataListTests#sizeTest

**Comment by sergeisolarev** [comment]
9) io.github.epam.tests.recommended.TableTests#jTablePerformanceTest has low performance

**Comment by sergeisolarev** [comment]
Pull Request #1685

**Comment by romaha08** [comment]
Demo has been done
