### ISSUE TITLE
Check and fix tests in "visual-chalange" module

### ISSUE THREAD

**Issue by romaha08** [jdi-testing/jdi-light#1678]

**Comment by sergeisolarev** [comment]
Fix 3 tests and teardown, 1 test removed. Branch "#1678"

**Comment by sergeisolarev** [comment]
Can't merge while resolved conflict with latest TESTNG (7.1). org.testng.IInvokedMethodListener2 used by allure-testng was deprecated in TestNG 7.1.
Ling to Alure bug: https://github.com/allure-framework/allure-java/issues/415
