### ISSUE TITLE
Correct Multiple inputs element 

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#1684]
Refactor Multiple inputs tests and element in bootstrap branch
https://github.com/jdi-testing/jdi-light/blob/bootstrap/jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/complex/MultipleInputsTests.java
in separate branch
Recommendations:

1. Remove MultipleInputs element
2. In the Page Objects add few examples of how to create sections for such elements. Add tests for that demonstrates work with such kind of elements
3. No need to add base validation because of no new element needed
4. Try to reduce the number of tests in order to demonstrate main functionality and not overflow user with useless tests

**Comment by AlexeyGirin** [comment]
Done by Roman
