### ISSUE TITLE
Send text with $ symbol does not work

### ISSUE THREAD

**Issue by bes422** [jdi-testing/jdi-light#169]
<artifactId>jdi-light</artifactId> 
<version>1.0.63</version>

Need to escape "$" -> "\\$" in following method: 
com.epam.jdi.tools.StringUtils#msgFormat(java.lang.String, java.util.List<java.lang.Object>)
|
com.epam.jdi.light.actions.ActionHelper#fillTemplate
if second parameter of the msgFormat contains "$" then bold line will throw "Illegal group reference": 
```
 public static String msgFormat(String template, List<Object> args) {
        String result = template;
        for (int i=0;i<args.size();i++)
            if (template.contains("{"+i+"}"))
                **result = result.replaceAll("\\{"+i+"}", args.get(i).toString());**
        return result;
    }
```

**Comment by yanusa3** [comment]
firstName.input("something$") lead to 
java.lang.RuntimeException: 
[27:38.236] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Surround method issue: Can't get action name: Can't fill JDIAction template: Submit '{name}' with {0}for method: submit

**Comment by RomanIovlev** [comment]
validate and fix TextFieldTests.inputSymbolsTest()
