### ISSUE TITLE
Fix usage of Selenium locator FindBy with how and using 

### ISSUE THREAD

**Issue by ksenia-vyushkova** [jdi-testing/jdi-light#172]
Seems that usage of Selenium locator <span>@</span>FindBy with how() and using() parameters is not working correctly.

Steps to reproduce:
1) Add the following to the site class:
```java
@FindBy(how= How.CLASS_NAME, using = "profile-photo")
public static WebElement element1;

@FindBy(className = "profile-photo")
public static WebElement element2;
```
2) In the some <span>@</span>Test try to click on the element.

Actual result: element2 is working correctly, however element1 can not be clicked. (Exception "Can't find Element 'StaticSite.element1 ()' during 10 seconds")

Expected result: both these elements should be clickable.

**Comment by troe88** [comment]
Demo has been done.
