### ISSUE TITLE
Add tests that doesn't exist for UIElement class

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#1723]
Including element is invisible.
Create required UI html elements on test page.
Create defects if something in UIElement class doesn't work and need investigation.
Add also left tests for asserts and annotations(Frame; getVisible, getVisibleEnabled, getShowInView tests with not visible and etc. elements; noCache, SName). Tests are in the same UIElementTests.java file.
Most part of the work for UIElement tests was done in #1485.

**Comment by pnatashap** [comment]
Not needed
