### ISSUE TITLE
Research JDI must attach screenshots in allure. If not - fix it.

### ISSUE THREAD

**Issue by romaha08** [jdi-testing/jdi-light#1731]

**Comment by DmitrievAlexander** [comment]
`Allure.addAttachment("Page screenshot", new ByteArrayInputStream(Files.readAllBytes(Paths.get(screenName)))); in AllureLoggerHelper class` is responsible for screenshot creation and attachment.
Screenshot is created according to specified folder but still not attached to allure report, found possible existing issue in allure itself https://github.com/allure-framework/allure-java/issues/419.
It is still possible to solve this issue for each JDI sub-module separately by adding custom listener.
JUNIT:
`    @After
    public void takesScreenshot(Scenario scenario) {
        if (scenario.isFailed()) try {
            byte[] screenshot = ((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.BYTES);
            scenario.embed(screenshot, "image/png");
        } catch (ClassCastException cce) {
            cce.printStackTrace();
        }
    }`
TestNG:
`
    @Override
    public void onTestFailure(ITestResult result) {
        makeScreenshot();
        log.info("Test FAILED: " + result.getName());
    }
    @Attachment(value = "Page screenshot", type = "image/png")
    private void makeScreenshot() {
        ((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.BYTES);
    }`

**Comment by pnatashap** [comment]
Attached in case of failure in elements asserts
