### ISSUE TITLE
Fix test in module HTML Tests

### ISSUE THREAD

**Issue by romaha08** [jdi-testing/jdi-light#1737]
The following tests are failed in html tests module:

    io.github.epam.html.tests.elements.common.PerformanceTests.displayButtonTest(PerformanceTests.java:84)
    io.github.epam.html.tests.elements.common.ButtonTests.isNotAppearButtonTest(ButtonTests.java:151)
    io.github.epam.html.tests.elements.common.ButtonTests.lambda$isNotAppearFailedButtonTest$4(ButtonTests.java:140)
    io.github.epam.html.tests.elements.complex.table.DataSimpleTableTests.valueTest(DataSimpleTableTests.java:53)
    io.github.epam.html.tests.elements.common.PerformanceTests.vanishButtonUITest(PerformanceTests.java:160)
    io.github.epam.html.tests.elements.common.PerformanceTests.vanishHiddenButtonTest(PerformanceTests.java:67)
    io.github.epam.html.tests.elements.common.PerformanceTests.vanishHiddenButtonUITest(PerformanceTests.java:171)
    io.github.epam.html.tests.elements.common.PerformanceTests.vanishRemoveButtonUITest(PerformanceTests.java:165)

**Comment by sergeisolarev** [comment]
Tests (time to time) doesn't work in FireFox browser only

**Comment by sergeisolarev** [comment]
The following 4 tests still failed in FireFox:

io.github.epam.html.tests.elements.common.PerformanceTests: suspendButtonTest ; io.github.epam.html.tests.elements.common.PerformanceTests: suspendButtonUITest ; io.github.epam.html.tests.elements.common.PerformanceTests: vanishButtonTest
io.github.epam.html.tests.elements.complex.table.DataSimpleTableTests: valueTest

**Comment by sergeisolarev** [comment]
io.github.epam.html.tests.elements.common.PerformanceTests.displayButtonTest(PerformanceTests.java:84)
io.github.epam.html.tests.elements.common.ButtonTests.isNotAppearButtonTest(ButtonTests.java:151)
io.github.epam.html.tests.elements.common.ButtonTests.lambda$isNotAppearFailedButtonTest$4(ButtonTests.java:140)
io.github.epam.html.tests.elements.complex.table.DataSimpleTableTests.valueTest(DataSimpleTableTests.java:53)
io.github.epam.html.tests.elements.common.PerformanceTests.vanishButtonUITest(PerformanceTests.java:160)
io.github.epam.html.tests.elements.common.PerformanceTests.vanishHiddenButtonTest(PerformanceTests.java:67)
io.github.epam.html.tests.elements.common.PerformanceTests.vanishHiddenButtonUITest(PerformanceTests.java:171)
io.github.epam.html.tests.elements.common.PerformanceTests.vanishRemoveButtonUITest(PerformanceTests.java:165)

**Comment by romaha08** [comment]
@RomanIovlev please review. Test doesn't work in FireFox. Looks like it's issue of geckoDriver - not if JDI

**Comment by RomanIovlev** [comment]
Looks like ) let's postpone for now

**Comment by romaha08** [comment]
Demo has been done.
