### ISSUE TITLE
Cover new parameters w/tests

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1744]
#screenshot.strategy=off | on fail | on assert | new page - прикладывает скриншот
#html.code.strategy=off | on fail | on assert | new page - html code страницы
#requests.strategy=off | on fail | on assert | new page - запросы 4ХХ, 5ХХ ошибки в консоль логе
#allure.steps=true - включены или нет степы для Алюр

Contact w/ @RomanIovlev for details

**Comment by kasdar23** [comment]
Required changes will be done in #1878 and #1879, like in story #1760
