### ISSUE TITLE
Please consider adding bdd and bdd -no-po tests to travis ci.

### ISSUE THREAD

**Issue by 886-59-936** [jdi-testing/jdi-light#1749]
Please consider adding bdd and bdd -no-po tests to travis ci.
This will increase coverage since test do not 100% match to other (not bdd) test.

**Comment by AkioFaris** [comment]
BDD tests are already added, no-po tests - not yet. Also this module need to be fixed. "mvn test" currenlty fails with "Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jdi-bdd-no-po-tests: There are test failures."

**Comment by pnatashap** [comment]
travis is no longer used
