### ISSUE TITLE
Update template repositories

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#1757]
Use jdi-light-testng-template as a reference and actualize tests and settings in jdi-light-junit-template
Add gradle settings to both examples
Check that tests work on latest versionon of Jdi lights from mvn clean install and from right click in IDE

**Comment by vitaly-dukhov** [comment]
jUnit template was actualized

**Comment by RomanIovlev** [comment]
Create new issue for Gradle https://github.com/jdi-testing/jdi-light/issues/1819
