### ISSUE TITLE
Implement the mobile-specific find methods

### ISSUE THREAD

**Issue by MazurK239** [jdi-testing/jdi-light#1766]
This is a part of #1668

All mobile-specific methods of element search (new types of locators, maybe overriding of some existing ones) need to be implemented within this task.

The complete list of the mobile driver features can be found in the attached document
Mobile driver features.docx

**Comment by ArKhmeln** [comment]
The following steps were taken for this task in jdi-light-mobile module:
- Created annotations for mobile find opportunities
- Added init rules for these annotations in PageFactory
- Implemented web and partially native selector strategies

There are native selectors which are yet to be checked:
- Image
- AndroidViewTag
- AndroidDataMatcher
These selectors were added to annotations util just like the others but not tested. (com.epam.jdi.light.mobile.elements.pageobjects.annotations;)

IOS selectors need to be implemented as well.
Mechanism of choosing proper selectors (web or native) for MobileFindBy annotition can be improved if necessary.
