### ISSUE TITLE
Create test page for Angular elements

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1777]
Create test page for Angular elements in the same manner as it is done for Bootstrap.
Put it here: https://github.com/jdi-testing/jdi-light/blob/gh-pages/angular.html 
Create additional left side menu item under "Elements pack" on the page https://jdi-testing.github.io/jdi-light/index.html - name it Angular
Point it to new page - https://jdi-testing.github.io/jdi-light/angular.html

Reference to the Epic - #1778

**Comment by mf-code** [comment]
done
