### ISSUE TITLE
Angular element test page creation: Buttons & Indicators - Chips

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1802]
Reference to Angular Epic issue - #1778
Reference to Test Page Creation task - #1777 

1. Implement static test html page with target control using Angular framework
2. See element code at https://material.angular.io/components/chips
3. Put Angular elements here: https://github.com/jdi-testing/jdi-light/blob/gh-pages/angular.html (in the same manner as it is done for HTML5 elements)
4. Check your changes at https://jdi-testing.github.io/jdi-light/angular.html
5. Branch for commits: https://github.com/jdi-testing/jdi-light/tree/gh-pages
6. If element is actionable - make the result of its work visible
7. Create documentation article for target element in the Angular section in the same manner as it is done for BootStrap elements (but w/out methods and etc - simply element description + element screenshot + element code screenshot) here: https://jdi-docs.github.io/jdi-light/#angular-common-elements

**Comment by AkioFaris** [comment]
[1st out of 2 PRs for this issue](https://github.com/jdi-testing/test-site/pull/1) (in the angular test-site project)

**Comment by AlexeyGirin** [comment]
Demo has been done.
