### ISSUE TITLE
Add Gradle in JUnit and TestNG template

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#1819]
Need to add gradle file and be sure that tests passed in
https://github.com/jdi-templates/jdi-light-junit-template
and 
https://github.com/jdi-templates/jdi-light-testng-template

Created from https://github.com/jdi-testing/jdi-light/issues/1757
For more details ask @vitaly-dukhov

**Comment by fedorsnigir** [comment]
https://github.com/jdi-templates/jdi-light-testng-template/pull/3
https://github.com/jdi-templates/jdi-light-junit-template/pull/2

**Comment by pnatashap** [comment]
Templates are updated
