### ISSUE TITLE
Implement Cucumber Steps for Button element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#185]
This is #23 decomposition, see it for details.

1. Implement steps for Button element
2. Cover it this tests using https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html as reference
3. Add Documentation to Cucumber Steps Library
4. Add reference to Cucumber Steps Library doc to HTML elements documentation

**Comment by AlexandraKozhevnikova** [comment]
Link for 1. [https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd/src/main/java/com/epam/jdi/bdd/stepdefs/ButtonSteps.java](url)

**Comment by AlexeyGirin** [comment]
Делаем тесты только на осмысленные шаги

**Comment by AlexeyGirin** [comment]
Demo has been done.
