### ISSUE TITLE
Refactor driver settings to minimize usage of static methods

### ISSUE THREAD

**Issue by rralys** [jdi-testing/jdi-light#1882]
The class DriverSettings within the com.epam.jdi.light.settings package should be refactored to
1. Avoid static methods as much as possible;
2. To minimize refactorig of other classes so that the DriverSettings class can be continued using with minimal changes in other code pieces.

**Comment by AkioFaris** [comment]
Postponed due to the lower priority for the moment. 
Last result here: https://github.com/jdi-testing/jdi-light/pull/1969 There are compilation errors, further investigation required.

**Comment by pnatashap** [comment]
All settings can be set up via *.properties files
