### ISSUE TITLE
Investigation: Verify the same code works on both platforms (ios and android)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#1883]
Add support for native control (let it be a button) and write a simple script with it.
Verify that it is possible to use the same script on both platforms - ios and android

**Comment by BraveLittleTapok** [comment]
Tests running on ios and android in follow packages: 
jdi-light:
- jdi-light-mobile-angular-web-tests
- jdi-light-mobile-bootstrap-web-tests
- jdi-light-mobile-html-web-tests
Instructions how to run tests are in REDME file in corresponding package
