### ISSUE TITLE
Add locator annotations

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#1892]
Mark all locators in JDI in one way

**Comment by jreznot** [comment]
It would be great to have either `@Language` annotation from JetBrains annotations `org.jetbrains:annotations:19.0.0` in case it is one of concrete languages: `CSS`/`XPath` or your custom annotation in method arguments that receive locators.

Example with your custom annotation:
```
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
public @interface Locator {
}
```

Usage in the framework:
```
public static WebList $$(@Locator String locator, Object parent) {
    return list(locator).setup(j->j.setParent(parent));
}
```

**Comment by RomanIovlev** [comment]
Developed in #1893
