### ISSUE TITLE
Investigation: problems with Section and Dropdown

### ISSUE THREAD

**Issue by alla-blinkova** [jdi-testing/jdi-light#1895]
1. Check behavior of click() for Section
2. Check behavior of expanded() for Dropdown

**Comment by alla-blinkova** [comment]
1. There is no click() method for Section, core().click() can be used instead. core().click() was checked for navbar Section and works correctly, test will be added later.
2. Dropdown and DropdownMenu (for bootstrap) were checked, isExpanded() method should be used instead of is().expanded(). Behavior of isExpanded() was checked for both classes, tests already exist and pass.

**Comment by RomanIovlev** [comment]
Fixed in 1.2.5
