### ISSUE TITLE
Add tests for jdi-light simple elements

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#19]
Add "unit-like" tests for each method of jdi-light elements marked with @JDIAction annotation
[UIElement](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/elements/base/UIElement.java)

**Comment by epam-ocherniavskaia** [comment]
Я правильно понимаю что теперь есть только UIElement и используя его надо проверять методы каждого из интерфейсов пакета com.epam.jdi.light.ui.html.common? Те также как раньше ButtonTests, но уже обращаясь к UIElement?

**Comment by RomanIovlev** [comment]
Нет обращаться надо в Button, TextField и т.д.
