### ISSUE TITLE
Implement tests on Angular elements

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1932]
Implement tests on Angular elements in **jdi-light-angular-tests** module the same way as jdi-light-bootstrap-tests. 
Add elements ids to the Angular page elements according to [the instruction](https://github.com/jdi-testing/test-site/wiki/Angular-setup-and-build-process)

**(!) If it makes sense to add some additional angular elements (buttons etc) or to change current element configuration (for example, add vanishing for a progress bar after some time) to make tests more plausible, please don't hesitate to do so.**

See the [Manual for Newcomers](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7BC686404C-FEE4-4E21-8438-183DE456AAF5%7D&file=Manual%20for%20Newcomers.docx&action=default&mobileredirect=true&cid=4baf434d-49d3-497b-9fbf-e8fd5dcb95e7) for additional test requirements. 
Group tests by packages according to [Angular elements categories](https://material.angular.io/components/categories)

**Comment by AlexeyGirin** [comment]
Done
