### ISSUE TITLE
Angular tests: Implement Radio buttons tests

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1934]
Reference to the Epic - #1932

All steps are described in [the Angular tests guide](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7BE3A93BE7-D0FF-45FD-B3D2-804A31B2482C%7D&file=Angular_tests_guide.docx&action=default&mobileredirect=true).

**Comment by TamMinh87** [comment]
tests already implemented in branch angular-tests-only

**Comment by AkioFaris** [comment]
Despite the fact that some tests are already implemented, this task needs to be finished:
1. RadioButtonTests class should consist of JDI asserts only.
2.  All elements for radio buttons tests should be moved from AngularPage to a new RadioButtonsSection, and this section should be added to the AngularPage.
3. Proper ids should be added to all elements involed in radio buttons tests on Alugar page.
4. More tests on radio buttons should be implemented.
5. Documentation should be added.

**Comment by ElenaBokova** [comment]
https://github.com/jdi-testing/jdi-light/pull/2169

**Comment by ElenaBokova** [comment]
https://github.com/jdi-docs/jdi-light/pull/1004
