### ISSUE TITLE
Angular tests: Implement Input tests

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1944]
Reference to the Epic - #1932

1. Link to the given element: https://material.angular.io/components/input/overview
2. Implement given angular element (if element has some variation - please parametrize) and put it here: https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap
3. Use HTML elements as a reference example
4. Create page object for a given element, and cover with tests all element methods, put tests to here: https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap-tests
5. Update documentation (add methods and examples, add links to test - in the same manner as it is done for HTML elements)
6. Add JavaDocs for a given element
7. Add link to angular element to angular documentation, put it above class implementation (see https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html/elements/common/Button.java as an example)
8. Move given element article to proper section (common, complex or composite) depending on the implementation

**Comment by dhoanglong91epam** [comment]
I am working on this ticket
