### ISSUE TITLE
Angular tests: Implement Form Field tests 

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1947]
Reference to the Epic - #1932

All steps are described in [the Angular tests guide](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7BE3A93BE7-D0FF-45FD-B3D2-804A31B2482C%7D&file=Angular_tests_guide.docx&action=default&mobileredirect=true).

**Comment by rralys** [comment]
https://github.com/jdi-testing/jdi-light/pull/2353 -- PR with the tests

https://github.com/jdi-docs/jdi-light/pull/1034 -- PR with the documentation.
