### ISSUE TITLE
Angular tests: Implement Grid List, List tests

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1953]
Reference to the Epic - #1932

All steps are described in [the Angular tests guide](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7BE3A93BE7-D0FF-45FD-B3D2-804A31B2482C%7D&file=Angular_tests_guide.docx&action=default&mobileredirect=true).

A tip: use _com.epam.jdi.light.elements.complex.JList_ element

**Comment by Vikew243** [comment]
link to the PR with tests: https://github.com/jdi-testing/jdi-light/pull/2174
link to the PR with documentation: https://github.com/jdi-docs/jdi-light/pull/1002
