### ISSUE TITLE
Angular tests: Implement Snackbar tests

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#1965]
Reference to the Epic - #1932

All steps are described in [the Angular tests guide](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/_layouts/15/Doc.aspx?sourcedoc=%7BE3A93BE7-D0FF-45FD-B3D2-804A31B2482C%7D&file=Angular_tests_guide.docx&action=default&mobileredirect=true).

A tip: use _com.epam.jdi.light.elements.composite.Section_ to describe Snackbar

**Comment by AlexeyGirin** [comment]
Оказалась сложной для студентов, поэтому возвращаем обратно в бэклог
