### ISSUE TITLE
Repeat test annotation

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#1999]
As user I will able to setup unstable tests to re-run if test failed.
Example:
@RepeatCount(5)
@Test
public void unstableTest() {
    ...
}

If First test run is failed but second is passed then test is passed in report.

**Comment by RomanIovlev** [comment]
You can do this using TestNG retry https://www.toolsqa.com/selenium-webdriver/retry-failed-tests-testng/
Or see an example in jdi-light-html-tests / ... /RetryTest
