### ISSUE TITLE
Add tests for jdi-light composite elements

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#20]
Add "unit-like" tests for each method of jdi-light elements marked with @JDIAction annotation
[Forms](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/elements/composite/Form.java)
[WebPages](https://github.com/jdi-testing/jdi-light/blob/master/jdi-light/src/main/java/com/epam/jdi/light/elements/composite/WebPage.java)

**Comment by AlexeyGirin** [comment]
Decomposed to #130 #131 #132
