### ISSUE TITLE
Remote driver and local driver configuration at once

### ISSUE THREAD

**Issue by troe88** [jdi-testing/jdi-light#2005]
As a JDI-Light user I wish:
1. to store local and remote driver setting in the test.properties at the same time;
2. to switch over local or remote browser by one "flag" property;
3. to have an example that shows remote&local driver configuration
4. to have an up-to-date documentation that describes remote&local driver configuration

_Example_1_:
```
driver=chrome
driver.remote.url=http://...:4444/wd/hub
...
driver.type=local
```
In this case, JDI shoud use local chrome driver regardless the fact that **driver.remote.url** has specified.
_Example_2_:
```
driver=chrome
driver.remote.url=http://...:4444/wd/hub
...
driver.type=remote
```
In this case, JDI shoud use remote chrome driver.

Contact dmitry_lebedev1@epam.com for more details, if needed.

**Comment by clockworkbanana** [comment]
Done.

Now one can add driver.type property to test.properties file.
> driver.type=local

If specified driver.type is 'local', jdi would try to use local WebDriver even if remote.url is specified.

PR:
https://github.com/jdi-testing/jdi-light/pull/2101

Documentation update:
https://github.com/jdi-docs/jdi-light/pull/971
