### ISSUE TITLE
Make sure JDI Light works with JDK up to version 11

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2016]
Make sure that JDI Light works w/java11.
Please investigate the problem found by @Sudalius in task #1776 (see comments)

Here is some update from @mf-code:
у нас проблемы с кодом light на jdk 11 из за JDIAction
(на мастере, не на мастере проблемы нет, разницу еще не искала)
Screen Shot 2020-04-09 at 4.07.59 PM.png
вот как это воспроизвести
из за того что в WebPage2 есть метод с JDIAction то все строчки кода которые используют JAction1, JFunc1 или Consumer (пример сделан с Consumer чтобы исключить проблемы с JAction1  который делает тоже самое), падают на jdk 11.0.5 с ошибкой ClassNotFound
Screen Shot 2020-04-09 at 4.13.24 PM.png
если переписать падающую строчку как на скриншоте - то не упадет. но есть и другие места (в енумах например) где такой финт не сработает так как там используются иные конструкции
может есть какие нибудь мысли почему JDIAction такой странный?
ClassNotFoundException comes while trying to load a class at run-time only and the name was provided during runtime, not at compile-time
если я меняю на @Retention(RetentionPolicy.SOURCE)
(вместо рантайм - тоже начинает работать)
вот так выглядит ошибка здесь больше деталей

**Comment by AkioFaris** [comment]
Closing since https://github.com/jdi-testing/jdi-light/issues/2072 task covers this one
