### ISSUE TITLE
Merge master into angular

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2039]

**Comment by rralisEPAM** [comment]
As far as I can see, the master and angular branches are identical at the moment.

![image](https://user-images.githubusercontent.com/30503686/83115029-71244480-a0d2-11ea-986c-8fabe2641716.png)

The task can be closed without the need to further progress it.

**Comment by rralys** [comment]
As far as I can see, the master and angular branches are identical at the moment.

![image](https://user-images.githubusercontent.com/14198577/83115482-15a68680-a0d3-11ea-9b65-3bc5b5081589.png)

The task can be closed without the need to further progress it.
