### ISSUE TITLE
[Travis] Add health checks for JDI Light Temlates

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2060]
Please add some cron checks for our Templates that make sure our templates are actual and work

**Comment by ViktarR** [comment]
.travis.yml health check added for repositories:
https://github.com/jdi-templates/jdi-light-testng-template                pass
https://github.com/jdi-templates/jdi-light-bdd-template                    pass
https://github.com/jdi-templates/jdi-light-selenoid-template             failed
https://github.com/jdi-templates/jdi-light-saucelabs-template           failed
https://github.com/jdi-templates/jdi-light-junit-template                   failed

**Comment by ViktarR** [comment]
travis.yml is not added for https://github.com/jdi-templates/jdi-light-csharp-template repository
