### ISSUE TITLE
jdi-light-testng-template project not compiling

### ISSUE THREAD

**Issue by Inov92** [jdi-testing/jdi-light#2062]
Steps to reproduce

1. Go to https://jdi-docs.github.io/jdi-light/#1-quick-start
2. Follow template project link in the paragraph: https://github.com/jdi-templates/jdi-light-testng-template
3. Clone the project and perform mvn clean install

Expected: Tests are compiled and successfully passed
Actual: Error:(21,31) java: cannot find symbol in the org.mytests.uiobjects.example.site.custom.MultiDropdown

**Comment by AkioFaris** [comment]
A tip: https://github.com/jdi-testing/jdi-light/tree/master/test-templates compiles and probably is the newer template version. Compare these templates, possibly it'd make sense to update jdi-light-testng-template according to the jdi-light master's jdi-light-testng-template.

**Comment by ViktarR** [comment]
https://github.com/jdi-templates/jdi-light-testng-template/tree/2062_jdi_light_test_template_not_compiling
