### ISSUE TITLE
Test JDI Plugin with IntelliJ IDEA Ultimate 2020.2 

### ISSUE THREAD

**Issue by clockworkbanana** [jdi-testing/jdi-light#2070]
**Background**
We need to verify JDI plugin with latest version of IntelliJ Idea

**Goal**
Issues are to be reported here:
> https://youtrack.jetbrains.com/issues/IDEA
> Subsystem: Frameworks. Selenium

**Comment by gbuh** [comment]
Checked. In my opinion, no issues.
