### ISSUE TITLE
Investigate and fix angular tests failures for jdk 11, 12, 13

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2072]
- In the PR against different JDK versions https://github.com/jdi-testing/jdi-light/pull/2065 in the comment section there are allure reports for different JDKs. (see comments for 5565 build)
- https://github.com/jdi-testing/jdi-light/runs/743181288 here is a corresponding Travis build, that contains hepful logs. 
Investigate why angular tests did not pass for jdk 11, 12, 13 and fix the issue.

**Comment by pnatashap** [comment]
Package is not published, will be checked after fixes and before publishing
