### ISSUE TITLE
SauceLabs integration - Documentation

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2081]
Add an article to the documentation regarding JDI and Sauce Labs
Don't forget to mention the project template demonstrates it: https://github.com/jdi-templates/jdi-light-saucelabs

Make sure all info from https://github.com/jdi-templates/jdi-light-saucelabs/blob/master/README.md moved to the documentation

**Comment by gbuh** [comment]
See PR: https://github.com/jdi-templates/jdi-light-saucelabs/pull/2
and https://github.com/jdi-docs/jdi-light/pull/972
