### ISSUE TITLE
[Travis] Add notifications to MS Teams for jdi-light, jdi-light templates cronjobs

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2091]

**Comment by ViktarR** [comment]
jdi-templates cronjobs notification stored [here](https://teams.microsoft.com/l/channel/19%3a4acb49d4c5c84c5680c8a3d2e15d2eb8%40thread.skype/jdi-templates?groupId=ac8f242a-5a99-4fab-a4d7-799de8968df5&tenantId=b41b72d0-4e9f-4c26-8a69-f949f367c91d)

jdi-light cronjobs notification stored [here](https://teams.microsoft.com/l/channel/19%3aa7fa20ba65de4d8aa8f901e7a1c2853b%40thread.skype/jdi-light?groupId=ac8f242a-5a99-4fab-a4d7-799de8968df5&tenantId=b41b72d0-4e9f-4c26-8a69-f949f367c91d)

pull request link : https://github.com/jdi-testing/jdi-light/pull/2096
