### ISSUE TITLE
Fix JDI-Light JUnit template

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2099]
https://github.com/jdi-templates/jdi-light-junit-template build failed, fix it

**Comment by clockworkbanana** [comment]
Following issues were discovered:

1. org.jsoup.helper.StringUtil used by MultiDropdown class has moved to internal package starting from 1.12.1
2. UISelectAssert is now generic

**Comment by clockworkbanana** [comment]
The change has been demonstrated to team and merged into master.
