### ISSUE TITLE
Demo platform UI tests: Add screenshot on failure for Allure report 

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2110]
An [Allure report](https://5ee24837c8f162898f279739--thirsty-yalow-da011e.netlify.app/) from recent [PR ](https://github.com/jdi-examples/jdi-light-report-portal-demo/pull/13)shows that currently we don't have screenshots for failed tests in Allure reports. That should be fixed.

**Comment by pnatashap** [comment]
Fixed in 1.3.6 version
