### ISSUE TITLE
Implement Cucumber Steps for WebPage Composite element 

### ISSUE THREAD

**Issue by Fenus4** [jdi-testing/jdi-light#215]
This is #23 decomposition, see it for details.

1. Implement steps for WebPage Composite element
2. Cover it this tests using https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html as reference
3. Add Documentation to Cucumber Steps Library
4. Add reference to Cucumber Steps Library doc to HTML elements documentation

**Comment by AlexeyGirin** [comment]
Add link to BDD article to main article (in HTML5 Composit elements section).
Finish documentation changes
@ChepelVE to create new task(s) for steps (depended on JS code) that don't work

**Comment by AlexeyGirin** [comment]
1. Lift code from the right up 
2. Add BDD and Java Tests links
3. Add code screenshot

**Comment by AlexeyGirin** [comment]
Demo has been done.
