### ISSUE TITLE
 Implement native iOS element: Switch

### ISSUE THREAD

**Issue by alexarm** [jdi-testing/jdi-light#2222]
Reference to Epic issue - #1924

Implement native iOS element: Switch

See its definition here: https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/
Cover its methods with "kind of unit" tests that verify it works properly (they should contain AssertThat and similar non-JDI methods)
Create test examples of how to use this element (with some tests)
Create an article in documentation with test examples from item 3. (Use HTML5 element article as an example)

**Comment by AlexeyGirin** [comment]
Demo has been done.
