### ISSUE TITLE
Implement native Android element: Toggle Buttons

### ISSUE THREAD

**Issue by alexarm** [jdi-testing/jdi-light#2248]
Reference to Epic issue - #2245 

Implement native Android element: Toggle Buttons
1. See its definition here: https://developer.android.com/guide/topics/ui/controls/togglebutton
2. Cover its methods with "kind of unit" tests that verify it works properly (they should contain AssertThat and similar non-JDI methods)
3. Create test examples of how to use this element (with some tests)
4. Create an article in documentation with test examples from item 3. (Use iOS element article as an example)

**Comment by AlexeyGirin** [comment]
Demo has been done.
