### ISSUE TITLE
Implement native Android element: Tooltips

### ISSUE THREAD

**Issue by alexarm** [jdi-testing/jdi-light#2251]
Reference to Epic issue - #2245

Implement native Android element: Tooltips
1. See its definition here: https://developer.android.com/guide/topics/ui/tooltips
2. Cover its methods with "kind of unit" tests that verify it works properly (they should contain AssertThat and similar non-JDI methods)
3. Create test examples of how to use this element (with some tests)
4. Create an article in documentation with test examples from item 3. (Use iOS element article as an example)

**Comment by Olesya24** [comment]
Standard widgets display tooltips based on the content of the title or content description properties. But Tooltip cannot be selected as a separate element in Appium.

**Comment by AleksandraMalygina** [comment]
hope, this will be of any help: https://stackoverflow.com/questions/30211827/not-able-to-perform-operation-on-tooltip-through-appium-android
