### ISSUE TITLE
Implement Cucumber steps for Html elements

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#23]
Implement methods for Cucumber for [html elements](https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html) methods

See example in [jdi-cucumber](https://github.com/epam/JDI/tree/master/Java/JDI/jdi-uitest-cucumber/src/main/java/com/epam/jdi/cucumber)

1. Create new methods for Cucumber steps (Cucumber Core) - use request from the team
2. Implement steps for Cucumber
2.1 Implement steps for Cucumber for Common Elements
2.2 Implement steps for Cucumber for Complex Elements
2.2 Implement steps for Cucumber for Composite Elements
3. Cover steps with tests - add JDI Light Cucumber dependency

**Comment by AlexeyGirin** [comment]
Closed since decomposed and all tasks are done.
