### ISSUE TITLE
Investigate Java 11 runtime error

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2373]
One of our users reported he got an error: 
RuntimeException: Runtime Can't init 'element' 
while using Java 11. 
At the same time - with Java 8 it works w/o the exception
Please investigate.

Source project: https://github.com/GhMartingit/qa-task

**Comment by pnatashap** [comment]
Additional parameter is needed for AspectJ lib.

    SUREFIRE_ARGS: "--add-opens java.base/java.lang=ALL-UNNAMED"
    SUREFIRE_ARGS_BDD: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED  --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
