### ISSUE TITLE
Fix bdd test scenarios

### ISSUE THREAD

**Issue by gbuh** [jdi-testing/jdi-light#2385]
The jdi-bdd-tests module has a failed test suite that needs to be fixed.
See failed travis builds:
https://travis-ci.com/github/jdi-testing/jdi-light/jobs/393254044
https://travis-ci.com/github/jdi-testing/jdi-light/jobs/393254045

**Comment by pnatashap** [comment]
All bdd tests passed for now.
It seem's that the task can be closed? @gbuh @AlexeyGirin

**Comment by GgStormer** [comment]
Result of running tests in jdi-bdd-tests folder:
Tests run: 922, Failures: 0, Errors: 0, Skipped: 0

**Comment by pnatashap** [comment]
Test works fine, some of them skipped for firefox
