### ISSUE TITLE
Implement List element for MobileAppElement and MobileUIElement

### ISSUE THREAD

**Issue by alexarm** [jdi-testing/jdi-light#2395]
1. Implement an element like WebList in JDI Light
2. Create/Update methods that return WebList for MobileAppFactory/MobileUIFactory

**Comment by groonyn** [comment]
PArty completed in another task with $$, made Unified list for JDI Elemements.

**Comment by AlexeyGirin** [comment]
Question to @RomanIovlev

**Comment by AlexeyGirin** [comment]
Fixed.
