### ISSUE TITLE
Fix broken syntax for JDI Light Mobile

### ISSUE THREAD

**Issue by alexarm** [jdi-testing/jdi-light#2414]
fix issues related to incorrect syntax
Codacy Verification Pattern:
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=17839124&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUxOTkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by tsvetaevAlex** [comment]
Codacy Verification Pattern:
https://app.codacy.com/manual/jdi-testing/jdi-light/issues?bid=16431431&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJFcnJvclByb25lIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUxOTkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by tsvetaevAlex** [comment]
demo has been done
