### ISSUE TITLE
Смена element.search.strategy на soft или any, multiple не влияет на поиск

### ISSUE THREAD

**Issue by StrikS** [jdi-testing/jdi-light#2470]
Несмотря на то, что element.search.strategy=soft или any, multiple
ошибка:
`java.lang.RuntimeException: [12:25.51] Failed to execute 'UIElement.click' for element 'locator' during '10' seconds. Found N elements instead of one for Element 'locator (xpath='locator')' during 10 seconds`
по прежнему выдается

Воспроизводится, как в случае если локатор начинается с $, так и в случае, если вынесен в переменную с аннотацией

[Ветка с тестом-примером, воспроизводящим дефект](https://github.com/StrikS/jdi-light-junit-template/tree/search_strategy_bug)

**Comment by StrikS** [comment]
Мерж #2471 должен фиксить эту проблему.

**Comment by AlexeyGirin** [comment]
@StrikS можешь проверить - исчезла проблема?

**Comment by StrikS** [comment]
Проблема исчезла, ошибка не выдаётся
