### ISSUE TITLE
Problem with Java 11

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2540]
Good evening everyone! So I have already checked with you guys about failing to run test cases from jdi-introduction project using Java 11 and after changing it to 1.8, it was working like a charm. But is there any way that Java 11 can still be used for this project and make it work?
I tried to start from scratch and made changes to the intro repo to run it against java 11 and here's the repo --> https://github.com/krathina/jdi-intro-java11

@RomanIovlev please have a look

**Comment by pnatashap** [comment]
Will check our tests on JDK 11

**Comment by pnatashap** [comment]
Current situation with our test for JDK 11:
Brief passed/failed/broken/skipped summary by JDK: 11
  Passed:  2605
  Failed:  6
  Broken:  1
  Skipped: 16
Will check the failures, but there is no significant difference with JDK8

**Comment by pnatashap** [comment]
All tests works fine on JDK 11, additional parameters are needed
    
SUREFIRE_ARGS: "--add-opens java.base/java.lang=ALL-UNNAMED"
    SUREFIRE_ARGS_BDD: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED  --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
