### ISSUE TITLE
Tansform element BDD articles for elements: Icon, Title, RadioButtons, Table

### ISSUE THREAD

**Issue by Fenus4** [jdi-testing/jdi-light#256]
See the complete list of common BDD steps here: https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd-tests/src/test/resources/steps_list

Replace every capital letter with lower case one at the beginning of every step for both - article and code example
Make sure "the" is present after each "Then" at validation step if applicable
Make sure "< I >" is present for each action step if applicable
Add steps that are absent and applicable for that element (for both - article and code example)
Make sure that link to the Tutorial looks like: More information in the < link >Tutorial< /link >
Make sure that link to tests looks like: < link >Cucumber tests< /link > for <ELEMENT_NAME>
Make sure that label for action steps examples (at the right) looks like: "<ELEMENT_NAME> action examples:"
Make sure that label for validation steps examples (at the right) looks like: "<ELEMENT_NAME> validation examples:"
Make sure that label for scenario examples (at the right) looks like: "Scenario example(s) for <ELEMENT_NAME>:"
Make sure that there is no italic text in the article
Remove is "basically valid" step(s) if any
Make sure that brakes (< br >) at the end of the article synchronize left and right parts
Remove "More examples are available in the Tutorial section." from code example if any

**Comment by AlexeyGirin** [comment]
1. Remove Title article from Documentation (from common elements section)
2. Create copy for Icon from Image (add clarification note that it is alias for Image)

**Comment by AlexeyGirin** [comment]
Demo has been done.
