### ISSUE TITLE
Implement mobile web element: Label

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2583]
Reference to Epic issue - https://github.com/jdi-testing/jdi-light/issues/1858

1. Extend JDI Light element: Label
with mobile capabilities (if possible) using generic UI web (html) mobile element created in the context of task #1667
2. Cover its methods with "kind of unit" tests that verify it works properly (they should contain AssertThat and similar non-JDI methods)
3. Create test examples of how to use this element (with some tests)
4. Create an article in documentation with test examples from pp.3. Use HTML5 element article as an example

**Comment by groonyn** [comment]
work fine on mobile web after implementation and merging of  https://github.com/jdi-testing/jdi-light/pull/2568

**Comment by groonyn** [comment]
no need to do after adaptation html tests for mobile. It was merged here https://github.com/jdi-testing/jdi-light/pull/2569
