### ISSUE TITLE
Documentation: merge two instances of the Icon article.

### ISSUE THREAD

**Issue by Fenus4** [jdi-testing/jdi-light#259]
There are two instances of the "Icon" article in the Documentation \ Common elements section

1. https://jdi-docs.github.io/jdi-light/#icon
2. https://jdi-docs.github.io/jdi-light/#icon-2

These two should be investigated and carefully merged to one article.

In case you'll find out that articles should stay separate, than jоustify that opinion in this comments sections please, PLUS rename one of the articles to avoid shared naming.

**Comment by AlexeyGirin** [comment]
Demo has been done.
