### ISSUE TITLE
Add tests with using Remote web driver Selenoid

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#26]
Add few tests as example for using Selenoid (remote driver)
\* Implement Selenoid properties file if necessary
Repository with project
https://github.com/jdi-templates/jdi-light-selenoid-template
Link to Selenoid Documentation: https://aerokube.com/selenoid/latest/

**Comment by AlexeyGirin** [comment]
Contact with @AnnaDreval regarding task details (take repository address from her and update example project in it with test that executed concurrently using selenoid)

**Comment by AnnaDreval** [comment]
Repository address: https://github.com/jdi-templates/jdi-light-selenoid-template
Selenoid instruction: https://aerokube.com/selenoid/latest/
