### ISSUE TITLE
Add additional BDD verification steps for DropDown

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#266]
Add additional BDD verification steps for DropDown:
1. expand()
2. close()

**Comment by 886-59-936** [comment]
Additional Bdd steps and new tests added.
But I have found that these steps are not applicable to DropDown used for <select> element. New issue created for this: https://github.com/jdi-testing/jdi-light/issues/1747

**Comment by romaha08** [comment]
Demo has been done. New issue created for this: https://github.com//issues/1747
