### ISSUE TITLE
Material UI tests: Implement Inputs - Transfer List

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2699]
Reference to the Epic - #2608 and  #2683

All steps are described in [the Material UI tests guide](https://epam-my.sharepoint.com/:w:/r/personal/alexey_girin_epam_com/Documents/JDI/JDI%20Light/Material-UI_tests_guide.docx?d=w5c44c14660654df6aa2b81b1b782ca55&csf=1&web=1&e=cDdINv).

**Comment by cold-flame** [comment]
Demo has been done
