### ISSUE TITLE
Add tests with using Remote web driver Sauce Labs

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#27]
Add few tests as example for using SauceLabs (remote driver)
\* Implement SauceLabs properties file if necessary

**Comment by AlexeyGirin** [comment]
@RomanIovlev to provide test for demo

**Comment by AlexeyGirin** [comment]
DriverData.CAPABILITIES_FOR_CHROME

**Comment by AlexeyGirin** [comment]
Для SauceLabs можно прямо взять этот проект - он у нас пример
скопировать и сделать так чтобы оно запускалось через SauceLabs https://github.com/jdi-templates/jdi-light-testng-template

**Comment by AlexeyGirin** [comment]
1. Положить все пять тестов в темплэйты
2. Создать рид ми
3. Создать документацию
4. @RomanIovlev создать репозиторий

**Comment by AlexeyGirin** [comment]
Demo has been done.

**Comment by RomanIovlev** [comment]
https://github.com/jdi-templates/jdi-light-saucelabs
