### ISSUE TITLE
BDD Form add json support

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#270]
Add ability to fill, submit, check Form with name of entity in BDD
like 
When fill form "Contact Form" with "Roman Contacts"
When submit form "Contact Form" with "Roman Contacts"
Then the form "Contact Form" data equals to  "Roman Contacts"'

related to https://github.com/jdi-testing/jdi-light/pull/261/files

Put data to fill form in json files in resources like
{
	name: "Roman",
	lastName: "Iovlev"
....
}

**Comment by AlexeyGirin** [comment]
@ChepelVE, please correct documentation (replace <> with [] for actions) and add jSON example for filling form - show options for filling (add to examples)

**Comment by AlexeyGirin** [comment]
Demo has been done.
