### ISSUE TITLE
Remove AllurePropertiesGenerator from tear down

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#2793]
Вот это в файле  jdi-light-mobile-html-web-tests/src/test/java/io/github/epam/TestsInit.java

    @AfterSuite(alwaysRun = true)
    default void tearDown() {
        new AllurePropertiesGenerator().createAllureProperties();

вызывает сомнения - почему мы используем генерацию репорта впрямую да ещё и в тир дауне?
Это значит, что в обычном тесте для мобайла по умолчанию репорта не будет без этого хака

**Comment by pnatashap** [comment]
проект вообще удален
