### ISSUE TITLE
Fix Codacy issues for Material UI branch

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#2840]
Setting that are now set for Codacy:

branches: master, Material-UI

Ignored files:
CHANGELOG.md
jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/select/CustomTriggerTextSelectTests.java
jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/MaterialSelectorUnitTests.java
jdi-light-angular-tests-with-mocks/src/test/java/io/github/epam/angular/unit/tests/with/mocks/CheckboxTest.java
jdi-light-angular-tests-with-mocks/src/test/java/io/github/epam/angular/unit/tests/with/mocks/SlideToggleTest.java
jdi-light-mobile/README.md
jdi-light-mobile-tests/README.md
jdi-light-mobile-tests/src/test/java/nativeapp_android/MobileFileManagerInit.java
pom.xml
README.md
reporting.sh
reports.sh

When finish with this issue need to set only mentioned ignored files.

**Comment by tsvetaevAlex** [comment]
![IgnoreListBeforeGlobalMuiACtivity](https://user-images.githubusercontent.com/56589282/111994268-a51c9a80-8b28-11eb-9993-3d58d7eeb289.png)

**Comment by tsvetaevAlex** [comment]
JDI-Light Repository Codacy Setting Ignored files; After changes.
![IgnoreLIst _AfterChanges](https://user-images.githubusercontent.com/56589282/111995935-91723380-8b2a-11eb-83f7-58434bf9625d.png)

fromnow only two folders will be included to codacy Verification:
 - jdi-light-material-ui-tests
 -  jdi-light-material-ui
 -

**Comment by tsvetaevAlex** [comment]
3/22/2021 4 PM: Alex T(Aleksander_Tsvetaev@epam.com):
update ignore List

**Comment by tsvetaevAlex** [comment]
3.22.2021 6:30PM Alex T:
new configuration applied:
Latest Verification Report:

![_3-22-2021-6-34PM-LatestReport](https://user-images.githubusercontent.com/56589282/112016467-c9cf3d00-8b3d-11eb-97ff-06f82b003ab2.png)

**Comment by evasileva-epam** [comment]
Demo has been done

**Comment by tsvetaevAlex** [comment]
![MuiCasper](https://user-images.githubusercontent.com/56589282/113585483-f488bd80-9634-11eb-9396-74532c6559c4.png)
