### ISSUE TITLE
Investigate if Material UI tests could be refactored without using frame variables

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#2843]
See examples for e.g. in angular tests.

Create example variant for 1 element.

**Comment by LunAndrey** [comment]
inspecting this issue showed that at this stage we can't escape Frame variables.
But when materialUI front will updated on new UI version, frame can be removed and we can escape frame variables.

**Comment by evasileva-epam** [comment]
In tests for meterial ui new page there's no frame variable
