### ISSUE TITLE
Fix Codacy Notificationss related to master branch

### ISSUE THREAD

**Issue by evasileva-epam** [jdi-testing/jdi-light#2870]
4/5/2021: Aleksander Tsvetaev:
new branch created: https://github.com/jdi-testing/jdi-light/tree/Task2870_codacySolutions
 from JDI-Light master branch.
---  ✄ ------------------------------------------------------
branch made to store fixes  regarding Codacy Notifications.

*Misc:
links to relative tasks will be added in comments below

**Comment by tsvetaevAlex** [comment]
Codacy: variables declaration #2874
https://github.com/jdi-testing/jdi-light/issues/2874
