### ISSUE TITLE
Codacy: variables declaration

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2874]
PMD 5.0
Use one line for each declaration, it enhances code readability.
Pattern: https://app.codacy.com/manual/jdi-testing/jdi-light/issues?bid=10286453&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU0MzkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by cold-flame** [comment]
not relevant
