### ISSUE TITLE
fix Issues regarding to Method Naming Conventions

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2880]
fix Codacy notifications related to
Codacy pattern:https://app.codacy.com/manual/jdi-testing/jdi-light/issues?bid=10286453&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjU0ODciXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by cold-flame** [comment]
Demo has been done
