### ISSUE TITLE
Switch  should have a Defailt case

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2887]
add default label into Switch
pattern: https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=22954971&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyNjMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by evasileva-epam** [comment]
Demo has been done

**Comment by LunAndrey** [comment]
Demo has been done
