### ISSUE TITLE
Resolve codacy pattern: Avoid reassigning parameters

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2920]
Codacy Pattern: Avoid reassigning parameters
Pattern: https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=21793422&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUzMjkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by LunAndrey** [comment]
Demo has been done
