### ISSUE TITLE
resolve codacy pattern: Avoid unused local variables

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2922]
Why is this an issue?

Since: PMD 1.0

Reassigning values to incoming parameters is not recommended. Use temporary local variables instead.
Pattern: https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=21793422&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyMzIiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by LunAndrey** [comment]
Demo has been done
