### ISSUE TITLE
shift of Fields declaration

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2930]
Resolve Codacy Pattern:
Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
pattern:
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=21793422&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjUyNzMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by cold-flame** [comment]
Demo has been done
