### ISSUE TITLE
Fix title name on Material UI: Navigation - Button_navigation

### ISSUE THREAD

**Issue by Fwerfad** [jdi-testing/jdi-light#2959]
https://jdi-testing.github.io/jdi-light/material/button_navigation
Change Buttom Navigation to Button Navigation

**Comment by AlexeyGirin** [comment]
Для Наташи

**Comment by Youfka** [comment]
нет компонента button_navigation, исправила на  bottom_navigation https://material-ui.com/components/bottom-navigation/
