### ISSUE TITLE
Onboarding Task

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#2998]
environment setup
automated TC`s execution

**Comment by strrust** [comment]
Cloned **jdi-testing/jdi-light** project to local machine from github, checked out to **Material-UI branch**, rebuilt project. Then all tests from **jdi-light-material-ui-tests** were run at once, and then again in blocks (displaydata, feedback, inputs, layout, navigation, surfaces, utils). In check process with expected results from Controlls excel file there are a few differences: Menu/Simple and Menu/Context TC's in navigation block passed, AppBar/Back TC in surfaces block failed with assertion failure. The rest of the TC's passed according to the excel file.

**Comment by tsvetaevAlex** [comment]
demo has been done:
board cards - created correctly
detection of failing test cases completed
