### ISSUE TITLE
UIElement.isVisible() has blind zone

### ISSUE THREAD

**Issue by Serporit** [jdi-testing/jdi-light#3003]
**com.epam.jdi.light.elements.common.UIElement.isVisible()**

    @JDIAction(value = "Check that '{name}' is visible by user", timeout = 0)
    public boolean isVisible() {
        if (isHidden())
            return false;
        Object isInView = js().executeScript(
            "const rect = arguments[0].getBoundingClientRect();\n" +
            "if (!rect) return false;\n" +
            "const windowHeight = Math.min(window.innerHeight || document.documentElement.clientHeight);\n" +
            "const windowWidth = Math.min(window.innerWidth || document.documentElement.clientWidth);\n" +
            "const ratio = arguments[1];\n" +
            "const reduceHeight = ratio*windowHeight;\n" +
            "const reduceWidth = ratio*windowWidth\n" +
            "if (rect.top < reduceHeight) return false;\n" +
            "if (rect.left < reduceWidth) return false;\n" +
            "if (rect.bottom > windowHeight-reduceHeight) return false;\n" +
            "if (rect.right > windowWidth-reduceWidth) return false;\n" +
            "return true;", getWebElement(), 0.05);
        return (boolean)isInView;
    }

This method has a 'blind zone' where element is considered as not visible: top 5% of a window, botton 5%, left 5% and right 5%.
Any elements in topbar or some side panels will be always considered as not visible.

![image](https://user-images.githubusercontent.com/43556422/125632476-b8bb4484-bcd9-489c-afcb-1cf97c25e224.png)

No idea why it is implemented such way but it needs to be fixed

**Comment by pnatashap** [comment]
Looks like fixed, please create a new issue if it is still reproduced
