### ISSUE TITLE
Fix Multiselect scenario issue

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#303]
Fix scenario
@failed
  Scenario: multi select
    Given I open "Html5 Page"
    When Select fields from "Multi Dropdown":
    |Steam|
    |Wood|
    Then the "Multi Dropdown" text equals to "Steam;Wood"

java.lang.AssertionError: java.lang.AssertionError: 
Expected: is "Steam;Wood"
     but: was "Steam"
Expected :Steam;Wood
Actual   :Steam

**Comment by AlexeyGirin** [comment]
Demo has been done. (Test has been removed since it is incorrect)
