### ISSUE TITLE
Vuetify tests: Implement Groups - Item groups 

### ISSUE THREAD

**Issue by evgenii-liashenko** [jdi-testing/jdi-light#3158]
Reference to the Epic - #3036 and #3116 

All steps are described in [the Vuetify tests guide.](https://epam-my.sharepoint.com/:w:/p/evgenii_liashenko/Ef5Y3JcicTlPtMmtHg_19T8BLDZqSkBEa7oOgyDxq_hgUA?e=TUcIPI)

Tasks:

- [x] implementing ItemGroup
- [x] refactoring ButtonGroup #3831 
- [x] refactoring SlideGroup #3833
- [ ] refactoring ChipGroup #3834

**Comment by MayaElf** [comment]
CLOSED. The tasks were udated and done.
