### ISSUE TITLE
Add non Page Object BDD implementation for basic steps (JDISteps)

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#319]
Add similar steps as in [JDISteps.java](https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd/src/main/java/com/epam/jdi/bdd/JDISteps.java) and feature tests like in [BaseUIElement.feature](https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd-tests/src/test/resources/features/BaseUIElement.feature) but with parameter locator instead of an element name
	When I click on "[value*='Red Button']" element
	When I send keys "simple 1234" to "#name" element
	Then the "#name" element's text matches to "\w{6} \d{4}"
etc.

**Comment by AlexeyGirin** [comment]
@RomanIovlev to provide consultation for @IgorGaidukEpam

**Comment by AlexeyGirin** [comment]
Demo has been done.
