### ISSUE TITLE
tune up Codacy for Vuetify

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3194]
activate and make initial configuration of Codact

**Comment by tsvetaevAlex** [comment]
Codacy Plugged in and configured to the Vuetify branch.

![Codacy0](https://user-images.githubusercontent.com/56589282/127322430-31d348f5-56a0-4b3a-a576-443e1f9ab88b.png)

**Comment by IgorGaidukEpam** [comment]
Demo has been done
