### ISSUE TITLE
Add Smart Locators support in BDD implementation for basic steps (JDISteps)

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#321]
Add similar steps as in [JDISteps.java](https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd/src/main/java/com/epam/jdi/bdd/JDISteps.java) and feature tests like in [BaseUIElement.feature](https://github.com/jdi-testing/jdi-light/blob/bdd/jdi-light-bdd-tests/src/test/resources/features/BaseUIElement.feature) but with locators from simple file-based PageObjects instead of an element name
	When I click on "Red button" element
	When I send keys "simple 1234" to "Name" element
	Then the "Name" element's text matches to "\w{6} \d{4}"
etc.
Miss elements Name in src/test/resources/html5.page
> Red button: [value*='Red Button']

In this case, element Name searched by the smart locator #name

**Comment by AlexeyGirin** [comment]
Demo has been done.
