### ISSUE TITLE
Material UI: Check Breadcrumb component

### ISSUE THREAD

**Issue by daxdue** [jdi-testing/jdi-light#3219]
Reference to the pull request - #3117
Reference to issue comments:
https://github.com/jdi-testing/jdi-light/pull/3117#discussion_r683259868
https://github.com/jdi-testing/jdi-light/pull/3117#discussion_r683260302

To fix issue:
1. Use new branch created from **master_material_ui** branch
2. Check the existence of Breadcrumb component in jd-light-material-ui or jdi-light
3. If the component exists refactor tests using the component
4. If the component doesn't exist assess the need for the component to be added to material-ui. If the component has specific functions that are not defined in basic JDI controls you need to implement the component otherwise you need to use basic JDI-Light controls.
5. Push changes.
6. Create pull request to **master_material_ui**

**Comment by Flowina** [comment]
Fixed in #3205
