### ISSUE TITLE
Make all Template repositories actual - ДЕКОМПОЗИРОВАТЬ

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#3250]
1. Go one by one (in order below) through all the [template repositories](https://github.com/jdi-templates/), update the version of JDI to the latest one (see [maven central](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light)) current version is 1.3.13 (soon will be 1.3.14)
Update version of aspectj to 1.9.6 as well
2. Run all tests in the repo and make sure they all pass successfully
3. Fix issues in tests or create a list of required issue fixes in libraries for each failed project
4. place actual status for reviewed repo 
`Non reviewed` - default status
`In review (name)` - Is in review, someone work on this repo
`Fail` - build version changed to latest but tests failed and it is require some time to fix issues
`Up-to-date (dd-MM-yyyy)` - Build updated to the latest and all tests pass

- [x] jdi-light-testng-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-dark-testng-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-light-junit-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] [jdi-introduction](https://github.com/jdi-examples/jdi-introduction) - `Up-to-date (23-11-2022)` - ci обновлен
- [x] jdi-light-bdd-template - `Up-to-date (24-11-2022)` - ci обновил
- [x] jdi-light-browserstack - `Up-to-date (24-11-2022)` - ci обновил
- [x] [simple-jdi-light-baeldung](https://github.com/jdi-examples/simple-jdi-light-baeldung) - `Up-to-date (25-11-2022)` ci обновлен
- [x] jdi-dark-junit-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-light-selenoid-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-light-saucelabs - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-dark-bdd-testng-template - `Up-to-date (25-11-2022)` - ci обновлен
- [x] [jdi-light-intro](https://github.com/jdi-examples/01-jdi-light-intro)  - `Up-to-date (25-11-2022)` - ci обновлен
- [x] jdi-dark-bdd-junit-template - `Up-to-date (25-11-2022)` - ci обновлен, но почему-то сами тесты не запускаются.
- [x] jdi-bdd-no-po-tests - `Up-to-date (18-11-2022)` - версии обновлены, локально тесты проходят нормально, не работает с jdk 16+, и локально не работают предусловия
- [x] jdi-gradle-template - `Up-to-date (06-01-2023)` - https://github.com/jdi-testing/jdi-light/issues/3292 - version up required - попробовал обновить, проект как-то криво открывается, пока отложил
- [ ] jdi-nova-template - `Up-to-date (24-11-2022)` - ci обновил, по прежнему ошибки с драйвером хрома (https://github.com/jdi-templates/jdi-nova-template/actions/runs/3540275248/jobs/5943128924) Наташа сказала отложить т.к не понятно насколько он изначально работоспособен
- [ ] jdi-light-mobile-android-template - `In review (Anton)` - #3343 - версии обновил, но тесты на виртуальном девайсе не отрабатывают.
- [ ] jdi-light-mobile-ios-template - `Non reviewed` - пустой проект в мастер ветке.
- [ ] jdi-light-csharp-template - `Non reviewed` -НЕ РЕВЬЮИТЬ
- [x] Добавить в какой-либо testng проект запуск через firefox - попробовал перевести jdi-light-intro, в git actions падает на попытке скачать драйвер (https://github.com/jdi-examples/01-jdi-light-intro/actions/runs/3444431576/jobs/5747028090#step:7:166)
- [x] [jdi-light-report-portal-demo](https://github.com/jdi-examples/jdi-light-report-portal-demo) - нет доступа к https://dev.fleetframework.io/ судя по всему больше нет такого портала - РЕШИЛИ ОСТАВИТЬ КАК ЕСТЬ
- [x] [jdi-dark-report-portal-demo](https://github.com/jdi-examples/jdi-dark-report-portal-demo) - нет доступа к https://dev.fleetframework.io/ судя по всему больше нет такого портала - РЕШИЛИ ОСТАВИТЬ КАК ЕСТЬ

**Comment by pnatashap** [comment]
Also it's very important to change aspectj version 1.9.6, without this change we can get a error on JDK 11+

**Comment by RomanIovlev** [comment]
Note about aspectj added to the description

**Comment by n-ton4** [comment]
> Also it's very important to change aspectj version 1.9.6, without this change we can get a error on JDK 11+

But as of now we continue using Java 8 right?

**Comment by pnatashap** [comment]
Jdi is tested on jdk 8-14, the same should be for templates

**Comment by n-ton4** [comment]
jdi-light-testng-template - https://github.com/jdi-templates/jdi-light-testng-template/pull/9/
jdi-gradle-template - this repository was updated long time ago; as for me it needs to be reviewed firstly by somebody who was involved in development 
jdi-nova-template - there are no dependencies on jdi-light and aspectj
jdi-dark-testng-template - https://github.com/jdi-templates/jdi-dark-testng-template/pull/11, there is no dependency on jdi-light
jdi-light-junit-template - https://github.com/jdi-templates/jdi-light-junit-template/pull/8, there is no dependency on aspectj
jdi-light-selenoid-template - https://github.com/jdi-templates/jdi-dark-testng-template/pull/11, there is no dependency on jdi-light
jdi-bdd-no-po-tests - https://github.com/jdi-templates/jdi-light-selenoid-template/pull/2, there are test failures not related to new code changes
jdi-light-bdd-template - Non reviewed
jdi-light-browserstack - Non reviewed
jdi-light-saucelabs - Non reviewed
jdi-dark-bdd-testng-template - Non reviewed
jdi-dark-bdd-junit-template - Non reviewed
jdi-dark-junit-template - Non reviewed
jdi-light-mobile-android-template - Non reviewed
jdi-light-mobile-ios-template - Non reviewed
jdi-light-csharp-template - Non reviewed

**Comment by AlexeyGirin** [comment]
1. Обновить версию во всех шаблонах до Релизной
2. Создать Гитнаб Экшен он деманд который позволяет запустить все шаблоны (тесты) и проверить их работоспособность

**Comment by AlexeyGirin** [comment]
Декомпозировать в список задач по актуализации шаблонов

**Comment by AlexeyGirin** [comment]
Done.
