### ISSUE TITLE
Test vuetify elements working properly

### ISSUE THREAD

**Issue by knadonenko** [jdi-testing/jdi-light#3289]
Parent task: #3274

Test vuetify elements on testing page from Alerts till Groups. https://jdi-testing.github.io/jdi-light/vuetify/alerts
Verify everything works correctly and if not create an issue to fix it

**Comment by knadonenko** [comment]
Reference web page: https://vuetifyjs.com/en/components/alerts/

**Comment by nechepurenkoN** [comment]
I checked all vuetify elements from Alerts till Groups. 

All these elements are working as expected. So, if an element is actionable on the [docs](https://vuetifyjs.com/en/components) page, it has the same behavior on the [JDI-testing page](https://jdi-testing.github.io/jdi-light/vuetify).

The only strangeness I noticed is the grouping container.
When I have a full-sized browser window (my screen width is 1980px) some grouping containers looks like on the screenshot below:

![Full sized](https://i.imgur.com/PxFMvjF.png)

The container block (with a shadow) has arrows to horizontally scroll the group as its content is wider than the width of the container.

When I shrink the window to half of its size, the container is still narrower than its content but the arrows are gone.

![Half sized](https://imgur.com/ftWdaYw.png) 

I checked this behavior on the [JDI-testing page](https://jdi-testing.github.io/jdi-light/vuetify). Arrows are shown then the window width is between 1240px and 1887px approximately. So if we have a maximized window tests, we can have these arrows or not depending on the max screen width and that seems flaky.

I'm not sure are those arrows important to test and if this strangeness deserves to be an issue or not.

**Comment by AlexeyGirin** [comment]
Done.
