### ISSUE TITLE
Test vuetify elements working properly №2

### ISSUE THREAD

**Issue by knadonenko** [jdi-testing/jdi-light#3290]
Parent task: #3274

Test vuetify elements on testing page from Dividers till last element. https://jdi-testing.github.io/jdi-light/vuetify/alerts
Verify everything works correctly and if not create an issue to fix it

**Comment by knadonenko** [comment]
https://vuetifyjs.com/en/components/alerts/

**Comment by Liliya-web** [comment]
I have found a lot of suspicious things when I test the site, but I think that most of them are not critical and maybe are the features. The document with founded issues is attached. I need a somebodies consultation to decide which of them are bugs
[Vuetify issues_part2.docx](https://github.com/jdi-testing/jdi-light/files/7141332/Vuetify.issues_part2.docx)

**Comment by AlexeyGirin** [comment]
Done.
