### ISSUE TITLE
jdi-dark-bdd-junit-template - workflow fails (compile issues and no tests)

### ISSUE THREAD

**Issue by n-ton4** [jdi-testing/jdi-light#3294]
There are compile issues, need some assistance to sort them out, also steps are not implemented.

Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project jdi-dark-bdd-template: Compilation failure: Compilation failure: 
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/com/epam/jdi/httptests/steps/InitService.java:[7,32] package com.epam.jdi.http does not exist
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/com/epam/jdi/httptests/steps/InitService.java:[7,1] static import only from classes and interfaces
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/CucumberTest.java:[1,25] package io.cucumber.junit does not exist
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/CucumberTest.java:[2,25] package io.cucumber.junit does not exist
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/CucumberTest.java:[3,24] package org.junit.runner does not exist
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/CucumberTest.java:[5,2] cannot find symbol
Error:    symbol: class RunWith
Error:  /home/runner/work/jdi-dark-bdd-junit-template/jdi-dark-bdd-junit-template/src/test/java/CucumberTest.java:[6,2] cannot find symbol
Error:    symbol: class CucumberOptions

**Comment by pnatashap** [comment]
fixed
