### ISSUE TITLE
jdi-dark-bdd-testng-template - workflow fails (compile issues and no tests)

### ISSUE THREAD

**Issue by n-ton4** [jdi-testing/jdi-light#3295]
There are compile issues, need some assistance to sort them out, also steps are not implemented.

Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project jdi-dark-bdd-testng-template: Compilation failure: Compilation failure: 
Error:  /home/runner/work/jdi-dark-bdd-testng-template/jdi-dark-bdd-testng-template/src/test/java/com/epam/jdi/httptests/steps/InitService.java:[7,32] package com.epam.jdi.http does not exist
Error:  /home/runner/work/jdi-dark-bdd-testng-template/jdi-dark-bdd-testng-template/src/test/java/com/epam/jdi/httptests/steps/InitService.java:[7,1] static import only from classes and interfaces

**Comment by pnatashap** [comment]
fixed
