### ISSUE TITLE
Vuetify: Unstable arrows in a group container

### ISSUE THREAD

**Issue by nechepurenkoN** [jdi-testing/jdi-light#3296]
Reference to #3036.

**Feature request**: create a container with a fixed width for a grouping container.

When I have a full-sized browser window (my screen width is 1980px) some grouping containers looks like on the screenshot below:

![Full sized](https://i.imgur.com/PxFMvjF.png)

The container block (with a shadow) **has arrows** to horizontally scroll the group as its content is wider than the width of the container.

When I shrink the window to half of its size, the container is still narrower than its content but **the arrows are gone**.

![Half sized](https://imgur.com/ftWdaYw.png) 

I checked this behavior on the [JDI-testing page](https://jdi-testing.github.io/jdi-light/vuetify). Arrows are shown then the window width is between 1240px and 1887px approximately. So if we have a maximized window tests, we can have these arrows or not depending on the max screen width and that seems flaky.

Suggested feature: create an outer container with a fixed width to have those arrows always **displayed regardless of the screen width** or introduce another way of solving this issue.

**Comment by vklonin** [comment]
done in a recent review process
