### ISSUE TITLE
Помочь Сергею

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3312]
Skype: live:striks.work
Добрый день!
У меня проблема с элементарной задачей: сделать так, чтобы selenoid запускал не latest версию хрома, а конкретную (например 88.0). 

Какую бы я версию не указывал в drivers.version, в итоге всегда получаю: 

Почти 2 часа на убил, разбираясь, думал наверняка проблема на моей стороне. Но теперь не уверен в этом.

Кто пользуется selenoid, попробуйте, пожалуйста, изменить drivers.version=latest на 88.0 или любую другую версию хрома, которая вам доступна.

Если нужен пример на поиграться, то
Шаги:
	1. Скачать https://github.com/jdi-templates/jdi-light-selenoid-template
	2. Указать в test.properties (можно полностью стерев, что там есть и заменив этим):
driver=chrome
drivers.version=88.0
timeout.wait.element=10
domain=${domain}
#driver.getLatest=true Такого параметра уже нет https://github.com/jdi-testing/jdi-light/issues/74
driver.remote.url=http://xn--80ad1e хаб selenoid/wd/hub
driver.remote.run=true
	3. Запустить любой тест

P.S. Это точно не проблема selenoid, так как там 88.0 версия хрома есть и успешно используется в других проектах

![image](https://user-images.githubusercontent.com/26869421/133253811-22253ad2-d081-46d5-8873-5649022918fb.png)

**Comment by n-ton4** [comment]
Привет. Используй driver.version, а не drivers.version в test.properties.

**Comment by StrikS** [comment]
Добрый день. Тот же результат:  какую бы версию не указывал в driver.version, получаю latest в selenoid

Пробовал в том же шаблоне https://github.com/jdi-templates/jdi-light-selenoid-template

P.S. drivers.version был взят из test.properties, вышеуказанного шаблона. Поэтому перед закрытием ишью там нужно будет заменить drivers.version на driver.version. Я бы создал ПР сам, но изменение слишком мелкое, поэтому проще вам самим коммит сделать.

**Comment by n-ton4** [comment]
https://github.com/jdi-templates/jdi-light-selenoid-template/pull/3

**Comment by n-ton4** [comment]
Я сейчас разверну селенойд локально с версией хрома 88 и запущу тесты из мастера. По результатам отпишусь. К слову без использования ремоут драйвера driver.version проперти обрабатывается как ожидается. На примере driver.version=88 скачивается именно эта версия, а не последняя.

**Comment by n-ton4** [comment]
Тут по ходу дело не в том, что берется latest, а вообще версия драйвера не передается в capabilities RemoteWebDriver и в таком случае запускается браузер, помеченный как default в browsers.json. В моем случае это версия 88.

"chrome": {
        "default": "88.0",
        "versions": {
            "88.0": {
                "image": "selenoid/chrome:88.0",
                "port": "4444",
                "path": "/"
            },
            "89.0": {
                "image": "selenoid/chrome:89.0",
                "port": "4444",
                "path": "/"
            }
        }
    }

Судя по всему это баг.

**Comment by n-ton4** [comment]
@StrikS какую версию селенойда Вы используете?

**Comment by n-ton4** [comment]
В общем это все-таки баг в jdi light, обойти к-й можно, попробовав вытащить Capabilities и записать туда browserVersion c нужной версией драйвера, например, "93.0"/ И уже после создавать сессию (отправлять запрос в Selenoid).

**Comment by AlexeyGirin** [comment]
Создан баг - #3333

**Comment by StrikS** [comment]
Обновил версию JDI до 1.3.16, куда должен был войти фикс. Проблема сохранилась.

Посмотрите, пожалуйста, пофиксилось ли у вас.

**Comment by StrikS** [comment]
√ Пофикшено в 1.3.16. Спасибо  
Разработчик уточнил, что в случае селеноида, нужно использовать не driver.version=88.0 в test.properties. А browserVersion=88.0 в chrome.properties
