### ISSUE TITLE
Selenoid: cannot unmarshal number into Go struct field Caps.desiredCapabilities.browserVersion of type string

### ISSUE THREAD

**Issue by n-ton4** [jdi-testing/jdi-light#3333]
There is an issue starting session in RemoteWebDriver with specific browser version in Selenoid.
I use src/test/resources/chrome.properties with browserVersion=93.0.
When I try to run tests I get the following exception:

14:44:14.003 [main] DEBUG JDI : ERROR: Failed to setup remote chrome driver. Exception: org.openqa.selenium.WebDriverException: json: cannot unmarshal number into Go struct field Caps.desiredCapabilities.browserVersion of type string

The root cause might be found in class DriverData:

`public static void setupCapability(MutableCapabilities cap, String property, String value) {
        if(!property.equals(ARGUMENTS_PROPERTY)) {
            cap.setCapability(property, stringToPrimitive(value));
        } else {
            if (isClass(cap.getClass(), ChromeOptions.class)) {
                ((ChromeOptions) cap).addArguments(value.split(" "));
            } else if (isClass(cap.getClass(), FirefoxOptions.class)) {
                ((FirefoxOptions) cap).addArguments(value.split(" "));
            }
        }
    }`

If I change `cap.setCapability(property, stringToPrimitive(value));` to `cap.setCapability(property, value);` remote driver session is created successfully.

Checked on Selenoid versions 1.10.1, 1.10.5

**Comment by n-ton4** [comment]
Hi @epam-roman-iovlev could you get across the reason to use stringToPrimitive(value) instead of raw value. It would really help to get over the issue.

**Comment by RomanIovlev** [comment]
Will be fixed in 1.3.16. The reason is that in some cases Selenium required primitive values for example for boolean and for some numbers

**Comment by AlexeyGirin** [comment]
Будет в ин прогресс пока не влили пулл реквест
