### ISSUE TITLE
Создать jdi-light-mobile-android-template заново

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3343]
Текущая версия jdi-light-mobile-android-template явно не работоспособна.
Необходимо пересоздать этот шаблон с нуля.
Можно использовать https://github.com/jdi-testing/jdi-light/tree/master/jdi-light-mobile-tests в качетво исходного проекта - просто выкинуть оттуда всё лишнее

**Comment by pnatashap** [comment]
fixed
