### ISSUE TITLE
Vuetify: Search API Autocomplete does not show the list of search results

### ISSUE THREAD

**Issue by Liliya-web** [jdi-testing/jdi-light#3381]
Search API does not show any list of search results when some text is typed into the text field. The bug was found on 07/10/2021. It worked fine before.
Steps to reproduce:
1. Navigate to https://jdi-testing.github.io/jdi-light/vuetify -> autocompletes
2. Scroll to API Search Autocomplete.
3. Type "Test" in the text field of the autocomplete.
Expected result: The list with the search results is expanded on the page.
Actual result: There is no list of search results in the autocomplete.

Screenshot:
![image](https://user-images.githubusercontent.com/61730255/136333779-2d30f18c-7953-4a81-8fc5-cefe42e047cd.png)
Link to issue: #3036

**Comment by Youfka** [comment]
cannot reproduce, works for me now

**Comment by AlexeyGirin** [comment]
Not Repro
