### ISSUE TITLE
Test doesn't return web browser page to maximized in @After test

### ISSUE THREAD

**Issue by knadonenko** [jdi-testing/jdi-light#3444]
On third data parameter doesn't returned to maximized view. WebDriverFactory.getDriver().manage().window().maximize(); is called in AfterMethod but browser dos not returns to maximized
![image](https://user-images.githubusercontent.com/8589740/139833195-09c67a0d-a46a-47de-b761-003aaa6a2cb5.png)

**Comment by pnatashap** [comment]
Works fine for Win and doesn't work for Mac.
 We need to create a public function to maximize window, as we have in DriverData class:
`private static WebDriver maximizeScreen(WebDriver driver) {
        try {
            switch (getOs()) {
                case WIN:
                case LINUX:
                    driver.manage().window().maximize();
                    break;
                case MAC:
                    java.awt.Dimension screenSize = getDefaultToolkit().getScreenSize();
                    setBrowserSizeForMac(driver, (int) screenSize.getWidth(), (int) screenSize.getHeight());
                    break;
                default: break;
            }
            return driver;
        } catch (Exception ex) {
            throw exception(ex, "Failed to maximize window");
        }
    }`
