### ISSUE TITLE
Alerts page needs to be added to MaterialUI site

### ISSUE THREAD

**Issue by alexkashin90** [jdi-testing/jdi-light#3506]
There is no page for Alerts on https://jdi-testing.github.io/jdi-light/material/
For example of the page see: https://mui.com/components/alert/

**Comment by Youfka** [comment]
added alerts page without storybook page, might need to add later

**Comment by cold-flame** [comment]
Add commit to gh-pages-material branch
Need create PR to master

**Comment by AlexeyGirin** [comment]
Done.
