### ISSUE TITLE
Fix Codacy verification issues: empty catch

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3533]
Empty catch block.  should not be used.
vuetify-develop branch;
Codacu issues list:
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=25422683&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjM3NTQiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by NewerNaigil** [comment]
Decided to ignore exception issues and empty catch block.

**Comment by tsvetaevAlex** [comment]
emo ha been done
