### ISSUE TITLE
Publish new version to Maven

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3540]

**Comment by AndreySinelnikov** [comment]
[JDI Light](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light/1.3.19)
[JDI Light HTML](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light-html/1.3.19)
[JDI Light Bootstrap](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light-bootstrap/1.3.19)
[JDI BDD](https://mvnrepository.com/artifact/com.epam.jdi/jdi-bdd/1.3.19)
[JDI Applitools Eyes](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light-eyes/1.3.19)
[JDI Mobile](https://mvnrepository.com/artifact/com.epam.jdi/jdi-light-mobile/1.3.19)
