### ISSUE TITLE
Error in UIElement.command when browser is unfocused

### ISSUE THREAD

**Issue by obitkin** [jdi-testing/jdi-light#3573]
[Open io.github.epam.material.tests.inputs.DateTimePickersTests](https://github.com/jdi-testing/jdi-light/blob/2f53a4bdc8e4ab76567613bf5f15190e621788b6/jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/DateTimePickersTests.java) 

- **master_material_ui** branch
- **2f53a4bd** commit

1. Run DateTimePickersTests
2. While browser is starting tests(before 1-st test) focus on another window - IDEA: 
<img width="395" alt="Screenshot 2021-12-06 233120" src="https://user-images.githubusercontent.com/68860735/144917995-23f18728-8614-4bf1-a23c-6732cfc0195a.png">

3. `datePickerDialogTest` and `timePickerTest` are failed
4. Reason: _Enter_ from `confirm()` method has been sent into IDEA twice instead of browser because browser was unfocused. 
```
@JDIAction("Confirm changes in {name} and close")
public void confirm() {
    command("Enter");
}
```

<img width="403" alt="Screenshot 2021-12-06 233510" src="https://user-images.githubusercontent.com/68860735/144918758-3e933c7e-8724-425c-af03-1bd8cc6d8c5d.png">

`UIElement.command(String sequence)` doesn't works fine with unfocused browsers. For example, with tests that run in parallel on CI.

**Comment by GgStormer** [comment]
Issue is not reproducable.

**Comment by pnatashap** [comment]
Parallel execution is not a problem for command. 
But local actions can be a reason for many actions. 
Not a bug
