### ISSUE TITLE
[SPIKE] Explore possibility of using ListItem in elements which uses .MuiList-root

### ISSUE THREAD

**Issue by knadonenko** [jdi-testing/jdi-light#3651]
Bottom AppBar, Inset Divider, Router Breadcrumbs, Responsive Drawer, Mini Drawer, Permanent Drawer, Clipped Drawer, Menu, Dialog

(списки можно найти по ".MuiList-root")

**Comment by alexkashin90** [comment]
Bottom AppBar - на странице есть List, но к App Bar он отношения не имеет
Inset Divider -   на странице есть List, но к Inset Divide он отношения не имеет
Router Breadcrumbs - заимплементил в PR: https://github.com/jdi-testing/jdi-light/pull/3655
Responsive Drawer, Mini Drawer, Permanent Drawer, Clipped Drawer - беру в работу. Продолжу их пилить в ветке этого PR: https://github.com/jdi-testing/jdi-light/pull/3636
Menu - работает Владислав Прокопенко, PR - https://github.com/jdi-testing/jdi-light/pull/3653
Dialog - заимплементил в PR: https://github.com/jdi-testing/jdi-light/pull/3626
