### ISSUE TITLE
FIX Codacy Pattern: ConstantName QTY == 7

### ISSUE THREAD

**Issue by foria1405** [jdi-testing/jdi-light#3685]
Checks that constant names conform to a specified pattern.

Codacy Pattern:
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=24589299&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjI4NjUiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

List of Issues:
Related code pattern
ConstantName
Java

**Comment by tsvetaevAlex** [comment]
demo has been done
