### ISSUE TITLE
01/12 Material: shift right curly brace to the correct place

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3702]
source links:
https://github.com/checkstyle/checkstyle/issues/5945
https://github.com/checkstyle/checkstyle/issues/7519

--------------------✁ cut line --------------
Pattern: RightCurly;
List of issues [QTY ==1 ]
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=24589299&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjE3ODIiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by daarklight** [comment]
Resolved as a part of pull request (https://github.com/jdi-testing/jdi-light/pull/3708) covering task 3696.
