### ISSUE TITLE
01/12 vuetify-develop: Remove unused imports;

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3703]
Pattern:  UnusedImports;

List of issues[QTY == 9]
https://app.codacy.com/gh/jdi-testing/jdi-light/issues?bid=25422683&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjI4MzMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by switzerrrland** [comment]
Unused import already deleted in https://github.com/jdi-testing/jdi-light/commit/baecdf5ae288cfaaf59b8615648953a6540b88d2

**Comment by tsvetaevAlex** [comment]
Demo has been done
