### ISSUE TITLE
Vuetify: investigate failed tests

### ISSUE THREAD

**Issue by daarklight** [jdi-testing/jdi-light#3734]
Vuetify:
- check which test classes and separate tests inside these classes are failed;
- investigate the reasons of Vuetify tests failing.
Tasks to fix these failed tests are to be created later.

**Comment by stanislavdmitriev-epam** [comment]
To avoid exceptions in BeforeClass hook when pages lag it was decided to add unified waitCondition checking page.isOpened() in test classes

**Comment by daarklight** [comment]
- Failed test classes and separate tests were investigated.
- The reason of failing of most tests was found and fixed.
- Other failed tests are covered by tasks to fix them.
