### ISSUE TITLE
Vuetify: Select tests refactoring

### ISSUE THREAD

**Issue by Kratlis** [jdi-testing/jdi-light#3804]
### In Select:
- [x] remove wrapper methods `labelText` and `messageText`. Instead, use the code inside them

### In SelectTests:
- [x] combine one-line checks like `message`, `label` with other tests *(e. g. message -> custom select, label -> multiple)* or add select check there
- [x] add check to `readOnlyTest()`:
  ```java
  readonlySelect.expand();
  readonlySelect.is().collapsed();
   ```
- [x] Change `@BeforeClass` to `@BeforeMethod`
- [x] replace standardDenseSelect in `basicFunctionalityTest()` with customSelect
- [x] add test step for `iconTest`
- [x] add test step for `multipleSelectTest`
- [x] create test to check of selecting all in append select

### In SelectsPage:
- [x] change `leftIconSelect` to `prependedIconSelect`
- [x] add `appendAndPrependItemSelect` 

### In DropdownExpand:
- [x] add '}' for close method
- [x] remove unused libraries

**Comment by behhVenn** [comment]
related MR is merged, specified points in tasks are implemented into vuetify-develop
