### ISSUE TITLE
КриптоПро ЭЦП Browser plug-in. Ошибка загрузки плагина

### ISSUE THREAD

**Issue by podlesnyv** [jdi-testing/jdi-light#3830]
Добрый день!
Для выполнения теста подписания ЭП документа используется плагин КриптоПро.
Плагин загружается 
`    public static void setChromeOptions() {
        DriverData.CHROME_OPTIONS = cap -> {
            defaultChromeOptions(cap);
            cap.addExtensions(new File(mergePath(COMMON.projectPath, "src/test/resources/iifchhfnnmpdbibifmljnfjhpififfog_main.crx")));
        };
    }`
Выполняется подписание ЭП и следует ошибка:
![errEDS](https://user-images.githubusercontent.com/4812651/152834811-56008fbf-2460-4be0-82f8-b7b4142213c2.jpg)
Корректно начинает работать только после того как выключу включу плагин.
![fixed_errEDS](https://user-images.githubusercontent.com/4812651/152835384-0bc8b5e7-9b5d-460d-95ed-b3efda3feba1.jpg)
Если же заменяю родной драйвер JDI на свой
WebDriverFactory.useDriver(() -> initWD());
то плагин отрабатывает корректно.
Что еще заметил: два раза выполнял один и тот же тест(ничего не меняя) подписание ЭП документа.
1-й прогон тест проходит.
2-й прогон тест не проходит(плагин не отрабатывает)

**Comment by AlexeyGirin** [comment]
Логин в скайпе - vladimir_p56

**Comment by AlexeyGirin** [comment]
Дефолтные капабилитиз которые мы передаём - содержат флаг отключения плагинов.
Клиенту даны рекомендации как сделать что бы работало

**Comment by podlesnyv** [comment]
Добрый день. Не совсем понял что и где надо подкрутить чтобы работать с JDI-драйвером ?
успешно выполняются три сьюта и далее "Can't get WebDriver: chrome
![Can't get WebDriver](https://user-images.githubusercontent.com/4812651/153846711-9dbd4357-3cba-445e-9a43-b8e659676ee7.jpg)
"
