### ISSUE TITLE
Bug - Indeterminate checkbox does not have three statements

### ISSUE THREAD

**Issue by IvKardapolov** [jdi-testing/jdi-light#3883]
On https://mui.com/components/checkboxes/ Indeterminate described like a checkbox with three statements
![mui com_components_checkboxes_ (2)](https://user-images.githubusercontent.com/96478309/156738706-ce68e830-6543-45f2-854a-5ef129b470c8.png)![mui com_components_checkboxes_ (3)](https://user-images.githubusercontent.com/96478309/156738773-380e993c-17c7-45a5-b199-e5ede1189484.png)![mui com_components_checkboxes_ (4)](https://user-images.githubusercontent.com/96478309/156738836-c1838bac-04e3-4b73-b21c-15da7cc4d802.png)

On https://jdi-testing.github.io/jdi-light/material/checkboxes Indeterminate have only two statements
![jdi-testing github io_jdi-light_material_checkboxes](https://user-images.githubusercontent.com/96478309/156739099-38e169fe-b619-4a06-b9fd-449f9a8742d1.png)![jdi-testing github io_jdi-light_material_checkboxes (1)](https://user-images.githubusercontent.com/96478309/156739150-4ee40d42-a39f-4b2c-ac7a-17f6bacf49c9.png)

Steps:
Go to: https://jdi-testing.github.io/jdi-light/material/checkboxes
Click two times on checkbox with indeterminate label

Expected:
Three different statements on every click

**Comment by NewerNaigil** [comment]
bug fixed
