### ISSUE TITLE
BUG Material UI: There is no example for nested list on test page

### ISSUE THREAD

**Issue by rvasilyev** [jdi-testing/jdi-light#3922]
On [Material UI test page](https://jdi-testing.github.io/jdi-light/material/simple_list) there is no example for nested list, which probably should be implemented:
![NestedList](https://user-images.githubusercontent.com/51886279/159223220-4d7903e3-8e78-4243-97dd-01731085a865.JPG)

Steps:
Go to [Material UI test page](https://jdi-testing.github.io/jdi-light/material/simple_list)

Expected:
There is example for nested list among other types of lists on web page.

Actual:
There is no example for nested list among other types of lists on web page.

**Comment by NewerNaigil** [comment]
bug fixed
