### ISSUE TITLE
Vuetify: investigate and fix failed test in DialogTests

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#3931]
Several tests in DialogTests is failed:
- [x] `formDialogTest`
- [x] `fullscreenDialogTest`
- [x] `loaderDialogTest`
- [x] `nestingDialogTest`
- [x] `overflowedDialogTest`
- [x] `persistentDialogTest`
- [x] `scrollableDialogTest`
- [x] `transitionsDialogTest`
- [x] `withoutActivatorDialogTest`

It is required to investigate the reasons of failing and fix them.

**Comment by evgenii-liashenko** [comment]
All tests in DialogTests pass. I could not reproduce the failures. It is possible that they were caused by not executing clean and install maven phases for some of the following projects: JDI Light, JDI Light Html Elements, JDI Vuetify, Tests: JDI Vuetify.
