### ISSUE TITLE
Material UI: Write Javadoc for Button, FAB, Backdrop, Snackbar

### ISSUE THREAD

**Issue by Kratlis** [jdi-testing/jdi-light#3956]
Write Javadoc according to the tutorial in "Инструктаж для новичков". 

Elements for Javadoc:
- [x] Button
- [x] Floating Action Button
- [x] Backdrop
- [x] Snackbar

**Comment by evgenii-liashenko** [comment]
There is no Button implementation in the element packages of the framework, therefore there will be no Javadoc for it.
