### ISSUE TITLE
Material UI: Refactor Table classes and tests

### ISSUE THREAD

**Issue by IvKardapolov** [jdi-testing/jdi-light#3959]
- [ ] refactor with Jtable annotations for Sorting and selecting table, Spanning Table, Virtualized table 
- [ ] refactor Virtualized table test to check element for visibility while scrolling
- [ ] make checkboxes part of Sorting and selecting Table
- [ ] write Javadoc

**Comment by Kchebulaev** [comment]
blocked by [3984](https://github.com/jdi-testing/jdi-light/issues/3984)

**Comment by Kchebulaev** [comment]
was done in scope of fixing table tests
