### ISSUE TITLE
Return count is 3, max allowed for non-void methods/lambdas is 2.

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3970]
Return count is 3, max allowed for non-void methods/lambdas is 2.
Issues QTY == 1
issue [Details](https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=9172678)

**Comment by NewerNaigil** [comment]
issue fixed

**Comment by tsvetaevAlex** [comment]
fixed iby commiy as a part of another task.
