### ISSUE TITLE
В целом не понятно, почему мои классы, написанные в https://github.com/jdi-templates/jdi-light-testng-template, не работают, а в https://github.com/jdi-testing/jdi-light - работают.

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3971]
Необходимо исследовать следующий фидбэк от Ксении Ковалёвой:

"В целом не понятно, почему мои классы, написанные в https://github.com/jdi-templates/jdi-light-testng-template, не работают, а в https://github.com/jdi-testing/jdi-light - работают."

**Comment by GgStormer** [comment]
Couldn't access rights for pushes;(
Thanks to Natalia Pozhidaeva for applying my patch with fixes and also making some more refactoring for this branch.

**Comment by pnatashap** [comment]
jdi-light-testng-template какое-то время был не рабочим, я его починила 5 апреля

**Comment by pnatashap** [comment]
Fixed
