### ISSUE TITLE
BUG Material UI: There is a lack of some types of steps for stepper on test page

### ISSUE THREAD

**Issue by rvasilyev** [jdi-testing/jdi-light#3972]
There are some step types missing on test page:
- optional step
![optional_step](https://user-images.githubusercontent.com/51886279/161540775-9145e104-b0dc-49f9-9dcb-f66a148d8279.JPG)
- error step
![error_step](https://user-images.githubusercontent.com/51886279/161540808-15104a67-a84e-40a3-9bb8-c0003ff63d49.JPG)
- editable step
![editable_step](https://user-images.githubusercontent.com/51886279/161540831-45237715-f437-4d43-b68e-dec3223ed33f.JPG)
- disabled completed step
![disabled_completed_step](https://user-images.githubusercontent.com/51886279/161540854-e4e0ca89-f10b-41e5-9a19-51ea30f7d77a.JPG)

Steps:
1. Go to [Material UI test page](https://jdi-testing.github.io/jdi-light/material/)
2. Open steppers

Expected:
There are all possible types of steps for steppers on web page.

Actual:
There are some missing types of steps: optional step, error step, editable step and disabled completed step - on web page.

**Comment by AlexeyGirin** [comment]
Not a bug
