### ISSUE TITLE
Material UI: Verify Bug 3972 and correct tests for Stepper

### ISSUE THREAD

**Issue by Kratlis** [jdi-testing/jdi-light#3979]
Currently, there are some missing examples on the test site (BUG #3972).

Please check that the bug is fixed before taking the task.

- [x] add checks into StepperTests class for:
- optional step
- error step
- editable step
- disabled completed step

Resolve TODO for Step class and correct StepAssert class if needed.

- [x] fix StaleElementReferenceException in verticalStepperTest

**Comment by BestNastos** [comment]
Issue [#3972](https://github.com/jdi-testing/jdi-light/issues/3972) was closed as "not a bug", so no new checks are required for StepperTests class
