### ISSUE TITLE
Improve HasLabel interface

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-light#4060]
Add method to check is label exists. If we throw exception if there is no label, we need to have ability to check if it exists

- [x] add method hasLabel to HasLabel interface
- [x] create custom implementations if it´s required in any class that implements HasLabel
- [x] add checks to tests there label exists and do not exists

**Comment by OlgaPoddubnaia** [comment]
https://github.com/jdi-testing/jdi-light/pull/4072

**Comment by OlgaPoddubnaia** [comment]
https://github.com/jdi-testing/jdi-light/pull/4108
