### ISSUE TITLE
MUITable refactoring

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-light#4069]
It should be possible to work with table without annotations using default locators.
 Now annotation JMUITable is required and initialization exception occurs in case of missing

**Comment by AlexeyGirin** [comment]
ПРОВЕРИТЬ НАЛИЧИЕ И КОРРЕКТНОСТЬ ДОКУМЕНТАЦИИ

**Comment by AlexeyGirin** [comment]
Done.
