### ISSUE TITLE
Review everything/Merge Material UI to Main

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4079]
Review everything/Merge Material UI to Main

- [x] Checkbox
- [x] Chips
- [x] Tooltip
- [x] Container
- [x] Avatar
- [x] Divider
- [x] Card
- [x] Radio
- [x] App Bar
- [x] Transitions
- [x] Material Icons
- [x] Icons
- [x] Floating Action Button
- [x] Hidden
- [x] Stepper
- [x] Slider
- [x] Tabs
- [x] Table
- [x] Typography
- [x] Badge
- [x] Snackbars
- [x] Backdrop
- [x] Dialog
- [x] Date / Time pickers
- [x] Select
- [x] Switch
- [x] Button
- [x] ButtonGroup
- [x] Grid
- [x] Drawer
- [x] Breadcrumbs
- [x] Bottom Navigation
- [x] Paper
- [x] Accordion
- [x] Portal - removed
- [x] Textarea Autosize
- [x] Popover
- [x] Modal
- [x] Popper
- [x] Progress
- [x] Link
- [x] Menus
- [x] Lists
    - [x] List Items
- [x] Transfer List
- [x] Text Field
- [x] Alert

**Comment by pnatashap** [comment]
material-ui merged to master.
more then 2000 commits
