### ISSUE TITLE
Tooltips page is not testable and not fully reflecting a tooltip functionality

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-light#4091]
All tooltips have the same text, so impossible to distinguish them.

- [x] change tooltip to "Tooltip for {button text}"
- [x] add elements with tooltips for color and alignment tests

<img width="881" alt="image" src="https://user-images.githubusercontent.com/57947006/182097598-0e73ebab-9058-46d2-8f9d-f2af1428ca00.png">

**Comment by toronto22** [comment]
@pnatashap The task is related to a website issue - tooltips have the same text- so I think we cannot fix it in our project.
