### ISSUE TITLE
Tooltips tests refactoring

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-light#4092]
TooltipsPage has a link to the first tooltip only, which is not correct, as all buttons have different tooltips. There is a bug in site, that the text should be different to be testable

- [ ] create a new test to display all tooltips in one and check them

**Comment by toronto22** [comment]
@pnatashap The task is related to a website issue - tooltips have the same text- so I think we cannot fix it in our project.

**Comment by pnatashap** [comment]
> @pnatashap The task is related to a website issue - tooltips have the same text- so I think we cannot fix it in our project.

In any case they display different tooltips, so it's not related to site.
@toronto22  And if you doesn't work on the task, please delete yourself from Assigners
