### ISSUE TITLE
Vuetify: add support of Mandatory property in Slide group

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4120]
Can't see related tests and element in Vuetify.
additionally need to update test site. It doesn't have related information.
from https://vuetifyjs.com/en/components/slide-groups/#custom-icons : "the mandatory prop will make the slide group require at least 1 item must be selected"

**Comment by OlgaPoddubnaia** [comment]
helpful material https://jdi-family.atlassian.net/wiki/spaces/JDIL/pages/47579246/How+to+update+a+test+site+Vuetify

**Comment by OlgaPoddubnaia** [comment]
the bug for adding the mandatory slide 
https://github.com/jdi-testing/jdi-light/issues/4141
