### ISSUE TITLE
Implement tests related with the rest of  v-slide-group properties

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4128]
Based on https://vuetifyjs.com/en/components/slide-groups/#usage need to add checks related with v-slide-group properties:

- [ ] dark
- [ ] light
- [ ] max
- [ ] mobile-breakpoint
- [ ] show-arrows
- [ ] tag
- [ ] value
- [ ] value-comparator

**Comment by MayaElf** [comment]
duplicate of #4298 
so CLOSED 05 01 23
