### ISSUE TITLE
Review current v-slide-group test and refactor it's properties

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4136]
Based on https://vuetifyjs.com/en/components/slide-groups/#usage
Some related tests already designed in Vuetify(in this case need to comment code which is used these properties). In some cases new tests should be added.
Known properties:
#active-class
#center-active
#mandatory
#multiple
#next-icon
#prev-icon

**Comment by MayaElf** [comment]
duplicates #4298
so this one is CLOSED
