### ISSUE TITLE
Implement checks related with v-slide-group events

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4137]
Based on https://vuetifyjs.com/en/components/slide-groups/#usage need to update existing code to cover v-slide-group events:
#change
#click:next
#click:prev

**Comment by MayaElf** [comment]
Duplicate of #4298 So CLOSED 04 01 23

**Comment by MayaElf** [comment]
Duplicate of #4298 So CLOSED 04 01 23
