### ISSUE TITLE
Add tests for features of element "badge" on a test-site

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4163]
Add tests for features of element "badge" on a test-site - combine them in tests

- [x] bordered (y/n)
- [x] inline(y/n)
- [x] tile (y/n)
- [x] Bottom (y/n)
- [x] Left (y/n)
- [x] Overlap (y/n)

**Comment by annav00** [comment]
Test for 'tile' will be added after the [issue 4162](https://github.com/jdi-testing/jdi-light/issues/4162)  is closed.
