### ISSUE TITLE
Add and refactor tests for features of element "appbars" on a test-site

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4170]
The class shouldn't contain elements specific to the test site.
Appbar extends Toolbar hat is why it is necessary to close [issue 4168](https://github.com/jdi-testing/jdi-light/issues/4168) before starting this one.

Add and refactor tests for features of element "appbars" on a test-site:

- [x] elevation (0-24)
- [x] color(red/orange/green /yellow/blue/purple)
- [x] outlined (y/n)
- [x] flat (y/n)
- [x] rounded (y/n)
- [x] shaped (y/n)
 -
- [x] collapse (y/n)
- [x] collapse-on-scroll (y/n)
- [x] dense(y/n)
- [x] elevate-on-scroll (y/n)
- [x] hide-on-scroll (y/n)
- [x] src (link)
- [x] prominent (y/n)

Weren't checked:

short (y/n)
scroll-threshold (0-n)
inverted-scroll (y/n) - no such property in API

Before taking this issue,  make sure that the necessary elements are added to the test-site ([issue 4169](https://github.com/jdi-testing/jdi-light/issues/4169))

**Comment by MayaElf** [comment]
#4168 DONE so the task is unblocked.
