### ISSUE TITLE
Review a following vuetify feature: radiobuttons

### ISSUE THREAD

**Issue by Olesya24** [jdi-testing/jdi-light#4222]
- [x] Review radiobuttons - fill matrix
- [x] Add tasks for radiobuttons - test-site #4354 
- [x] Add tasks for radiobuttons tests #4355

**Comment by Olesya24** [comment]
- [ ] Review radiobuttons - fill matrix
- [ ] Add tasks for radiobuttons - test-site
- [ ]  Add tasks for radiobuttons tests
- [ ] Refactor radiobuttons tests

**Comment by MayaElf** [comment]
@omega790 Elena, please, review

**Comment by MayaElf** [comment]
reviewed
