### ISSUE TITLE
Баг на тестовом сайте - Stepper

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4230]
Детали от Ансара тут

**Comment by 1138th** [comment]
### Case 1, completed steps
1. Go to https://jdi-testing.github.io/jdi-light/material/steppers;
2. Section `Non-linear stepper`, click `Complete Step` two times – first two steps **are enabled and completed**, user is currently on Step#3;
![image](https://user-images.githubusercontent.com/14041995/187832056-d8cb50a6-bace-4c25-a8d7-a0f542bd17df.png)
4. Press `Back` – user is currently on Step#2, step 2 is **enabled** and **not completed**;
![image](https://user-images.githubusercontent.com/14041995/187832252-3f17212c-edca-47cc-9552-34be0b78dbb5.png)
Expected: step 2 is **enabled** and **completed**
6. Press `Back` again – user is currently on Step#1, step 1 is **enabled** and **not complete**;
![image](https://user-images.githubusercontent.com/14041995/187833222-faac695a-ff34-4869-80f6-e8a51cb28e18.png)
step 2 is **disabled** and **not completed**
![image](https://user-images.githubusercontent.com/14041995/187832559-285cb424-6437-490f-b7ac-dae1471044be.png)
Expected: steps 1 and 2 are **enabled** and **completed**

### Case 2, incomplete steps
1. Go to https://jdi-testing.github.io/jdi-light/material/steppers;
2.  Section `Non-linear stepper`, click `Next`;
3. User is on Step#2 – step 1 is **enabled** and **completed**
![image](https://user-images.githubusercontent.com/14041995/187833629-58469a0a-e54a-48cb-be35-f83c690c6103.png)
Expected: step 1 is **disabled** and **not completed**

**Comment by vklonin** [comment]
Was fixed on 5th of Sep 2022
https://github.com/jdi-testing/test-site/commit/8d2935d5dfa5120e7624db4333495b9e53688be7
