### ISSUE TITLE
Check browser resolution in a headless mode

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4249]
Уточнить какое разрешение у браузера, если мы попросили headless режим и попросили максимизировать окно в test.properties. насколько я помню реализацию, то оно не будет максимизироваться. скорее всего исправляется аргументами запуска драйвера. 

Что сделать: Проверить как в хэдлесс режиме работает максимайз окна. Видимо - не работает.
Как должно быть - либо в аргументах добавить параметр старта в максимайзе, либо - указывать явно указывать изменение размера к конкретным величинам.

**Comment by pnatashap** [comment]
Разрешение разное, даже при наличии видеокарты, возможно берет максимум: у меня без headless разрешение было 3600 на 1882, в headless 3600 на 2338
В целом рекомендуется указывать, какое разрешение нужно, если это критично. На серверах, где GUI нет вообще, не понятно, что будет
