### ISSUE TITLE
Update test-site: element "slider"

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4250]
Update test-site: element "slider"

- [x] background-color(name of material color or css color)
- [x] theme (dark)
- [x] dense (y/n)
- [x] error-count (0-n)
- [x] height (0-n)
- [x] hide-details (y/n)
- [x] hide-spin-buttons (y/n)
- [x] loader-height (0-n)
- [x] loading (y/n/color)
- [x] success (y/n)
- [x] success-messages (string)
- [x] validate-on-blur (y/n) (01.11.22 works only after putting focus(=click) on slider and then click outside)

**Comment by MayaElf** [comment]
Discussed on sync 01.11.22
validate-on-blur 01.11.22 works only after putting focus(=click) on slider and then click outside
agreed  to use as it is and create bug and fix it later
