### ISSUE TITLE
Create abstract class BasicSlider

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4259]
It is necessary to create:
- [x] abstract class BasicSlider
- [x] BasicSliderAssert for BasicSlider

On its basis, such elements as [Slider](https://vuetifyjs.com/en/components/sliders/) and [Rang Slider](https://vuetifyjs.com/en/components/range-sliders/#min-and-max) will be extended.

The following features should be provided:
- [x] append-icon (y/n)
- [x] color (name of material color or css color) 
- [x] background-color (name of material color or css color)
- [x] theme (dark/light)
- [x] dense (y/n)
- [x] disabled (y/n)
- [x] error (y/n)
- [ ] error-count (0-n)
- [x] error-messages (string)
- [x] height (0-n)
- [x] hide-details (y/n)
- [x] hide-spin-buttons (y/n)
- [ ] hint (string)
- [x] inverse-label (y/n) 
- [x] label (string)
- [ ] loader-height (0-n)
- [ ] loading (y/n/color)
- [x] max (0-n)
- [ ] messages (sting)
- [x] min (0-n)
- [ ] persistent-hint (y/n)
- [x] prepend-icon (y/n)
- [x] readonly (y/n)
- [ ] rules (array)
- [x] step (0-n)
- [x] success (y/n) 
- [x] success-messages (string)  
- [ ] tick-labels (array) 
- [ ] tick-size (0-n) 
- [ ] ticks (y/n/”always”) 
- [ ] track-color (color) 
- [ ] track-fill-color (color) 
- [x] validate-on-blur (y/n) 
- [x] vertical (y/n)

When executing the task, you can take as an example the current implementation of the Bar elements, which uses the abstract class BasicBar.

**Comment by MayaElf** [comment]
16 12 22 it was agreed with Vladimir Klonin not to implement BasicSlider. So the task is closed.
