### ISSUE TITLE
Update test-site: element switch

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4276]
Update test-site: element switch:

- [x] append-icon (y/n)
- [x] background-color (name of material color or css color)
- [x] theme (dark)
- [x] dense (y/n)
- [x] error (y/n)
- [x] error-count (0-n)
- [x] error-messages (string)
- [x] hint (string)
- [x] messages (sting)
- [x] persistent-hint (y/n)
- [x] prepend-icon (y/n)
- [x] readonly (y/n)
- [x] ripple (y/n)
- [x] success (y/n) 
- [x] success-messages (string)

**Comment by MayaElf** [comment]
reviewed
