### ISSUE TITLE
Add and refactor tests for features of element select on a test-site

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4287]
Add and refactor tests for features of element select on a test-site:

- [ ] append-icon (icon)
- [ ] append-outer-icon (y/n)
- [ ] autofocus (y/n)
- [ ] background-color (name of material color or css color)
- [ ] chips (y/n)
- [ ] clear-icon (icon)
- [ ] theme (dark/light)
- [ ] deletable-chips (y/n)
- [ ] dense (y/n)
- [ ] disable-lookup (y/n)
- [ ] error-count (number)
- [ ] filled (y/n)
- [ ] flat (y/n)
- [ ] full-width (y/n)
- [ ] height (0-n)
- [ ] hide-details (y/n)
- [ ] hide-selected (y/n)
- [ ] items (array)
- [ ] loader-height (0-n)
- [ ] loading (y/n) 
- [ ] messages (string)
- [ ] no-data-text (string)
- [ ] open-on-clear (y/n)
- [ ] outlined (y/n)
- [ ] persistent-hint (y/n)
- [ ] persistent-placeholder (y/n)
- [ ] placeholder (string)
- [ ] prefix (y/n)
- [ ] prepend-inner-icon (icon)
- [ ] reverse (y/n)
- [ ] rounded (y/n) 
- [ ] shaped (y/n) 
- [ ] single-line (y/n) 
- [ ] small-chips (y/n) 
- [ ] solo (y/n) 
- [ ] solo-inverted (y/n) 
- [ ] suffix (y/n) 
- [ ] validate-on-blur (y/n)

**Comment by RoninED** [comment]
"clear-icon: exist in VariousAttributesSelect

**Comment by RoninED** [comment]
"chips", "filled", "outlined", "single-line" in LightSelect

"autofocus", "items ", "deletable-chips', "disable-lookup", "error-count", "flat", "full-width", "height" "hide-selected", "loader-height", "loading". "messages", "open-on-clear", "no-data-text", "persistent-hint", "persistent-placeholder", "placeholder", "prefix", "reverse', "rounded", "shaped", "small-chips", "solo-inverted". "suffix", "validate-on-blur", "dark" in VariousAttributesSelect

"dense", "solo" in Dense select

"hide-details" in IconsSelect

**Comment by MayaElf** [comment]
element 'Select' was reviewed by Natalia Pozhidaeva, no additional tasks were created
