### ISSUE TITLE
Update test-site: element "textfield"

### ISSUE THREAD

**Issue by obitkin** [jdi-testing/jdi-light#4304]
- [x] autofocus (y/n)
- [x] background-color (color)
- [x] theme (dark)
- [x] error-count (number)
- [x] error-messages (string)
- [x] flat (y/n)
- [x] height (number)
- [x] loader-height (number)
- [x] loading (y/n)
- [x] persistent-placeholder (y/n)
- [x] reverse (y/n)
- [x] success (y/n)
- [x] success-messages (string)
- [x] validate-on-blur (y/n)

**Comment by MayaElf** [comment]
reviewed 25 10 22. Items already implemented were deleted from the list of tasks.
