### ISSUE TITLE
Добавить Shadow Element

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4368]
В HTML5 элементы добавить Shadow element проперть
(детали у Наташи Пожидаевой)

Смысл элемента
Есть общее дерево, некоторые элементы не видны, он переходит в альтернативное дерево на той же странице.
Нужно создать анотацию Шадоу - которую можно повесить на любой элемент
Когда строим и получаем на элемент - и находим шэдоу - надо стопануться и он будет корневым элементом.
1. Логика получения шэдой элемента с аннотацией шэдой будет другая
2. Дочерние от шэдой - должны считать шэдоу рутом

Для таких элементов есть отдельный дом
Шэдой элемент - это рут страницы. Всё от него - считает этот элемент рутом. Каскадная инициализация должна останавливаться.

DoD:
1. Появится новая аннотация ( `@ShadowElement` )
2. Изменится процесс каскадной иницилизации
3. Создать страничку с такими элементами (хотя бы HTML5)
4. [инвестигация] Узнать могут ли быть остальные элементы в других библиотеках - шэдоу

**Comment by pnatashap** [comment]
https://embed.plnkr.co/fVIYs97WzjwjYnuDE75u/ - неплохой пример, как вставить на сайт
