### ISSUE TITLE
Обновить версию JDI в примере - https://github.com/jdi-examples/jdi-introduction. И включить его в CI/CD

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4389]
В данный момент в https://github.com/jdi-examples/jdi-introduction используется версия JDI 1.0.65
Нужно обновить до 1.4.4 и включить его в CI/CD

**Comment by pnatashap** [comment]
Updated to RELEASE version, so can be run to check after new release
