### ISSUE TITLE
Добавление параметра add-opens для запуска на JDK16+ по нашим шаблонам

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4391]
Для работы JDI на JDK16+ необходимо добавить аргумент запуска --add-opens java.base/java.lang=ALL-UNNAMED (нужен на самом деле для работы AspectJ https://htmlpreview.github.io/?https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/README-197.html ) 
В нашем случае аргумент должен добавляться в аргументы запуска maven-surefire-plugin
!!! Небольшая сложность заключается в том, что такого параметра в JDK 8 не было, поэтому просто добавить для всех не получается

Поэтому по всем примерам (для Cucumber значение параметра ниже) нужно внести изменения как в этом PR
https://github.com/jdi-testing/jdi-light/pull/4388/files#
1. в pom.xml добавить параметр в properties
```
 <!-- - - add-opens java.base/java.lang=ALL-UNNAMED is needed for JDK 16+ -->
        <aspectj.args></aspectj.args>
```
2. в аргументы запуска maven-surefire-plugin (до javaagent)
```
<argLine>
                        ${aspectj.args}
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
</argLine>
```
3.  в файл запуска тестов (обычно main.yml) добавить jdk 16, 17 и скопировать шаги для установки параметра (как в PR)

Для Cucumber значение параметров (хранится в SUREFIRE_ARGS_BDD)
`--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED  --add-opens=java.desktop/java.awt.font=ALL-UNNAMED`

Убедится, что тесты запустятся на 16 и 17 jdk при создании PR и убедится, что они прошли

**Comment by pnatashap** [comment]
Обновили все примеры, шаблоны и тесты в самом JDI
