### ISSUE TITLE
Update Test site: Dialogs

### ISSUE THREAD

**Issue by Liliya-web** [jdi-testing/jdi-light#4418]
Add the following features:

- [x] disabled (y)

**Comment by Liliya-web** [comment]
open/close delay doesn/t work for the moment. Please add the functionality when the bug is fixed in the Vuetify framework: https://github.com/vuetifyjs/vuetify/issues/15938

**Comment by MayaElf** [comment]
15 11 22 agreed to delete:
1) no-click-animation
2) open-delay
3) close-delay
