### ISSUE TITLE
Refactor Form element part 1 (service functions)

### ISSUE THREAD

**Issue by Liliya-web** [jdi-testing/jdi-light#4547]
The Form element extends JDILight.Form element. There are a lot of methods for JDILight.Form, and none of the methods were overridden for Vuetify.Form. It wasn’t checked in the tests for Vuetify.Form element that all these JDILight methods are working. It should be checked, and if not working, it should be overridden. If none of the methods is working, there shouldn’t be that inheritance;
Implement the following methods (from JDI Light Form):
- [ ] public String getAction(Field field, Object element, Object parent)
- [ ] public Form<T> setPageObject(Object obj)
- [ ] public List<Field> allFields()
- [ ] public List<Field> allFields(Object obj)
- [ ] protected List<String> verify(MapArray<String, String> map)
- [ ] public List<String> verify(T entity)
- [ ] public void check(MapArray<String, String> map)
- [ ] public void check(T entity)
- [ ] public boolean isDisplayed()
- [ ] public boolean isValid()

**Comment by MayaElf** [comment]
**11.01.23 Agreed to close and implement abstract class**
