### ISSUE TITLE
Enable and refactor disabledSliderTest in order to be less flaky on CI

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4585]
Enable and refactor test in order to be less flaky on CI

- [ ] refactor disabledSliderTest

**Comment by Liliya-web** [comment]
Fixed in https://github.com/jdi-testing/jdi-light/pull/4670

**Comment by MayaElf** [comment]
Fixed in https://github.com/jdi-testing/jdi-light/pull/4670 So this task is closed
