### ISSUE TITLE
Refactor Form element part 2 (press button and submit actions)

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4589]
**11.01.23 Agreed to close and implement abstract class**

The Form element extends JDILight.Form element. There are a lot of methods for JDILight.Form, and none of the methods were overridden for Vuetify.Form. It wasn’t checked in the tests for Vuetify.Form element that all these JDILight methods are working. It should be checked, and if not working, it should be overridden.

Implement the following methods (from JDI Light Form):
- [ ] public void pressButton(String buttonName)
- [ ] public void submit(String text)
- [ ] public void submit(String text, String buttonName)
- [ ] public void submit()
- [ ] public void submit(T entity)
- [ ] public void submit(T entity, String buttonName)
- [ ] protected void submit(MapArray<String, String> objStrings, String name)
- [ ] public void submit(MapArray<String, String> objStrings)

**Comment by MayaElf** [comment]
**11.01.23 Agreed to close and implement abstract class**
