### ISSUE TITLE
Refactor Form element part 3 (other actions with buttons)

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4590]
**11.01.23 Agreed to close and implement abstract class**

The Form element extends JDILight.Form element. There are a lot of methods for JDILight.Form, and none of the methods were overridden for Vuetify.Form. It wasn’t checked in the tests for Vuetify.Form element that all these JDILight methods are working. It should be checked, and if not working, it should be overridden. If none of the methods is working, there shouldn’t be that inheritance;

Implement the following methods (from JDI Light Form):

- [ ] public void login(T entity)
- [ ] public void login()
- [ ] public void loginAs(T entity)
- [ ] public void send(T entity)
- [ ] public void send()
- [ ] public void add(T entity)
- [ ] public void publish(T entity)
- [ ] public void save(T entity)
- [ ] public void update(T entity)
- [ ] public void cancel(T entity)
- [ ] public void close(T entity)
- [ ] public void back(T entity)
- [ ] public void select(T entity)
- [ ] public void next(T entity)
- [ ] public void search(T entity)
- [ ] public void create(T entity)

**Comment by MayaElf** [comment]
**11.01.23 Agreed to close and implement abstract class**
