### ISSUE TITLE
Refactor Form element part 4 (fill)

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4591]
The Form element extends JDILight.Form element. There are a lot of methods for JDILight.Form, and none of the methods were overridden for Vuetify.Form. It wasn’t checked in the tests for Vuetify.Form element that all these JDILight methods are working. It should be checked, and if not working, it should be overridden. If none of the methods is working, there shouldn’t be that inheritance;
Implement the following methods (from JDI Light Form):
- [ ] public void fillAction(Field field, Object element, Object parent, String setValue)
- [ ] public void fill(MapArray<String, String> map)
- [ ] public void fill(T entity)

**Comment by MayaElf** [comment]
**11.01.23 Agreed to close and implement abstract class**
