### ISSUE TITLE
Add SauceLabs properties in file

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#464]
https://github.com/jdi-testing/jdi-light/issues/27
Place SauceLabs settings in property file
Create class SauceLabsUtils и добавить туда все методы для работы SauceLabs
https://github.com/jdi-templates/jdi-light-saucelabs/blob/master/src/test/java/org/mytests/tests/TestsInit.java

**Comment by AlexeyGirin** [comment]
Closed since task was discontinued
