### ISSUE TITLE
Documentation for Vuetify element: Select

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4651]

**Comment by marsoloGit** [comment]
The task should go to the backlog as it is not ready for being done yet. 

According to the Vuetify traceabilty matrix the tests for the elements to be documented as part of this tasks are not ready yet:
https://jdi-family.atlassian.net/wiki/spaces/JDIL/pages/49020933/Vuetify+review+traceability+matrix
