### ISSUE TITLE
Documentation for Vuetify element: Text

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4655]

**Comment by AlexeyGirin** [comment]
Это утилитный элемент - для него документацию создавать не надо

**Comment by AlexeyGirin** [comment]
Но нужно перенести этот утилитарный элемент в отдельный пакет - утилит

**Comment by prudei-core** [comment]
@AlexeyGirin Привет, а можно поподробнее что надо сделать?
