### ISSUE TITLE
Refactor vuetify data-iterators tests leftovers

### ISSUE THREAD

**Issue by Liliya-web** [jdi-testing/jdi-light#4706]
Should be implement after merge of #4705 

To test:
- [x] No data text
- [x] No results text
- [x] Loading + Loading text
- [x] Locators for DataIterator elements on the page must point to elements with class v-data-iterator
- [x] Remove extents DataTable, as it is not a table at all (check DataIterator with checkboxes)
- [x] Remove collapse and expand methods, as it is not a common functionality
- [x] REVIEW ALL METHODS and keep only functions that are COMMON for all

**Comment by pnatashap** [comment]
All is fixed
