### ISSUE TITLE
Refactor tests: calendar leftovers

### ISSUE THREAD

**Issue by MayaElf** [jdi-testing/jdi-light#4737]
Please, investigate possibilities to test:

- [ ] control color
- [ ] event color
- [x] event ripple
- [x] get weekdays
- [x] interval width (min, h)

**Comment by sergei820** [comment]
control color - not related to calendar
event color - not testable (events and their colors changes every time when page loads)

calendarEventRippleTest() done
checkCalendarIntervalWidth() done
calendarWeekdaysTest() done
darkCalendarTest() fixed

**Comment by MayaElf** [comment]
was merged by Natalia Pozhidaeva
