### ISSUE TITLE
Refactor Window

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-light#4762]
Now Window is implemented as a Card, but it is another element.

Window is element with class v-window, have no actions, only container and items and prev and next buttons.

<div class="v-window v-item-group theme--light v-window--show-arrows-on-hover">
 <div class="v-window__container" style="">
   <div class="v-window-item" style="display: none;"></div>
   <div class="v-window-item" style="display: none;"></div>
   <div class="v-window-item v-window-item--active"></div>
   <div class="v-window__prev"></div>
 </div>

**Comment by pnatashap** [comment]
@ilya1032 what is the progress for the task?

**Comment by ilya1032** [comment]
@pnatashap almost done, some problems with JList/List initialization which prevents stable test execution

**Comment by pnatashap** [comment]
Implementation was totally wrong, fixed by myself (not all, test must be improved later)
