### ISSUE TITLE
Card element issues

### ISSUE THREAD

**Issue by antonfilichkin** [jdi-testing/jdi-light#4795]
- [ ] Remove `getMaxWidth()` and `getMaxHeight()` methods and related asserts as they are the same as default methods provided via interfaces
- [ ] Update documentation

**Comment by pnatashap** [comment]
Two items were removed, as progress bar is a legal part of Card to display loading and click on center is default. In case of required for special click, we need to get required part of the card and click on it.

**Comment by pnatashap** [comment]
Documentation is updated now, methods are also usefull.
Closing as no action required
