### ISSUE TITLE
Check if the simple template idi light mobile is working correctly

### ISSUE THREAD

**Issue by vklonin** [jdi-testing/jdi-light#4803]
Check if the simple template idi light mobile is working correctly if pulled out from repo and acted according to readme.md
repository:
https://github.com/jdi-templates/jdi-light-mobile-android-template.git
[setup-template] branch

**Comment by shoggy** [comment]
<img width="597" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/13015572/233377360-a977288b-b561-412f-a38b-f1630d7440db.png">
