### ISSUE TITLE
Впилить log4j обратно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4811]
Были договорённость с Наташей - сделать отдельную версию
Версию с лог4ж и без. Версия с лог4ж будет наследовать версию БЕЗ

**Comment by pnatashap** [comment]
со следующей версии 1.5.0 будет пакет jdi-light-core и jdi-light, jdi-light - это jdi-light-core с log4j 
для внешних пользователей ничего не изменится кроме как можно удалить зависимость на логгер
