### ISSUE TITLE
Implement Angular element: Button

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4838]
Проверить текущую имплемпентацию элемента на соответствие нашим принципам.
Принципы: https://github.com/jdi-testing/jdi-light/blob/master/Documents/element_design.md

В случае, если имплементация не соответсвует принципам - привести в соответствие

**Comment by spbqaru** [comment]
https://github.com/jdi-testing/jdi-light/pull/5407
