### ISSUE TITLE
[Bug] Jdi-light is not compatible with a new versions of chromedriver

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-light#4898]
**Steps:**

1. install the latest version of chrome (>=112.0.5615.49) 

1. launch any jdi tests with default settings

1. check the results

**Actual Result:**

- tests were failed with error:

  > WARNING: Invalid Status code=403 text=Forbidden chrome selenium

**Expected Result:**

- Browser was correctly open and tests are green

**Comment by pnatashap** [comment]
By default the latest chrome driver is used, so the latest Chrome browser should be installed.
If previous version should be used, then there is a parameter in test.properties file `driver.version=112` (for 112 version driver, only the major number should be written)
