### ISSUE TITLE
Update testsite: autocomplete element

### ISSUE THREAD

**Issue by alla-blinkova** [jdi-testing/jdi-light#4905]
At the moment the following features are not presented on angular testsite for element AUTOCOMPLETE:
test-site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/autocomplete/overview

- [x] autoSelectActiveOption: boolean (true)
- [x] disableRipple: boolean (true)
- [x] hideSingleSelectionIndicator: boolean (true)
- [x] matAutocompleteDisabled: boolean (true)
- [x] panelWidth: string | number
- [x] position: 'auto' | 'above' | 'below'
- [x] plain input autocomplete

**Comment by MayaElf** [comment]
DONE, merged
