### ISSUE TITLE
Update test site: Form field element

### ISSUE THREAD

**Issue by FursovaKate** [jdi-testing/jdi-light#4907]
At the moment the following features are not presented on angular test site for element Form field:
test-site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/form-field/api

Form Field control:
- [x] disabled: boolean
- [x] subscriptSizing: 'fixed'
- [x] subscriptSizing: 'dynamic'

We would also need to change the way we work with hints:

- [x] align: 'start'
- [x] align: 'end'

**Comment by MayaElf** [comment]
DONE, merged
