### ISSUE TITLE
Update test site: Paginator element

### ISSUE THREAD

**Issue by FursovaKate** [jdi-testing/jdi-light#4925]
At the moment the following features are not presented on angular test site for element Paginator:
test-site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/paginator/api

- [x] firstPageLabel: string
- [x] lastPageLabel: string
- [x] color: ThemePalette
- [x] disabled: boolean
- [x] hidePageSize: boolean.
- [x] showFirstLastButtons: boolean

**Comment by MayaElf** [comment]
DONE, merged
