### ISSUE TITLE
Update test site: Datepicker element

### ISSUE THREAD

**Issue by b14ckster** [jdi-testing/jdi-light#4929]
**CLOSED as duplicate of #4930** 

At the moment the following features are not presented on angular test site for element Datepicker.
test-site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/datepicker/overview

[ ] Date range picker forms integration
[ ] 
[ ] 
[ ] 
[ ] 
[ ] 
[ ]

**Comment by MayaElf** [comment]
CLOSED as duplicate of https://github.com/jdi-testing/jdi-light/issues/4930
