### ISSUE TITLE
Update test site: Datepicker element

### ISSUE THREAD

**Issue by b14ckster** [jdi-testing/jdi-light#4930]
At the moment the following features are not presented on angular test site for element Datepicker.
test-site: https://jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/datepicker/overview

Examples to add:
- [x] Date range picker forms integration (check the angular site for an example)
- [x] Datepicker emulating a Year and month picker (check the angular site for an example)
- [x] Datepicker palette colors (check the angular site for an example)
- [x] Datepicker action buttons (check the angular site for an example)
- [x] Date range picker comparison ranges (check the angular site for an example)
- [x] Date range picker with custom a selection strategy (check the angular site for an example)
- [x] Datepicker inline calendar example (check the angular site for an example)
- [x] Basic date range picker (check the angular site for an example)
- [x] Datepicker with custom icon (check the angular site for an example)
- [x] Datepicker with custom date classes (check the angular site for an example)
- [x] Datepicker with custom calendar header (check the angular site for an example)

Properties to add:
- [x] color: Primary | Accent
- [x] closeCalendarLabel: 'Close calendar'

**Comment by MayaElf** [comment]
Checked, closed
