### ISSUE TITLE
Tests refactoring: Ripples

### ISSUE THREAD

**Issue by FursovaKate** [jdi-testing/jdi-light#4938]
UPD:
AGREED to delete 'Ripple' element 13 09 23

1. Check JDI-Light framework part, if control implemented correctly,
- [x] Ensure that all the required methods and variables are implemented in the control for it to function correctly in tests.
- [x] Check if all the remaining functionality is working properly.

2. Refactoring tests:
- [x] randomMouseClickTest (in RippleUnitTests)
- [x] add descriptions to tests

3. Verify the correct design and functioning of all existing tests.
 - [x] Perform this check after the implementation is completed.

**Comment by MayaElf** [comment]
UPD:
AGREED to delete 'Ripple' element 13 09 23
