### ISSUE TITLE
Update testsite: checkbox element

### ISSUE THREAD

**Issue by alla-blinkova** [jdi-testing/jdi-light#4948]
At the moment the following features are not presented on angular test site for element CHECKBOX:
test site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/checkbox/overview

- [x] aria-label: string
- [x] color: ThemePalette ("Basic checkboxes example" from the angular site) 
- [x] disableRipple: boolean
- [x] required: boolean

Example for "color":
![image](https://github.com/jdi-testing/jdi-light/assets/26868439/54f39de8-90c7-49fa-a835-275c5ac46043)

**Comment by MayaElf** [comment]
DONE, merged
