### ISSUE TITLE
Tests refactoring: checkbox element

### ISSUE THREAD

**Issue by alla-blinkova** [jdi-testing/jdi-light#4949]
Should be done AFTER https://github.com/jdi-testing/jdi-light/issues/4948 is completed.

1. Check JDI-Light framework part, if control implemented correctly,
- [x] Ensure that all the required methods and variables are implemented in the control for it to function correctly in tests.
- [x] Check if all the remaining functionality is working properly.

2. Tests should be added to cover features:
- [x] aria-label: string - DELETED by NP
- [x] color: ThemePalette
- [x] disableRipple: boolean - DELETED by NP
- [x] labelPosition: 'after'
- [x] required: boolean

3. Verify the correct functioning of all the tests.
 - [x] Perform this check after the implementation is completed.

**Comment by MayaElf** [comment]
PR merged
