### ISSUE TITLE
Update testsite: table element

### ISSUE THREAD

**Issue by alla-blinkova** [jdi-testing/jdi-light#4989]
test site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/table/overview
examples: https://material.angular.io/components/table/examples

At the moment the following examples are not present on angular test site for element TABLE and should be added:
- [x] Adding and removing data when using an array-based datasource
- [x] Adding and removing data when using an observable-based datasource
- [x] Styling columns using their auto-generated column names
- [x] Flex table where one column's cells has a greater height than others
- [x] Tables with toggle-able sticky headers, footers, and columns
- [x] Use of mat-text-column with various configurations of the interface
- [x] Tables with Material Design ripples

For the following existing examples links to the correct examples on the angular site should be added:
- [x] Table dynamically changing the columns (+rename example on test site)
- [x] Table with expandable rows
- [x] Table retrieving data through HTTP
- [x] Table with multiple header and footer rows
- [x] Data table with sorting, pagination, and filtering.
- [x] Table showing each row context properties.
- [x] Table with re-orderable columns

For the following examples links should be fixed:
- [x] Basic use of `<mat-table>` (uses display flex)
- [x] Table with filtering 
- [x] Footer row table 
- [x] Table with pagination
- [x] Table with selection 
- [x] Table with sorting 
- [x] Table with sticky columns
- [x] Table with a sticky footer
- [x] Table with sticky header

**Comment by MayaElf** [comment]
done, merged
