### ISSUE TITLE
Поднять версию Java до 11

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#5042]
- [x] Поднять версию Java на которой компилируется JDI Light до 11.
- [x] Обновить AspectJ до последней
- [x] Обновить TestNG до последней
- [x] Обновить DowloadManager до последней
- [x] Удалить прогон тестов под Java 8 (для JDI Light)
- [x] Удалить прогон тестов под Java 8 (для шаблонов)
- [x] Обновить TestNG у шаблонов

**Comment by pnatashap** [comment]
Исправлено
