### ISSUE TITLE
Investigate a possibility to use mobile test app from Mobitru

### ISSUE THREAD

**Issue by MaksimMeshcheriakovEPAM** [jdi-testing/jdi-light#5091]
Mobitru offers a dedicated mobile test/demo app for training and demo needs. 
Need to consider the possibility to use this app in place of current pretty old demo app

**Expected result:**
Написать 1 тест на JDI Mobile, который будет запускаться локально (под андроид).
По образу и подобию тех тестов что есть в темплэйте.

- [x] Собрать приложение от Мобитру
- [x] Интегрировать в эмулятор
- [x] Запустить мобитрушные тесты (которые идут вместе с приложением)
- [x] Создать проект
- [x] Поднять версию java клиeнта для Appium
- [x] Написать тест на логин форму на JDI Mobile

**Comment by AlexeyGirin** [comment]
See result of investigation here: https://github.com/YatsekTest/jdi-light-mobile-native-mobitru-app-template
