### ISSUE TITLE
Создать пустой шаблон на Selenuim для JDN

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#5249]
В JDN мы вплотную подошли к поддержке Selenium. Соответсвующая задача ( https://github.com/jdi-testing/jdn-ai/issues/585 ) - будет включена в ближайший релиз

Это значит, что после пользователь будет иметь возможность экспортнуть созданные им пэйдж объекты в проект на Selenium.
Для этого нам нужен шаблон.
Разместить его нужно там же где размещён шаблон для JDI Light - в https://github.com/jdi-templates
Репозиторий можно назвать аналогично - selenium-testng-empty-template

И мне нужна краткая инструкция - куда складывать пэйдж объекты, где прописать сайт и адреса страничек

**Comment by pnatashap** [comment]
Will be placed https://github.com/jdi-templates/jdn-template-selenium

**Comment by AlexeyGirin** [comment]
Поменять жаву на 11
