### ISSUE TITLE
Создать пустой шаблон на Selenide для JDN

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#5250]
В JDN мы вплотную подошли к поддержке Selenide. Соответсвующая задача ( https://github.com/jdi-testing/jdn-ai/issues/829 ) - будет включена в ближайший релиз

Это значит, что после пользователь будет иметь возможность экспортнуть созданные им пэйдж объекты в проект на Selenide.
Для этого нам нужен шаблон.
Разместить его нужно там же где размещён шаблон для JDI Light - в https://github.com/jdi-templates
Репозиторий можно назвать аналогично - selenide-testng-empty-template

И мне нужна краткая инструкция - куда складывать пэйдж объекты, где прописать сайт и адреса страничек

**Comment by pnatashap** [comment]
Will be placed https://github.com/jdi-templates/jdn-template-selenide
