### ISSUE TITLE
Обновить шаблон JDI Light для много энвароментности и для запуска через мавен для JDN

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#5260]
### Проблема
Текущий шаблон (https://github.com/jdi-templates/jdi-light-testng-empty-template) который мы используем для экспорта в JDI Light проект - не поддерживает многопоточность и не настроен по умолчанию под несколько энвароментов (хотя бы на уровне закомментированного кода)

Необходимо это исправить

**Comment by pnatashap** [comment]
@AlexeyGirin  про многопоточность - неправда https://github.com/jdi-templates/jdi-light-testng-empty-template/blob/main/src/test/resources/general.xml запуск настроен на 6 потоков по классам, но нужно понимать, что для testng это наша хотелка, он может НЕСМОТРЯ на эту настройку запустить в 1 поток, подумав, что ресурсов маловато или не зачем плодить потоки для 3 тестов. 

Несколько энвайронментов мы не поддерживаем, напиши точнее, что хочется

**Comment by AlexeyGirin** [comment]
Пока откладываем т.к. не очень понятно что значит поддержка нескольких энвароментов.
Нужно побрэйнштормить

**Comment by AlexeyGirin** [comment]
Не актуально.
