### ISSUE TITLE
Tests refactoring: fix Snackbar element tests

### ISSUE THREAD

**Issue by igor-korost** [jdi-testing/jdi-light#5378]
**NOTE:** Эта задача была выделена из задачи https://github.com/jdi-testing/jdi-light/issues/4942 т.к. она была сделана частично и что бы эти изменения не потерять - создана эта задача с тем что было сделано

- [ ] Snackbar refactoring
- [ ] Fix all failing `SnackbarTests` tests (currently 1 test is failing)
- [ ] Migrate tests to the new page (tale care of TODO item)

**Comment by pnatashap** [comment]
@igor-korost why Snackbar refactoring is out of scope? There is no issues with it?

**Comment by AlexeyGirin** [comment]
No actual any more
