### ISSUE TITLE
Documentation on new UI locators

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#56]
Css and XPath > UI
New locators features 
['text']
[*'text']
<
[3]

Tests with no locators and jdi markup for applications
See examples in tests https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-examples/src/test/java/io/github/epam/tests/smart/path/PathTests.java

**Comment by AlexeyGirin** [comment]
Problem - JCheckList and JMenu are not described in the documentation
JPagination - no examples and documentation - decided to delete (@ksenia-vyushkova )
JCheckList - decided to delete (@ksenia-vyushkova )
JMenu - add description to documentation in Menu section (@ksenia-vyushkova )

**Comment by ksenia-vyushkova** [comment]
>JPagination - no examples and documentation - decided to delete (@ksenia-vyushkova )

Done 

>JCheckList - decided to delete (@ksenia-vyushkova )

Done

>JMenu - add description to documentation in Menu section (@ksenia-vyushkova )

No functionality currently implemented. Added an issue instead - https://github.com/jdi-testing/jdi-light/issues/171

**Comment by Dashanchik** [comment]
Documentation is done
https://jdi-docs.github.io/jdi-light/?java#jdi-locators-simple-as-css-powerful-as-xpath
