### ISSUE TITLE
Documentation on Composite elements

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#65]
Write documentation on all methods for 
**Section** - This means to add different types of elements on section and validate that they are not null after Section init (via Site) and use Section (parent) locator as context
- public WebElement
- WebElement
- public static WebElement
- public TextField
- TextField
- public static TextField
- extend PageObject from some BaseClass that extends Section (public class Header extends BasePage; public class BasePage extends Section); place some elements on Base Page and validate that these elements are not null
- Create Section for IFrame with @Frame annotation (use this page https://jdi-testing.github.io/jdi-light/index.html) and validate that elements in IFrame are intractable
- Validate that Base action also work for section (like _isDisplayed_ and all _is()_ validations)
- Add tests for PageObjects that not extend Section and placed on some WebPage

**Form**
- Validate all form actions
- Validate changing FILL_ACTION and GET_ACTION methods
- Validate filters functionality
- Add test for form with overridden fillAction() and getAction()

**WebPage**
- Add @Url and @Title validation tests with all combinations of these annotations params (including cases where some annotations missed)
- Add tests on all Page actions
- Add the same tests as for Section
- Add tests for PageObjects that not extend WebPage and placed on some Site

**Comment by AlexeyGirin** [comment]
Decomposed on three other issues - #130, #131, #132
