### ISSUE TITLE
Invalid message while can't init some elements from the page.

### ISSUE THREAD

**Issue by IrinaTuzikova** [jdi-testing/jdi-light#68]
Instead of concrete element value can see the message :: 
java.lang.RuntimeException: 
Can't init page 'generalReportsPage' on 'C2CSite'. Exception: java.lang.RuntimeException: java.lang.RuntimeException: 
Can't setup field 'generalReportsPage' on page ''. No setup rules found (you can add appropriate rule in InitActions.SETUP_RULES)
**Actual behavior::**
Where the second string should be filled by not valid element parameters. Not the name of the page and the empty string 
**Expected behavior::**
The name of the element which can't be init.

**Comment by igordien** [comment]
@IrinaTuzikova, this issue is fixed starting from version 1.0.31.
