### ISSUE TITLE
java.lang.NullPointerException for UIList<DashboardItem, ?>.get("...")

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#70]
Precondition: 
@XPath("//*[contains(@href, '%s')]")
public UIList<DashboardItem, ?> documents;

public class DashboardItem extends Section {
    @UI(".document-actions")
    public DocumentActions menu;
}

public class DocumentActions extends HtmlElement {
    private Button documentActionsBtn= $(new By.ByCssSelector("[qa-item='document-actions-btn']"), this);
    private WebList actions =  new WebList(new By.ByCssSelector("[qa-item='%s-btn']"));
    @Override
    public void select(String name) {
        documentActionsBtn.click();
        actions.select(name);
    }
}

documents.get(document.uid) - throw java.lang.NullPointerException

**Comment by yanusa3** [comment]
Now the error is different:
java.lang.RuntimeException: 
[49:00.23] 
Failed to execute 'get' for element 'Documents' action during '25' seconds. Exception: 
Expected at least 1 elements but failed (DashboardPage.documents (xpath='//*[@qa-item='document-title-link' and contains(@href, '**VALUE**')]/../../..'))

**Comment by AlexeyGirin** [comment]
@RomanIovlev please provide an access for testing site to @PetelimovaNadezhda and @elv1s42

**Comment by AlexeyGirin** [comment]
The issue has been fixed.
