### ISSUE TITLE
JList<Item>.getSize() take 26 sec

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#71]
getSize() for JList take 26 sec

Precondition:
@UI("[qa='item']")
JList<Item> items;

public class Item extends UIElement {
    public HtmlElement status = $(new By.ByCssSelector(".badge"), this);
}

//first time fast call
items.size(); // < 1 sec;

//second time very slow
items.size();// > 20 sec

**Comment by yanusa3** [comment]
1.0.45 - still reproduced

**Comment by AlexeyGirin** [comment]
Dear @yanusa3 , we can't reproduce your issue, please contact with @kasdar23 in Skype to help her reproduce the issue

**Comment by AlexeyGirin** [comment]
Waiting for @RomanIovlev decision regarding this issue

**Comment by AlexeyGirin** [comment]
@yanusa3 please contact w/ @RomanIovlev or @kasdar23 regarding this issue - we can't repro it
