### ISSUE TITLE
Element not initialized

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#72]
Precondition:
public static Page page;

public class Page extends WebPage {
    @Css("[qa='export-modal']")
    public DocumentExport export;
}

public class DocumentExport extends Section {
    public Select selectDocumentVersion;
    public Checkbox checkboxIncludeDeletePending;
    public Checkbox checkboxIncludeToc;
    public Button btnCancel;
    public Button btnExport;
}

page.export.selectDocumentVersion - is NULL!

**Comment by sandraj-cuelogic** [comment]
Check if there are similarly named element as `@css("[qa='export-modal']")`. If yes, there may be the issue. As if there are multiple elements with the same name in the DOM, selenium may not be able to find the right one to initialize it.

**Comment by RomanIovlev** [comment]
@yanusa3 Select element is not JDI element so it is not initialized
