### ISSUE TITLE
Shift index for all elements except WebElement

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#782]
Shift index for all elements except WebElement

**Comment by AlexeyGirin** [comment]
1. Делаем два набора - первый это наши классы с нашими листами с 1 и они доступны пользователю
второй - их дубликат и работает с селениумом и лежит в отдельном пакете и не доступен пользователю из тестов и из кода
только фрэймворку доступно
2. надо переделать все методы которые использовали гееиндекс-1 на использование первого набора

3. проаанализировать все классы и возможно упростить код используя классы с 1

**Comment by AlexeyGirin** [comment]
Критерии проверки - у нас должно появиться 3 новых класса в селениуме, а те три старых остаться как были, три новых класса используются только в InitActions, а старые классы используются везде в остальных местах

**Comment by troe88** [comment]
Should be closed.
