### ISSUE TITLE
Wrong procceeding of HTML table

### ISSUE THREAD

**Issue by EDbarvinsky** [jdi-testing/jdi-light#860]
If I create an JTable element and trying to get it row, then I get an Runtime exception, otherwise if I am trying to get an webRow, than everything passes well, but the last column, which contains totally the same text as previous one merged into one value.
e.g.
|header1|header2|header3|
|value1   |value2   |value2  |
|value3   |value4   |value5  |

WebList row = PageWithTabletable.webRow(1);
System.out.println(row.getText)

Result of SOUT looks like:
expected: [value1, value2, value2]
current: [value1, value2]

**Comment by pnatashap** [comment]
Tables were changed in many places. 
Closing as we can not check. Please create a new issue with html markup example for investigation
