### ISSUE TITLE
Travis CI fail

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#87]
Travis build always fail because can't get driver name from properties
in log you can find: "Unknown driver: ${driver}"

Need to identify the problem and fix it

**Comment by AlexeyPlatkovsky** [comment]
Fixed - travis passes variable for driver in maven command now

**Comment by AlexeyGirin** [comment]
Another problem has detected - @RomanIovlev please have a look - problem with multithreading
