### ISSUE TITLE
Some tests failed in Firefox

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#89]
Some tests failed in Firefox but passed in Chrome
Need to look through this tests and fix them
FileUploadTests.downloadTest
DropdownTests.disabledTest
MultiDropdownTests.assertValidationTest
MultiDropdownTests.baseValidationTest
MultiDropdownTests.disabledTest
MultiDropdownTests.getValueTest
MultiDropdownTests.before (4)
MultiDropdownTests.isValidationTest
MultiDropdownTests.labelTest
MultiDropdownTests.selectEnumTest
MultiDropdownTests.selectNumTest
MultiDropdownTests.selectTest
MultiDropdownTests.selectedTest
DataTableTests.previewTest
FormsTests.loginTest

**Comment by AlexeyGirin** [comment]
Demo has been done.

**Comment by kasdar23** [comment]
Tests have been fixed:
 FileUploadTests.downloadTest     
 MultiDropdownTests.assertValidationTest
 MultiDropdownTests.baseValidationTest
 MultiDropdownTests.getValueTest
 MultiDropdownTests.isValidationTest
 MultiDropdownTests.labelTest
 MultiDropdownTests.selectTest
 MultiDropdownTests.selectedTest

**Comment by kasdar23** [comment]
Test have been fixed:
DataTableTests.previewTest
FormsTests.loginTest

**Comment by kasdar23** [comment]
Tests don't work for the same reason: method check() for MultiSelector.
MultiDropdownTests.selectEnumTest
MultiDropdownTests.selectNumTest
MultiDropdownTests.selectTest
I don’t know how to fix it.

**Comment by kasdar23** [comment]
DropdownTests.disabledTest
Method select() for Dropdown ignores the “disable” and allows to select any of the elements
I don’t know how to fix it.

**Comment by kasdar23** [comment]
And in FireFox browser screen doesn't maximize.

**Comment by AlexeyGirin** [comment]
@RomanIovlev please have a look

**Comment by PetelimovaNadezhda** [comment]
Now DRIVER_NAME may not  has name firefox, but Driver2, for example
Show(jdi-light\jdi-light\src\main\java\com\epam\jdi\light\driver\WebDriverFactory.java)
So
if (isFireFox()) return;
protected static boolean isFireFox() 
        return DRIVER_NAME.toLowerCase().equals("firefox");
in  MultiDropdownTests, FileUploadTests.downloadTest, DropdownTests.disabledTest do not work now

**Comment by 886-59-936** [comment]
https://github.com/jdi-testing/jdi-light/pull/1715

**Comment by 886-59-936** [comment]
Tests fixed. New issue created: https://github.com/jdi-testing/jdi-light/issues/1756
I suppose that this issue could be closed and if some tests will fail again - new issues should be created for specific test cases.

**Comment by romaha08** [comment]
Demo has been done
