### ISSUE TITLE
Create Html elements examples

### ISSUE THREAD

**Issue by RomanIovlev** [jdi-testing/jdi-light#9]
We need to add description to all types of html elements
Html elements placed: http://epam.github.io/JDI/html5.html
Each section needs:
- TITLE
- Short description
- W3C link
- Mdn link
- Element Methods
- Link to code examples (later) 

Html code can be changed in https://github.com/epam/JDI/tree/gh-pages

**Comment by owl-se** [comment]
Hey @RomanIovlev , please take a look at my branch, "gh-pages-html5-upd"
I've marked my questions in bold section, also I'm not quite sure about different input types <>

**Comment by owl-se** [comment]
One more small fix

**Comment by RomanIovlev** [comment]
1) Make all links with href and target="_blank"
<p>W3C: <a href="https://www.w3schools.com/tags/tag_a.asp" target="_blank">https://www.w3schools.com/tags/tag_a.asp</a></p>
2) Add more methods from internal interfaces (extend) for all elements
