### ISSUE TITLE
Button Section on HTML 5 Elements Page contains wrong links to W3C & MDN.

### ISSUE THREAD

**Issue by antonfilichkin** [jdi-testing/jdi-light#90]
https://epam.github.io/JDI/html5.html
has to be:
W3C: [https://www.w3schools.com/tags/tag_button.asp](https://www.w3schools.com/tags/tag_button.asp)
MDN: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)

![html5page](https://user-images.githubusercontent.com/41286257/56044050-12253400-5d47-11e9-89df-2091dcd5c49d.png)

**Comment by AlexeyGirin** [comment]
Do the same in JDI-testing/java github (i.e. move changes from epam/JDI git to JDI-testing/java)

**Comment by AlexeyGirin** [comment]
Demo has been done.
