### ISSUE TITLE
Implement boostrap element: Modal - Live demo

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#952]
In the context of #15 decomposition
In the context of #527 decomposition

0. Link to the given element: https://getbootstrap.com/docs/4.3/components/modal/#live-demo
1. Implement given bootstrap element (if the element has some variation - please parametrize) and put it here: https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap
Use HTML elements as a reference example
2. Create a page object for a given element,
3. And cover with tests all element methods, put tests to here: https://github.com/jdi-testing/jdi-light/tree/bootstrap/jdi-light-bootstrap-tests
4. Update documentation (add methods and examples, add links to test - in the same manner as it is done for HTML elements) 
5. Add JavaDocs for a given element
6. Add a link to bootstrap element to bootstrap documentation, put it above class implementation (see https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html/elements/common/Button.java as an example)
7. Move given element article to proper section (common, complex or composite) depending on the implementation

**Comment by troe88** [comment]
Demo has been done.
